* user selection

* done download tags
ideally iteratively: need to get tags also later on
-> should check whether tag downloaded already

tag <-> artist network? 
idk
not that many tags -> 

* tag space
- convex hull of hypervolume
- box

additional: 
- how clear is space: how many works are in there that are not of tag
- distribution: how are artists in space of tag distributed along other tags


how to deal with tag weights
- 2/3 layers: core (75+), medium (35-75), periphery (5-25)




* check tag technicalities
** histories
tags added to website between june and september 2005

maybe add website changes as dummies for website changes (exogeneous shocks)



** done bit unhyped by the little time period: 8 years at most
# fucking retards why did they stop recording so early

-> ask if you can get name? 

gabriel@music.mcgill.ca

Dear Dr. Vigliensoni, 

thank you for the MHLD! I am currently a master student in cultural sociology at the University of Amsterdam and plan to use it for my master thesis. Would it be possible for me to get access to the original user names to collect additional data on how the listening histories have developed in the last years? 

Best, Johannes Aengenheyster


I plan on using the 


** set unit of analysis
- artist
- album
- song

nested structure? 

* popularity of UoA over time

* done normalized stress MDS
correlate distances (original and new from MDS?)
http://cognitionandreality.blogspot.com/2015/04/computing-fit-of-mds-solution-using-r.html
 
https://github.com/scikit-learn/scikit-learn/pull/10168
divide by sum of squared distances? test with R: 

10 dims
- R: 8.94
- python: 0.095

2 dims: 
- Python: 0.238 
- R: 26.63

somewhat similar
# maybe diagonals get counted differently? 
python slightly better at few dimensions, R very slightly better at many dims


* computing power
** done info and request
space on 81GB: delete windows files? 

Dear SurfSara Helpdesk, 

I am currently a student in the Research Master Social Sciences at the University of Amsterdam, where for my master thesis I am studying musical consumption patterns. One potential dataset that I consider using exceeds the my computer in terms of storage (hundreds of GB) and processing power, and upon mentioning this to my supervisor Alex van Venrooij, he mentioned your organization. Would it be possible to get access to the computing resources for a masters thesis? 

Best, Johannes Aengenheyster




* substitutes and complements
some tags may be dependent on others 
isn't that legitimation tho? 

female vocalist and chillout

* different groups use different tags for same thing? 

* asymetric competition coefs
can't be reduced to single space

is specialist similar to generalist
or generalist similar to specialist

north korea more similar to china than china to north korea
-> specialist more similar to generalist than generalist to specialist

-> ask alex, do tags first

* improve reading in edges
** done bash processing 1
atm quite some entries in artist names that are not bids
maybe length requirement? 


** todo bash processing 2: read in from multiple folders
symlink dir with all country

simultaneous sub processes to pre-process? 

run in 01/02/03 folder, then swoop up afterwards to be able to read from csv? 



** todo bash processing 3
unclear whether to weigh edges
could be done with Counter
similarity doesn't 

** done data filtering per timepoint
can be done with awk



* structural equivalence
to go from what to how? 


* secondary
** personal tags

http://ws.audioscrobbler.com/2.0/?method=user.getpersonaltags&user=rj&tag=rock&taggingtype=artist&api_key=607aa0a70e1958439a7de088b66a4561

would need user and tag: 50k users, 1k tags -> 50m requests
seems i can look up who gave what tags 


also would have to identify users first
-> secondary

** identifying users
would need to scrape last fm top listeners

would get 270 per artist

download histories
test for matches

not sure about approach: 
- focus on user, as in trying to id user based on the artists
- focus on artists: see which top listeners are in my dataset

maybe both: first user to select artist, then see who of the 270 can be ided? 

or primarily artist based: have the hunch it gives more findings: always everybody can be ided

** additional analysis: consequences of legitimacy
study band success based on how legitimated their tags are?
or does that become circular?
idk:
would be if a tag is legitimate if it is popular
but i think measure of legitimacy does not rely on popularity, 
