* Proposal: fluctuations of genre popularity
** intro

** theoretical framework
*** notes
-> RQ

category emergence/abandonment
-> institutionalization

dillution
preference for popularity

boundaries: tags -> shows what people think
-> listening and tags should align 
# but no temporal stuff on tags fUUUUUU
I NEED MEANING

lyrics? musical features? -> topic modeling
# oh boy so much data

# - 5: Òscar Celma. Music Recommendation and Discovery: The Long Tail, Long Fail, and Long Play in the Digital Music Space. Springer-Verlag Berlin Heidelberg,Berlin, Germany, 2010.
# - 7: Gideon Dror, Noam Koenigstein, Yehuda Koren, andMarkus Weimer. The Yahoo! music dataset and KDD-cup’11. Journal of Machine Learning Research,
# - 4: Iván Cantador, Peter Brusilovsky, and Tsvi Kuflik.Last.fm web 2.0 dataset. In 2nd Workshop on Informa-tion Heterogeneity and Fusion in Recommender Systems, RecSys 2011, Chicago, IL, 2011.
# - 13
# - 8: EMI Group Limited. EMI Million Interview Dataset,2012.http://musicdatascience.com/
# 19
# 9
# 24
# pretty much all useless: no artist tags


# no tag history: all variation in tag is with change in artists

# even if i could get tags it would be aggregate -> would need to get which tags were added when 

density 
legitimacy

attention

typicality

microfoundations

*** text 
From a neo-institutional perspective, oranizational forms have to adhere to rules/standars of legitimacy to be successful parencite:diMaggio_1983_iron,Zuckerman_1999_illegitimacy, often resulting in homogenization. 
#
Such emphasis on reliance on pre-existing standards has problems to explain the emergence of new forms. 
#
#
However, concepts from organizational ecology such as cross-form legitimation, density dependence and saturation have been shown to explain form emergence parencite:Ruef_2000_emergence
#
Additionally, the emphasis on individual-level cognitive processes of quality inference from popularity parencite:Strang_2001_excellence as well as variation in individual preferences and 'dilution' effects parencite:Kovacs_2014_paradox have been proposed to explain the dynamics of organizational forms. 
#
~lieberson~



declarative and non-declarative

is non-declarative (listening habit) even useful for changing times (genre emergence)? 
#
declarative: tags? 
#


2007 tags are there




** Issues: 
The population (predominantly young and male) might not adhere to genre boundaries to an extent that results in clear boundaries. 
# 
Similarity measures might therefore be unreliable when users listen to a large number of artists that they do not consider similar. 
# 
On the other hand, one might still expect patterns in the aggregate. 
# 
Playlists might be a useful as in these listeners group objects together on perceived similarity, and therefore would be a good application of practical classification systems parencite:van_Venrooij_2018_fuzziness. 
# 
However playlist data is not available from last.fm, and I have not been able to get access to the so-called Million Playlist Dataset (MPD) by Spotify. 
# ask the DGS people? 


The sample might be generally be unrepresentative.  


** Identity
Artists can be tagged by users. 
# 
While there is no breakdown by who tagged which artist, tags are weighted on a scale from 1 to 100 (the most frequent tag always is always 100). 
# 
Once genres are constructed from a similarity measure, it should be possible to construct the tags associated with each, and therefore get a measure of how clear of an identity a genre has at each point in time. 
# 
I assume that a clear identify enhances survival prospect cite:Zuckerman_1999_illegitimacy,Hsu_2006_jacks. 
# 
A clear identity can be also seen as successful institutionalization, as it corresponds to the construction of a cognitive layer which solidifies the common aesthetic elements of a set of works to the degree that they become taken for granted parencite:Powell_1991_introduction. 
# 
This process similarly corresponds to the prototype view parencite:Murphy_2004_concepts, in which a general concept that that either lists the features of a category or additionally, posits relations between the is constructed from a set of items in a process of abstraction. 
# 
A clear identity might stand in contrast to popularity, as it might be easier to maintain a clear identity. 
#
Reversely, it might be that larger genres develop more 'momentum' and through institutionalization reach more clarity, yet it could also be that a clear identity is a precondition for growth in the first place. 

** fields
#
The trivial saying that social phenomena do not take place in a vacuum undoubtedly applies here as well, and the environment and relation to other genres might be have crucial impact. 
# 
ecology; 
# can i even model overlap if i use artist similarity for construction in the first place

fields: 
- relations to other things than other genres? 

is legitimation 
- field process? nope: fields more about power, less about consensus/shared meanings which is required for legitimacy
- ecology: yup: 
- institutionalism? yup: adherence to institutional logic  
  positing an institutional logic per genre would not be very parsimonious tho


ecology: resource: are there 'areas' in teh musical space that do not have many genres? 



** micro-processes
people: does it matter if people are more omnivorous? 
- more omnivorous -> might be less 'committed' to genre
- more omnivorous -> might be more open? 

# Kovacs: 
# - popular -> cool to hate
#   seems unlikely? might overemphasize distinction (hcc mentality)
#   rather seems to me that genre failure will be mostly in infancy
#   if genres are established that avant-garde thinks its cool to hate them they will have dedicated (intrinsically motivated) following 

#   or does it? petit-bourgois mentality might be everywhere, trying to imitate HCC
#   but shift to way, not object (was actually always the case (Kantian aesthetic vs necessity))
  
Ruef: multiple parents
-> what does one genre take from those that predate it? 
- artists first in one, then later genre? also albums, songs
- listeners?: how many listeners are passed on? 
   or do i use them to create genres in the first place? 


It is furthermore relevant to consider the individual-level processes through which macro-level mechanisms are mediatated. 
# 
textcite:Kovacs_2014_paradox postulates that two mechanisms that lead to short-term devaluation might have long-term consequences. 
# 
First, he finds that status attracts audiences not who are not intrinsically attracted and hence devalue the object due to lack of fit with their personal evaluation criteria. 
# 
Second, he finds that increasing popularity results in more devaluation by audiences who dislike popular products and want to distinguish themselves from 'mainstream' objects. 
# 
Both these measures should be relatively straightforward. 
# 
While it is presumably most convenient to aggregate them to the level of genre, I do not think that this diminishes their explanatory power. 
#
However, I wonder if maybe textcite:Kovacs_2014_paradox, particularly in the second mechanism, 'imposes' a high cultural capital mindset (distinction) as general mechanism (something that e.g. textcite:holt1998does warns against). 
#
It further seems to me that the assumptions of the first mechanism, namely an intrinsically interested audience, to some degree limit the effect of the second, as these are presumably not easily swayed by short-term shifts in public opinion. 
# 
Obviously, only empirical analysis can settle these matters. 

*** para :ignhead:
The impacts of other personal-level variables are also worth investigating, such as ~omnivorousness~ parencite:peterson1996changing (or more precise, atypicality and variety parencite:Goldberg_2016_span).
# 
Omnivores might be less committed to a particular genre as their ~identity~ is to span different genres, yet their openness parencite:Roose_2012 might nevertheless make them willing propagators of new forms. 
# 


*** field :ignhead:
# 
Some field-theoretical insights might also be integrated. 
# 
While musical production has only weak links to state control or legislative requirements, it can be expected that music producers are nevertheless keen observers of their organizational environment, consisting of other artists, as well as record labels and radio states ~and~. 
# 
~In particular, one might say that links to other artists are either cooperative or competitive~




Tfp: not just how many like it, but who: is it liked by people with lower TfP? then good





*** tag issues
However, no temporal data on tags is available, i.e. the tags and their weights  would reflect the cumulative history which would pose problems if artists are changing their styles over time. 
# 
This might be alleviated to some degree by focus on albums or even songs as these are much more associated with the point of time of their release (although this does not for canonical works which remain popular cite:Anand_2000_sensemaking). 
# 
Furthermore, a finer levels means that the tags themselves are sparser. 
# 
Additionally, even single albums or songs might be interpreted differently throughout time, albeit I think that this does not occur to an extent that it would have a substantial impact. 
#


** crises in neighboring fields
# 
could be
- positive: more resources (i.e. when fields are competing)
- negative if it kills legitimacy: 
-> what are relations between genres? 

Kovacs: imposes HCC mindset (distinction) as general cultural mechanism (something that e.g. textcite:holt1998does warns against). 
# 



** reflect on meetings: websites
# topic is changes in popularity of genres
# why is listener network data approach better? 
# no imposition of genres
# non-declarative (actual useage, not conscious)
# 

It strikes me as somewhat ironic that a cognitive criticism of surveys is their exclusive focus on declarative culture which may be only tangentially related to action, yet the reverse is the case here as behavioral is readily available but little insights are available of the cognitive that underlie the actions (yet since the cognitive critique also stresses the loose coupling between declarative and non-declarative culture, it is not clear if attitudinal data would provide additional insights, and hence might only serve as a confirmation of the loose coupling). 
# 





** Issues 
focusing on the relation between users and artists (or works) might ignore external influences, such as promotion efforts. 





** Data and methods
*** notes

*** text
This thesis will study the fashion dynamics of genres (organizational forms) of popular music. 
#
Longitudinal data 


tags: crawl through the rateyourmusic archive.org sites to get tags? but don't know where they're coming from either

# cluster all time periods, group similar ones together (across time?)
# might merge multiple from years
# then so be it? 
# assumes genre can't change completelyl
# maybe just similarity within window? like marieke: only current/previous year...

** 
tags: identity/perception: does group have a stable identity/is it perceived to be different 
textcite:dimaggio1987classification: *socially constructed organizing principles*
is clear abstraction formed? 


questions: start with tags, or with networks/connections

* technical
big data: pre-processing in python? 
graphtool? 


google analytics for the frequencies


