#+latex_class: article_usual2
# erases make title
#+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
# #+OPTIONS: toc:nil#+TITLE: #+AUTHOR: #+DATE: 
#+OPTIONS: h:5





* Thesis Proposal: Fashion Dynamics of Musical Genres 
** Introduction
# 
The primary aim of this thesis is to investigate changes in genre popularity (size) with a particular focus on abandonment, i.e. the disappearance of a form.
# 
Mechanisms that explain these changes incorporate environmental, genre-level and individual mechanisms, such as competition with other genres, fuzziness of genre identity, and composition of genre in terms of listeners. 
# 
# As parencite:Sewell_1996_inventing argues, small ruptures of established structures take place every day, however most are absorbed, neutralized or repressed and hence lack the momentum to result in permanent changes. 

** Theoretical Framework

*** Conceptualizing Genres
**** what is genre? 1 :ignhead:
# 
# Genres constitute a key term in cultural sociology. 
# 
Genres can be defined as "socially constructed organizing principles" or "aggregation principle enables observers to sort products into categories" [[parencite:dimaggio1987classification][p.441]]. 
# 
They can therefore be considered as organizational forms cite:Ruef_2000_emergence which consist of a blueprint of typical features and values for assessing objects. 
#
Given the general importance of categories and categorization for sense-making and action  parencite:Zuckerman_1999_illegitimacy,Negro_2011_winemaking,Hsu_2015_granted, their development cite:Ruef_2004_demise,van_Venrooij_2015_ecology, persistence cite:Lounsbury_2004_sources, change cite:Negro_2011_winemaking and disappearance cite:Strang_2001_excellence,Ruef_2004_demise is of substantial interest. 
# 
Genres furthermore do exist not in isolation and have to be considered in relation to both other genres, e.g. by mapping them into a conceptual space parencite:Hannan_2019_concepts, and their audiences [[parencite:dimaggio1987classification][p.441]]. 
# 
It is variation in these relations that can be seen as resulting in variation in genres on a number of aspects, such as their size, complexity, concentration parencite:Lounsbury_2004_sources or the fuzziness of their boundaries parencite:Hannan_2010_partiality,van_Venrooij_2018_fuzziness which in turn can be expected to result in variation in long-term survival chances. 
# 
With such a relational perspective, the actual content of the genres (what feature values which an object would have to adhere to to be considered a typical member) become secondary. 
# 
Nevertheless, with a focus on the categories which audiences use to make sense of the world, attention has to be given to cognitive associations and routines that become taken for granted and thereby form a key part in the establishment and institutionalization of new organizational forms. 


# textcite:dimaggio1987classification also discusses genres as "sets of works classified together on the basis of perceived similarities" (p.441); ~an aspect that also has to be considered~.
# Rather than defining genres in terms of form or content, I plan to focus on the "social relations among producers and consumers", 
# # 
# While textcite:dimaggio1987classification based on these considerations conceptualizes genres as 

#  (p.441), it seems to me that not only explicit classifications of objects are indicative of genres, but that of implicit usage data (in this case, listening records) should also enable the linking of particular objects to particular audiences. 
# # 
# This does not mean that perceptions of 
# 
# similarity or other cognitive processes are not worthy of considering, as on the contrary, the development of # 

# **** Identity :ignhead:
# # 
# A genre is however not just an abstract 


# but (according to the prototype view of cite:Murphy_2004_concepts) it also requires a the formation (institutionalization) of a somewhat abstract, yet able to be taken-for-granted concepts which can be used in the assessment of newly encountered works (rather than requiring comparison to all individual elements). 
# # 
# These "socially constructed organizing principles" [[parencite:dimaggio1987classification][p.PAGE]] 


# 
# 

#  fuzziness, which, given that fuzziness has substantial impacts on individual objects parencite:Zuckerman_1999_illegitimacy,Hsu_2006_jacks which
# 
# A clear identity might stand in contrast to popularity, as it might be easier to maintain a clear identity. 
#
# Conversely, it might be that larger genres develop more 'momentum' and through institutionalization reach more clarity, yet it could also be that a clear identity is a precondition for growth in the first place. 

**** Resource distribution :ignhead:
# 
# Another relevant genre-level variable might be the resource distribution; one can imagine an ideal-typical contrast between concentration where few artists account for the majority of listeners with a relatively evenly spread distribution 
# 
# While this might impact survival chances, albeit I cannot think of a clear direction so far. 
# parencite:Ruef_2000_emergence

*** Micro-processes
**** kovacs :ignhead:
It is furthermore relevant to consider the individual-level processes through which macro-level mechanisms are mediatated. 
# 
textcite:Kovacs_2014_paradox postulate that two mechanisms that lead to short-term devaluation might have long-term consequences. 
# 
First, they find that status attracts audiences not who are not intrinsically attracted and hence devalue the object due to lack of fit with their personal evaluation criteria. 
# 
Second, they show that increasing popularity results in more devaluation by audiences who dislike popular products and want to distinguish themselves from 'mainstream' objects. 
# 
I assume the measurement of both these mechanisms to be relatively straightforward. 
# 
While it is presumably most convenient to aggregate them to the level of genre, I do not think that this diminishes their explanatory power. 
#
# However, I wonder if maybe textcite:Kovacs_2014_paradox, particularly in the second mechanism, 'impose' a high cultural capital mindset (distinction) as general mechanism (something that e.g. textcite:holt1998does warns against). 
#
# It further seems to me that the assumptions of the first mechanism, namely an intrinsically interested audience, to some degree limit the effect of the second, as these are presumably not easily swayed by short-term shifts in public opinion. 
# 
# Obviously, only empirical analysis can settle these matters. 

**** TfP :ignhead:
# 
Especially the second mechanism seems to be related to what parencite:Zuckerman_2012_valuations,Lieberson_2003_popularity label Taste for popularity (TfP). 
# 
TfP on its own might furthermore be relevant insofar as it could not only be the mere number of a listening audience that is considered, but also its composition. 
#
In particular, one might imagine that an actor with medium TfP would be more enticed by a genre that is consumed by a small number of avant garde than one that is just being abandoned by the last audiences with a high TfP, as the former provides much more potential for distinction than the former which has already been chewed through by large parts of the population.  


**** other individual-level variables :ignhead:
The impacts of other individual-level variables are also worth investigating, such as omnivorousness parencite:peterson1996changing, albeit the rather unprecise term might be specified in a less ambiguous way by building on for example textcite:Koppman_2016_different (omnivorousness taste by distinctiveness) or textcite:Goldberg_2016_span (taste for atypicality and variety). 
# 
'Omnivores' might be less committed to a particular genre as their 'identity' based on spaning different genres, yet their openness parencite:Roose_2012 might nevertheless make them willing propagators of new forms. 


*** Environmental Influences

# the properties of the location of the musical space in which they emerge parencite:Lizardo_2009_comparative,Hsu_2005_form


Next to the internal composition of a genre, the relationship to its environment needs to be taken into account. 
# 
Primarily insights from organizational ecology can be incorporated here such as density of the musical spaces in which they reside parencite:Hannan_1977_ecology,Carroll_1989_density,Hannan_1992_dynamics, competition over resources which in this case are listeners parencite:Mark_1998_feather, saturation of different niches parencite:Ruef_2000_emergence,Ruef_2004_demise and reaping the benefits of form legitimation performed by other actors parencite:van_Venrooij_2015_ecology [fn:: it also seems that social movement concepts such as contagion and bandwagoning might be useful, but I did not have the time to explore them properly]. 
# 
Compelling concepts might also be gained by incorporating field-theoretical approaches, such as the primary focus on actors (or more precisely, incumbents and challengers) which in "the aggregate constitute a recognized area of institutional life" [[parencite:diMaggio_1983_iron][p.148]]. 
# 
Considerations of how their perceptions, evaluations, strategies, decision making, and alliances parencite:Fligstein_2015_fields,Anand_2006_charting would contribute to field emergence, settlement and rupture would certainly provide valuable insights. 
# 
However, the complexities involved in taking into account the large number of actors which next to other artists would also increase for example record labels, radio stations and other distributors as well as the relations between them presumably is beyond the scope of this study. 
# 
As this focus on the relations among artists and to consumers leaves out a number of key actors, caution has to be exercised to avoid misattributing effects, in particular as the textcite:Fligstein_2015_fields consider the relations to outside actors as key predictors of field stability or change (while one might grant music is only slightly regulated by the government, textcite:rossman2012climbing still highlights the importance of outside actors and exogeneous shocks). 
# 

**** further limitations :ignhead:
Further elements that I think are beyond the scope of the thesis are considering the aesthetic elements themselves such as lyrics or musical features such as beats per minutes, tonal frequencies or instruments as genres are primarily seen as a set of objects which has similar relations to audiences parencite:dimaggio1987classification. 
# 
While especially latter ones seem to be used in recommendation systems, and while inclusion of this would certainly be an enrichment parencite:van_der_Laan_2016, I assume that an approach that focuses on the relations between objects and audiences parencite:Emirbayer_1997 is preferable given the time constraints. 


# Tfp: not just how many like it, but who: s it liked by people with lower TfP? then good


** Operationalization
*** Data
**** tags :ignhead:
It seems that the last.fm tag system is a suitable case study the trajectories of categories, as last.fm  allows its users to label artists, albums and songs with arbitrary tags. 
# 
Last.fm provides information on these tags through its API by listing tags as well as their relative frequency: 
#
Tags are weighted on a scale from 1 to 100 (the most frequent tag always is always 100) [fn::While it would be even more desirable to know which user tagged which artists, this information would require the usernames, which are not available for the by far most extensive datasource]. 
# 
This partiality or grade of membership can be fruitfully exploited to make inferences about genre properties such as fuzziness or concentration. 
# 

**** MLHD :ignhead:
However as only aggregate, but no temporal information on tags is available, the popularity of the items over time has to be analyzed with different means. 
# 
It seems that the Music Listening History Dataset (MHLD, cite:Vigliensoni_2017_mlhd) is well suited for such an approach. 
# 
It contains the last.fm listening histories of over 500,000 people which have at least 7300 entries, resulting in a total of around 27 billion entries. 
# 
Information is hence available at a very detailed level, which allows to track with great accuracy the compositions of each genre in terms of audience characteristics. 
# 
Similarly, the information of user data can be used to position the genres (through the items) in musical space which therefore also allows to investigate the impact of environmental conditions. 

**** more descriptions :ignhead:
Country, age and gender are available for approximately two thirds listeners, especially country might be useful as it might be necessary to focus only on one country due to the large amounts of data (the total dataset has a size of over 500 GB). 
# 
Each entry for a user consists of a (unix) timestamp and musicbrainz identifiers for the song, the album and the artist. 
#
Due to the high numbers of artists and users, it seems that an effective way to analyze this data is to treat it as a network. 
# 
While the construction of a complete adjacency matrix would require extensive resources due to the high number of both listeners and artists, by treating each log file as an edge list it is possible to construct a two-mode network with the first mode being the user, and the second the artist, album or song [fn::Presumably it would be possible to construct a multi-mode network as well, but this seems too complicated to me for now]. 
# 
The choice whether to take the artist, album or song as the second mode is still open. 
# 
As there is no temporal information of an item's tag associations available, albums and songs might be preferable as they can be expected to accumulate different associations over time to a lesser extent than artists do (whose tags might reflect their entire production) and hence offer better reconstruction of the popularity of genres over time. 
# 

# So far I've been using graph-tool, a python library which so far has been able to load and process a subset of 6000 users and several million edges in each 3 month time chunk. 
# albeit analytically I have only calculated similarity scores so far, not more network-based approaches such as community detection. 
# 
# I still have to investigate how it performs with larger files, I am however slightly optimistic that it is up to the task as so far it could handle everything I've tasked it with. 

*** Analysis
**** genre measures :ignhead:
# 
It is relatively straightforward to calculate at for a period in time a number of measures for each genre (tag) that fulfills some conditions, such as a minimum number of artists that it is assigned to and/or minimum weights with which it is assigned to these artists. 
# 
The popularity of a genre can for example be constructed by summing up the products of tag weight and item play count for each item the tag is applied to. 
#
Concentration can be assessed with the Gini index (or other measures of inequality or concentration) of these products[fn::(as it might also be seen as an indicator of fuzziness, more work has to be spent on the concrete operationalisation)], and it might be possible to assess the cohesion of a genre with the (bipartite) connectedness of the sub-network of the relevant items and their listeners. 
# 
Measures such as overlap can on the one hand also be calculated from the two-mode network, for example by investigating the overlap of nodes of two tags (those that are labeled with both tags)
# 
Alternatively, it is possible to map node positions into a lower-dimensional space based on similarity scores using multi-dimensional scaling. 
# 
This practice would then also result in relatively straightforward measurements of niche width. 
# 
Eventually this approach would result in all relevant measures available for each genre for each time period, which can then be analyzed using fixed and/or random effect models. 


# Due to the relational approach outlined above, it seems to me that it should be possible to construct genres by grouping artists (or albums or songs) based on similarity, which in turn is based on the extent to which these objects share a common audience at a particular point in time. 
# # 
# I am not yet clear which similarity measure precisely to use. 
# # 
# Jaccard similarity is a possible candidate, although more network-based measures (such as modularity) might also work. 
# # 
# To investigate the longitudinal changes, it seems possible to first cluster each point in time (presumably a period of some months), and then merge the genres across time points on some threshold of some similarity score

# **** identity :ignhead:
# 
# The fuzziness (or clarity) of a genres 'identity' can be assessed with 'tags' which users can employ to label artists, albums and songs. 

# Once genres are constructed from a similarity measure, it should be possible to construct the cognitive identity from the tags associated with each of the genre's artists, and subsequently measure of how clear of an identity a genre has at each point in time. 

**** final analysis :ignhead:
# Finally, a genre can be considered abandoned at the end of 'time point genres'. 
# # 
# For the 'merged' genres it should be possible to calculate all relevant genre-level variables for each time point, individual level ones can be constructed from the audience of each, and would be aggregated [fn::It came to my mind to use a multilevel structure in which users would be nested in genres, however this would require a more complicated model as the primary interest would be a second-level variable, and it would also require that listeners only belonged to one genre]. 
# # 
# In the final analysis, either the size or the status might be predicted in a fixed or random effects model, in which the time points would be nested in genres. 

** Current Issues 
# *** tag issues :ignhead:
# No temporal data on tags is available, i.e. the tags and their weights reflect the cumulative history which cannot be disentangled for a particular period of time the implications of which have to be considered in the calculation of the fuzziness of the genres cognitive elements. 
# #
# If artists are (seen as) changing their styles over time, this would problems, but not if generally artists rise and fall with genres, and genres with artists. 
# 
# Furthermore this problem might be alleviated to some degree by focus on albums or even songs as these are much more associated with the point of time of their release (although this does not for canonical works which remain popular parencite:Anand_2000_sensemaking). 
# # 

# Furthermore, a finer levels means that the tags themselves are sparser. [fn:: it is not clear to me how last.fm generates the tag weights for the artists, nor did I find out so far whether tags given to songs by users automatically extend to the album and the artist] 
# # 
# Additionally, even single albums or songs might be interpreted differently throughout time, albeit I think that this does not occur to an extent that it would have a substantial impact. 

*** sampling
Sampling might be a problem: 
# 
The population (predominantly young and male) might (next to generally being unrepresentative) not adhere to genre boundaries to an extent that results in clear boundaries given the currently planned analytic strategy. 
# 
Similarity measures might therefore be unreliable when users listen to a large number of artists that they do not consider similar. 
# 
On the other hand, one might still expect patterns in the aggregate. 
# 
Playlists might be a useful as in these listeners group objects together on perceived similarity, and therefore would be a good application of practical classification systems parencite:van_Venrooij_2018_fuzziness. 
# 
However playlist data is not available from last.fm, and I have not been able to get access to the so-called Million Playlist Dataset (MPD) by Spotify. 

*** technicalities
# 
A number of technical issues also require further work, such as tag cleaning to deal with duplicate tags (such as "punk rock" and "punkrock", efficient ways to store and analyze the data as well as finding ways to map of items into a lower dimensional space that takes features such as asymmetry into account. 

# ask the DGS people? 


#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}


** additions :noexport:
shift to genres as tags
partiality

probability densities



asymmetry: china/NK, Mohr, Kovacs

# cross-form legitiation

spatial metaphors

# niches 
link of cultural and cognitive space -> Mohr

improve speculation on trajectories

concentration/distribution matters somehow


much reliance on conventional industrial categories -> also for music

categories from the ground up? 

categories provided by users: Zucc, Hsu



*** structure
- genres: focus on cognitive aspect
# how to save dimaggio? 
- concept relations: general/special -> asymmetry


# send alex the git diff? 
Bourdieu: space already contains the forms






*** whining
causal path: from cognition to action 
but does that work with ecology? 
yeahhh: it seems more like how do objective conditions lead to culture :(
ehh not quite either: cross-form legitimation is culture -> culture link

Tfp is cognitive too
fuzziness tool
maybe see it a bit more unified: competition is also cultural, is over legitimacy as much as about users? 




* export :noexport:
#+BEGIN_SRC emacs-lisp
  (org-babel-tangle)
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                      'comment 'identity))
      do
      (setf (buffer-substring (org-element-property :begin comment)
                  (org-element-property :end comment))
            "")))

  (let ((org-export-before-processing-hook '(delete-org-comments)))
    (switch-to-buffer (org-latex-export-to-pdf)))
#+END_SRC

#+RESULTS:
: #<buffer /home/johannes/Dropbox/gsss/thesis/proposal/proposal.pdf>

