#+latex_class: article_usual2
# erases make title
#+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
# #+OPTIONS: toc:nil#+TITLE: #+AUTHOR: #+DATE: 
#+OPTIONS: h:5





* Proposal: fluctuations of genre popularity
** intro

** theoretical framework
*** notes
-> RQ

category emergence/abandonment
-> institutionalization


boundaries: tags -> shows what people think
-> listening and tags should align 
# but no temporal stuff on tags fUUUUUU
I NEED MEANING



attention

typicality

Further elements that I think are beyond the scope of the thesis are considering the aesthetic elements themselves such as lyrics or musical features such as bpm, as genres are primarily seen as a set of objects which has similar relations to audiences parencite:dimaggio1987classification. 
# 
While especially latter ones seem to be used in recommendation systems, and while inclusion of this would certainly be an enrichment parencite:van_der_Laan_2016, I assume that an approach that focuses on the relations between objects and audiences is preferable given the time constraints parencite:Emirbayer_1997. 


**** What is a genre
Rather than defining genres in terms of form or content, I plan to focus on the "social relations among producers and consumers", assuming that genres are "partially constituted by the audiences that support them" [[parencite:dimaggio1987classification][p.441]]. 
# 
While textcite:dimaggio1987classification based on these considerations conceptualizes genres as "sets of works classified together on the basis of perceived similarities" (p.441), it seems to me that not only explicit classifications of objects are indicative of genres, but that of implicit usage data (in this case,  listening records) should also enable the linking of particular objects to particular audiences. 
# 
This does not mean that perceptions of similarity or other cognitive processes are not worthy of considering, as on the contrary, the development of cognitive associations and routines that become taken for granted is a key part of the establishment and institutionalization of new organizational forms. 
# 



*** text 
# From a neo-institutional perspective, oranizational forms have to adhere to rules/standars of legitimacy to be successful parencite:diMaggio_1983_iron,Zuckerman_1999_illegitimacy, often resulting in homogenization. 
# #
# Such emphasis on reliance on pre-existing standards has problems to explain the emergence of new forms. 
# #
# However, concepts from organizational ecology such as cross-form legitimation, density dependence and saturation have been shown to explain form emergence parencite:Ruef_2000_emergence
# #
# Additionally, the emphasis on individual-level cognitive processes of quality inference from popularity parencite:Strang_2001_excellence as well as variation in individual preferences and 'dilution' effects parencite:Kovacs_2014_paradox have been proposed to explain the dynamics of organizational forms. 
#
~lieberson~


declarative and non-declarative

is non-declarative (listening habit) even useful for changing times (genre emergence)? 
#
declarative: tags? 

2007 tags are there




** Issues: 
The population (predominantly young and male) might not adhere to genre boundaries to an extent that results in clear boundaries. 
# 
Similarity measures might therefore be unreliable when users listen to a large number of artists that they do not consider similar. 
# 
On the other hand, one might still expect patterns in the aggregate. 
# 
Playlists might be a useful as in these listeners group objects together on perceived similarity, and therefore would be a good application of practical classification systems parencite:van_Venrooij_2018_fuzziness. 
# 
However playlist data is not available from last.fm, and I have not been able to get access to the so-called Million Playlist Dataset (MPD) by Spotify. 
# ask the DGS people? 


The sample might be generally be unrepresentative. 

 


** Identity
Artists can be tagged by users. 
# 
While there is no breakdown by who tagged which artist, tags are weighted on a scale from 1 to 100 (the most frequent tag always is always 100). 
# 
Once genres are constructed from a similarity measure, it should be possible to construct the tags associated with each, and therefore get a measure of how clear of an identity a genre has at each point in time. 
# 
I assume that a clear identify enhances survival prospect cite:Zuckerman_1999_illegitimacy,Hsu_2006_jacks. 
# 
A clear identity can be also seen as successful institutionalization, as it corresponds to the construction of a cognitive layer which solidifies the common aesthetic elements of a set of works to the degree that they become taken for granted parencite:Powell_1991_introduction. 
# 
This process similarly corresponds to the prototype view parencite:Murphy_2004_concepts, in which a general concept that that either lists the features of a category or additionally, posits relations between the is constructed from a set of items in a process of abstraction. 
# 
A clear identity might stand in contrast to popularity, as it might be easier to maintain a clear identity. 
#
Reversely, it might be that larger genres develop more 'momentum' and through institutionalization reach more clarity, yet it could also be that a clear identity is a precondition for growth in the first place. 
# 

*** Resource distribution
# 
Another relevant genre-level variable might be the resource distribution; one can imagine an ideal-typical contrast between concentration where few artists account for the majority of listeners with a relatively evenly spread distribution. 
# 
While this might impact survival chances, albeit I cannot think of a clear direction so far. 



** micro-processes

It is furthermore relevant to consider the individual-level processes through which macro-level mechanisms are mediatated. 
# 
textcite:Kovacs_2014_paradox postulates that two mechanisms that lead to short-term devaluation might have long-term consequences. 
# 
First, he finds that status attracts audiences not who are not intrinsically attracted and hence devalue the object due to lack of fit with their personal evaluation criteria. 
# 
Second, he finds that increasing popularity results in more devaluation by audiences who dislike popular products and want to distinguish themselves from 'mainstream' objects. 
# 
Both these measures should be relatively straightforward. 
# 
While it is presumably most convenient to aggregate them to the level of genre, I do not think that this diminishes their explanatory power. 
#
However, I wonder if maybe textcite:Kovacs_2014_paradox, particularly in the second mechanism, 'imposes' a high cultural capital mindset (distinction) as general mechanism (something that e.g. textcite:holt1998does warns against). 
#
It further seems to me that the assumptions of the first mechanism, namely an intrinsically interested audience, to some degree limit the effect of the second, as these are presumably not easily swayed by short-term shifts in public opinion. 
# 
Obviously, only empirical analysis can settle these matters. 

*** other individual-level variables :ignhead:
The impacts of other personal-level variables are also worth investigating, such as ~omnivorousness~ parencite:peterson1996changing (or more precise, atypicality and variety parencite:Goldberg_2016_span).
# 
Omnivores might be less committed to a particular genre as their ~identity~ is to span different genres, yet their openness parencite:Roose_2012 might nevertheless make them willing propagators of new forms. 
# 


*** environment :ignhead:
# 
Next to the internal composition of a genre, the relationship to its environment needs to be taken into account. 
# 
Primarily insights from organizational ecology can be incorporated here parencite:Hannan_1977_ecology,Ruef_2000_emergence,Ruef_2004_demise,van_Venrooij_2015_ecology such as density of the musical spaces, competition over resources (listeners), saturation of different niches and reaping the benefits of form legitimation performed by other actors. 
# 
Compelling concepts might also be gained by incorporating field-theoretical approaches, such as the primary focus on actors (or more precisely, incumbents and challengers) which in "the aggregate constitute a recognized area of institutional life" [[parencite:diMaggio_1983_iron][p.148]]. 
# 
Considerations of how their perceptions, evaluations, strategies, decision making, and alliances parencite:Fligstein_2015_fields,Anand_2006_charting would contribute to field emergence, settlement and rupture would certainly provide valuable insights. 
# 
However, the complexities involved in taking into account the large number of actors which next to other artists would also increase for example record labels, radio stations and other distributors as well as the relations between them presumably is beyond the scope of this study. 
# 
As this focus on the relations among artists and to consumers leaves out a number of key actors, caution has to be exercised to avoid misattributing effects, in particular as the textcite:Fligstein_2015_fields consider the relations to outside actors as key predictors of field stability or change (nevertheless, this might be less of an issue as musical production faces relatively little state regulation). 
# 


*** TfP :ignhead:
Taste for popularity parencite:Zuckerman_2012_valuations,Lieberson_2003_popularity might furthermore matter insofar as it could not only be the mere number of a listening audience that is considered, but also its composition. 
#
In particular, one might imagine that an actor with medium TfP would be more enticed by a genre that is consumed by a small number of avant garde than one that is just being abandoned by the last audiences with a high TfP. 
# 
as the former provides much more potential for distinction than the former which has already been chewed through by large parts of the population.  

# Tfp: not just how many like it, but who: s it liked by people with lower TfP? then good



*** tag issues :ignhead:
However, no temporal data on tags is available, i.e. the tags and their weights  would reflect the cumulative history which would pose problems if artists are changing their styles over time. 
# 
This might be alleviated to some degree by focus on albums or even songs as these are much more associated with the point of time of their release (although this does not for canonical works which remain popular cite:Anand_2000_sensemaking). 
# 
Furthermore, a finer levels means that the tags themselves are sparser. 
# 
Additionally, even single albums or songs might be interpreted differently throughout time, albeit I think that this does not occur to an extent that it would have a substantial impact. 
#


** reflect on meetings: websites
# topic is changes in popularity of genres
# why is listener network data approach better? 
# no imposition of genres
# non-declarative (actual useage, not conscious)
# much more complete: not just what people chose to review
 

It strikes me as somewhat ironic that a cognitive criticism of surveys is their exclusive focus on declarative culture which may be only tangentially related to action, yet the reverse is the case here as behavioral is readily available but little insights are available of the cognitive that underlie the actions (yet since the cognitive critique also stresses the loose coupling between declarative and non-declarative culture, it is not clear if attitudinal data would provide additional insights, and hence might only serve as a confirmation of the loose coupling). 
# 





** Issues 




** Data and methods
*** notes

*** text
This thesis will study the fashion dynamics of genres (organizational forms) of popular music. 
#
Longitudinal data 


tags: crawl through the rateyourmusic archive.org sites to get tags? but don't know where they're coming from either

# cluster all time periods, group similar ones together (across time?)
# might merge multiple from years
# then so be it? 
# assumes genre can't change completelyl
# maybe just similarity within window? like marieke: only current/previous year...

** 
tags: identity/perception: does group have a stable identity/is it perceived to be different 
textcite:dimaggio1987classification: *socially constructed organizing principles*
is clear abstraction formed? 


questions: start with tags, or with networks/connections

* technical
big data: pre-processing in python? 
graphtool? 


google analytics for the frequencies

#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}




* export :noexport:
#+BEGIN_SRC emacs-lisp
  (org-babel-tangle)
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                      'comment 'identity))
      do
      (setf (buffer-substring (org-element-property :begin comment)
                  (org-element-property :end comment))
            "")))

  (let ((org-export-before-processing-hook '(delete-org-comments)))
    (switch-to-buffer (org-latex-export-to-pdf)))
#+END_SRC

#+RESULTS:
: #<buffer /home/johannes/Dropbox/gsss/thesis/proposal/proposal.pdf>

