* theory/IRC final: noexport:

** notes alex
DV: survival or abandonment of cognitive labels used by audiences. 

Mechanisms: 
- Conceptual informativeness or distinctiveness. -> using the musicological features of songs.  
- Distinctiveness: Piazzai approach. MDS of features. Songs. Spherical space. 
- Informativeness: hierarchical concept. nature of the relations among concepts. 
- Audience niche size. 
- Audience composition: avant-garde or mainstream. 
- Status: average Billboard. Label could be more widely applied in aesthetic and social space. Expansion of use of genre labels due to increased popularity.
- Density measures. 
- Legitimation= same as status. 
- Rapid adoption could lead to abandonment. 

Methodological:
- assymmetry: 
- identification of genre-labels
- nature of the relations among concepts. 
- how tightly connceted the audiences are? two-mode not well connected individual listeners. 
- length of the time period. 
- Billboard. 


** own notes
unit of analysis is concept -> start with concepts

ecological 

add stuff about partiality 
- mean
  - high: salient
  - low: peripheral
- skew:
  - high: concentration
  - low: equality

can there be low mean but high skew? 

theoretical implications: 

*** fuzziness
concept (fruit) is fuzzy if there are objects (olive) of which it is not clear whether it belongs or not

classical category: just 100s (rest 0s)
somewhat fuzzy: many 100s, some non 100s

very fuzzy: many non 100s

the lower the average weight, the fuzzier the category? 

electronic: will be more fuzzy than syncwave-electrofunk
but that's accurate isn't it? 
people who use a very specific label know it well, have clearer criteria -> can make membership more binary

*** informativeness
needs hierarchy!!!

average informativeness?

need way to formalize informativeness from asymmetric competition coefs

hierarchy is a way to deal with asymmetry

make the use more the improvisations (Bourdieu) -> stresses flexibility

*** other areas of concepts: 
- psychology
- neurophysiology
- information science

* text
** introduction
#

** concepts
# 
With genres as the unit of analysis, ~it is necessary~ to expand on general features of these mental blueprints.
#

*** fuzziness/partial membership
textcite:Hannan_2019_concepts provide a summary of the recent concept literature and highlight a number of key properties. 
#
~Categories~

Concepts are fuzzy: 

Given
- logocentrism (Derrida)
- bureaucratization/iron cage 
  - narrow down to institutional logic? 

It may seem intuitive to think that concepts can clearly described with a precise definition of features. 

textcite:Murphy_2004_concepts argues that the "classical view" in the psychology of concepts constituted such a praradigm  until the 1970s considered concepts as definitions with necessary and jointly sufficient attributes. 
# 
While there have always been philosophical criticisms of the non-universality of rationality 
- Wittgenstein
- Habermas
a paradigm shift took place in psychology only with 
- ~experiments~.


textcite:Murphy_2004_concepts,Hannan_2019_concepts argue that concepts are fuzzy and entail blurred boundaries. 
# 
Consequentely no clear defining list of necessary and/or sufficient features can exist for a concept. 
# 
For example, while there are features which we strongly associate with the concept of a ~dog~  such as fur, barking, or four legs, we can well imagine animals that do not fulfill all of these attributes but that we would nevertheless call dogs. 
# ~Wittgenstein game example?~
# 
Such lack of logical clarity and hence debate over terminologies regarding membership criteria are present in virtually every context, including highly technical ones such as astronomy (whether Pluto is a planet) or mathematics (classification of polyhedras, cite:Lakatos_2015_proofs)


~need to account for partial membership because data (tag weights)~
use fruits; tomato as illustrations



# 
The abandonment of crisp boundaries does not entail the adoption of (caricature of) an arbitrary 'postmodern' 'anything-goes' approach. 
# 
Instead, cite:Hannan_2019_concepts invoke the notion of "probability densities" to capture the variation of the probability of an objects to belong to concept based on their position in a feature space. 
# 
The relations between concepts can hence be inferred by the relations of their respective probability densities. 
#
Concepts that occupy similar regions of the feature space (such as ~sociologist~ and ~anthropologist~) are ~closer together~ than concepts that reside in different regions (such as ~sociologist~ and ~lumberjack~). 
# this is relevant how? 





*** hierarchy
A key issue concerns the hierarchy of concepts. 
#
As concepts vary in their degree of abstraction (e.g vehicle -> car -> pickup truck), different approaches exist to account for these different levels. 
#
The ~classical view (is it really the classical view?)~ sees concepts stored in an hierarchical network, where at each level only the relevant features are stored. 
#
For example in the case of vehicles, the property of being a mechanical device to transport things is seen as associated with the most general ~vehicle~ level, the feature of having wheels and driving on roads to the intermediate and the feature of having an open cargo area associated with the most specific level. 
#
Within such a (crisp) hierarchy, features are inherited from higher levels. 
# 
Membership ~in the sub-concepts~ is furthermore transitive: all pick up trucks are cars as well as vehicles. 
# 




cite:Hannan_2019_concepts to a large extent follow cite:Collins_1969_retrieval,Quillian_1988_memory in conceptualizing concepts as stored explicitly in a hierarchical network. 
#
They conceptualize the resulting conceptual space as a semi-lattice, a nested tree built from sub-concept relations. 
# 
In this directed tree, conceptual /roots/ (e.g. vehicles) spawn /cohorts/ of concepts (e.g. car, ship, plane); groups of concepts at the same level of abstraction. 
#
They nevertheless diverge from the classical to some extent. 
# 
First, they consider feature inheritance as probabilistic, as more typical subconcepts inherit more features ~and feature dimensions~ from their roots than atypical ones. 
#
Second, they explicitly allow inheritance from multiple parents, which takes into accounts 'hybrids' such as romantic comedy or ~flying cars~. 



However, it seems to me that despite these additions the assumption of explicitly stored hierarchical links is not consistent with theoretical considerations and empirical evidence. 
#
Instead, I find more convincing the argument of textcite:Murphy_2004_concepts that hierarchical links are not explicitly stored, but computed based on similarity values. 
#
One reason is transitivity of membership. 
#
Murphy (refering to ~source~) argues that when subjects agree that chairs are a type of furniture, and car seats are a type of chairs, they nevertheless do not consider car seats a type of furniture. 
#
He argues that the features that car seat shares with chair are different from those that chair shares with furniture, which leads to refusal of membership even if it would follow on logical grounds. 
#
A further argument against explicitly stored hierarchical links are response times. 
#
If features are only stored at one level, inferences would take the longer the more hierarchical links they have to travel through. 
# 
While this holds in some cases ~page~, it can also be violated: 
# 
cite:Murphy_2004_concepts, ~other source~ find that verifying the statement 'a dog is an animal' is faster than the verifying the statement 'a dog is a mammal'. 
# 
If hierarchical links were explicitly stored, the latter statement would be faster as the mammal concept would be closer to the dog concept than the animal concept of which it is a subconcept of. 
# 
Murphy explains this with dogs being more typical animals than mammals. 
# wouldn't it need to be: dogs are more typical of animals than they are of mammals? 

inclusion fallacy? 
# robin have X -> all birds have X more believable than ostrichs have X -> all birds have X
# can't see how that supports computed
# is typicality effect, but typicality can be considered in hierarchy
# maybe murphy didn't consider Hannan's view yet (argues against "logical reasoning")


cite:Hannan_2019_concepts are aware of the latter argument, and in response argue that features duplicated at lower levels. 
# 
I however do not find this satisfactory: 
# 
It breaks with the parsimony

# therefore argues against a hierarchical taxonomy 

are features inherited or root concepts? 
if i want to know whether pick up is a vehicle: 
do i need to get both pick up and vehicle and see how well features of pick up fit into vehicle? 
or can I just have a look at pick up which has also inherited the root concept of being a vehicle?




cite:Murphy_2004_concepts however rejects Q.'s approach and argues that hierarchies are imputed based on typicality values: 
- faster that dog is animal than dog is mammal: dog is more typical animal than mammal
- furniture; chair: car seat, : transitivity violation: features that car seat shares with chair are different from those that chair shares with furniture





# feature spaces need to be linked: 
# need to be able to ask: what is the difference between an economist and a sociologist
# can't be that each has its own separate feature space
Hannan: differences between concepts really explicitly specified
more elegant: differences between concepts in terms of features -> two mode network? 




To describe the relation of concepts to other concepts, the authors employ the notion of a conceptual space. 
#
They argue that concepts are hierarchically structured based on their level of abstraction , 
just not mention informativeness in main part, just in discussion
do i even need conceptual space then? 







# difference between concept and feature space? 
# - feature space: UoA: objects, dimensions: features
# - conceptual space: UoA: concepts, no dimensions, but distances/is-a relations to other concepts


The variation in the probabilities of category membership are described with typicality (or its reverse, atypicality). 
#
While robins are highly typical members of the bird category, penguins are atypical birds as they lack a feature that we see as important of birds, namely the ability to fly. 
# but are still birds -> binary membership? 
# 
While penguins are considered birds (and hence display discrete membership status in the institutionalized taxonoy), atypicality effects are nonetheless present and influence e.g. the speed ~and accuracy?~ of logical inferences. 





# relationship between: 
# - concepts
# - objects
# - features

# objects fit into concepts/categories with varying fit due to varying fit of their features to the concept prototypes




* questions
can i test prototype vs exemplar model? 
do they imply different mechanisms for survival? 


Piazzai doesn't even use word
- exemplar/prototype view
- *atypicality*
  Hannan: equivalent to informativeness
  is about relation between object and concept
  idc much about that relation
  
fix refs
- Hannan 2019: add authors

fix ref style

reflection (Lizardo)
if i make for each genre a "spread-score": how big the tension between genres is (low for heavy metal and black metal, higher for black metal and opera) -> can average that to the genre level



zG&}/Pv8w@^BPRiq"w9[

zG&}/Pv8w@^BPRiq"w9[

~is quillian part of the classical model?~
