* theory/IRC final: noexport:

** notes alex
DV: survival or abandonment of cognitive labels used by audiences. 

Mechanisms: 
- Conceptual informativeness or distinctiveness. -> using the musicological features of songs.  
- Distinctiveness: Piazzai approach. MDS of features. Songs. Spherical space. 
- Informativeness: hierarchical concept. nature of the relations among concepts. 
- Audience niche size. 
- Audience composition: avant-garde or mainstream. 
- Status: average Billboard. Label could be more widely applied in aesthetic and social space. Expansion of use of genre labels due to increased popularity.
- Density measures. 
- Legitimation= same as status. 
- Rapid adoption could lead to abandonment. 

Methodological:
- assymmetry: 
- identification of genre-labels
- nature of the relations among concepts. 
- how tightly connceted the audiences are? two-mode not well connected individual listeners. 
- length of the time period. 
- Billboard. 


** own notes
unit of analysis is concept -> start with concepts

ecological 

add stuff about partiality 
- mean
  - high: salient
  - low: peripheral
- skew:
  - high: concentration
  - low: equality

can there be low mean but high skew? 

theoretical implications: 

*** fuzziness
concept (fruit) is fuzzy if there are objects (olive) of which it is not clear whether it belongs or not

classical category: just 100s (rest 0s)
somewhat fuzzy: many 100s, some non 100s

very fuzzy: many non 100s

the lower the average weight, the fuzzier the category? 

electronic: will be more fuzzy than syncwave-electrofunk
but that's accurate isn't it? 
people who use a very specific label know it well, have clearer criteria -> can make membership more binary

*** informativeness
needs hierarchy!!!

average informativeness?

need way to formalize informativeness from asymmetric competition coefs



* text
** introduction
#

** concepts
# 
With genres as the unit of analysis, ~it is necessary~ to expand on general features of these mental blueprints.
#
textcite:Hannan_2019_concepts provide a summary of the recent concept literature and highlight a number of key properties. 
#
~Categories~

Concepts are fuzzy: 

Given
- logocentrism (Derrida)
- bureaucratization/iron cage 
  - narrow down to institutional logic? 


It may seem intuitive to think that concepts can clearly described with a precise definition of features. 

textcite:Murphy_2004_concepts argues that the "classical view" in the psychology of concepts constituted such a praradigm  until the 1970s considered concepts as definitions with necessary and jointly sufficient attributes. 
# 
While there have always been philosophical criticisms of the non-universality of rationality 
- Wittgenstein
- Habermas
a paradigm shift took place in psychology only with 
- ~experiments~.


textcite:Murphy_2004_concepts,Hannan_2019_concepts argue that concepts are fuzzy and entail blurred boundaries. 
# 
Consequentely no clear defining list of necessary and/or sufficient features can exist for a concept. 
# 
For example, while there are features which we strongly associate with the concept of a ~dog~  such as fur, barking, or four legs, we can well imagine animals that do not fulfill all of these attributes but that we would nevertheless call dogs. 
# ~Wittgenstein game example?~
# 
Such lack of logical clarity and hence debate over terminologies regarding membership criteria are present in virtually every context, including highly technical ones such as astronomy (whether Pluto is a planet) or mathematics (classification of polyhedras, cite:Lakatos_2015_proofs)


~need to account for partial membership because data (tag weights)~
use fruits; tomato as illustrations



# 
The abandonment of crisp boundaries does not entail the adoption of (caricature of) an arbitrary 'postmodern' 'anything-goes' approach. 
# 
Instead, cite:Hannan_2019_concepts invoke the notion of "probability densities" to capture the variation of the probability of an objects to belong to concept based on their position in a feature space. 
# 
The relations between concepts can hence be inferred by the relations of their respective probability densities. 
#
Concepts that occupy similar regions of the feature space (such as ~sociologist~ and ~anthropologist~) are ~closer together~ than concepts that reside in different regions (such as ~sociologist~ and ~lumberjack~). 
# this is relevant how? 





*** hierarchy
A key issue concerns the hierarchy of concepts. 
#
As concepts vary in their degree of abstraction (e.g vehicle -> car -> pickup truck), different approaches exist to account for these different levels. 
#
The ~classical view (is it really the classical view?)~ sees concepts stored in an hierarchical network, where at each level only the relevant features are stored. 
#
For example in the case of vehicles, the property of being a mechanical device to transport things is seen as associated with the most general ~vehicle~ level, the feature of having wheels and driving on roads to the intermediate and the feature of having an open cargo area associated with the most specific level. 
#
Within such a (crisp) hierarchy, features are inherited from higher levels. 
# 
Membership ~in the sub-concepts~ is furthermore transitive: all pick up trucks are cars as well as vehicles. 


# feature spaces need to be linked: 
# need to be able to ask: what is the difference between an economist and a sociologist
# can't be that each has its own separate feature space
Hannan: differences between concepts really explicitly specified
more elegant: differences between concepts in terms of features -> two mode network? 




zG&}/Pv8w@^BPRiq"w9[

zG&}/Pv8w@^BPRiq"w9[







cite:Hannan_2019_concepts follow cite:Collins_1969_retrieval,Quillian_1988_memory in conceptualizing concepts stored explicitly in a hierarchical network. 
#
They differ however by allowing 'multiple parents

This so-called semi-lattice builds on 

~is quillian part of the classical model?~

 ~explicitly~ stored


To describe the relation of concepts to other concepts, the authors employ the notion of a conceptual space. 
#
They argue that concepts are hierarchically structured based on their level of abstraction , 
just not mention informativeness in main part, just in discussion
do i even need conceptual space then? 



cite:Murphy_2004_concepts however rejects Q.'s approach and argues that hierarchies are imputed based on typicality values: 
- faster that dog is animal than dog is mammal: dog is more typical animal than mammal
- furniture; chair: car seat, : transitivity violation: features that car seat shares with chair are different from those that chair shares with furniture



# difference between concept and feature space? 
# - feature space: UoA: objects, dimensions: features
# - conceptual space: UoA: concepts, no dimensions, but distances/is-a relations to other concepts


The variation in the probabilities of category membership are described with typicality (or its reverse, atypicality). 
#
While robins are highly typical members of the bird category, penguins are atypical birds as they lack a feature that we see as important of birds, namely the ability to fly. 
# but are still birds -> binary membership? 
# 
While penguins are considered birds (and hence display discrete membership status in the institutionalized taxonoy), atypicality effects are nonetheless present and influence e.g. the speed ~and accuracy?~ of logical inferences. 





# relationship between: 
# - concepts
# - objects
# - features

# objects fit into concepts/categories with varying fit due to varying fit of their features to the concept prototypes




* questions
can i test prototype vs exemplar model? 
do they imply different mechanisms for survival? 


Piazzai doesn't even use word
- exemplar/prototype view
- *atypicality*
  Hannan: equivalent to informativeness
  is about relation between object and concept
  idc much about that relation
  


fix refs
- Hannan 2019: add authors

fix ref style
