#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
# #+OPTIONS: num:nil
#+OPTIONS: toc:nil
# #+OPTIONS: toc:nil#+TITLE: #+AUTHOR: #+DATE: 
# #+OPTIONS: h:5




# -*- org-export-babel-evaluate: nil -*-

* header :ignhead:
#+latex: \input{./title_page}

# #+TOC: headlines 3
#+latex: \tableofcontents

* Introduction
** basic intro:ignhead:

Classification systems are essential for social life parencite:Durkheim_2019_primitive. 
# 
Without conceptual systems to aid in sense-making and generalization of experience, the complexity of perception would certainly be overwhelming. 
# 
Interpretive frameworks that structure perception and allow cognitive processing to make sense of the world parencite:Hsu_2006_jacks,Zuckerman_1999_illegitimacy. 
# 
While the impact of categorical systems to structure action can hardly be overestimated, it is equally important to take a step back from the and investigate the processes that these very classification systems are shaped by.
# 
While often taken-for-granted, classification systems are not immune to change. 


** specific focus :ignhead:

In this study, I focus on a particular process of change, namely abandonment of concepts of practical classification frameworks, which are characterized by little explicit formalization and emerge from multiple actors parencite:Pontikes_2012_coin,van_Venrooij_2018_fuzziness. 
# 
Using the case of last.fm, a digital music service website, I investigate which forces shape the disappearance of user-defined musical genres. 
#
Guided by the idea that a key property of concepts is to structure our understanding of the world, I focus on predictors that measure the informative content of a genre, both vis-a-vis its more general superordinates ("metal" is a superordinate of "death metal") as well as its cohort members on the same level of specificity ("black metal" and "death metal" are cohort members). 
#
Using an ecological approach parencite:Ruef_2009_credit, I further investigate how density (the saturation of a genre's environment) influences survival chances. 
#
Contrary to my expectations, I find no substantial effects of my key variables, which I argue is likely due to difficulties of operationalization. 
#

** para 3 :ignhead:
# 
The rest of the study is structured as follows: 
#
First, I outline the main theoretical developments in the literature on concept structure, which are furthermore evaluated in terms of ecological mechanisms. 
# 
I then describe the case of last.fm, which provides highly detailed account on category membership and individual user listening histories. 
#
I give then a detailed description of how this data was processed to construct a genre-network, whose longitudinal properties I exploit to fit a survival model that measures genre abandonment. 
#
Given the lack of support for my key variables of interest, I discuss possible causes and outline areas for future research. 


* Theoretical framework
** The structure of concepts: What makes something something? 
*** concept v categories paragraph :ignhead:

It first is necessary to clarify terminology. 
# 
The notions of concepts and category are sometimes used interchangeably, however here I use them to refer to distinct ideas. 
# 
A category here is a set of items, be they objects, events, persons or ideas, that are classified together; it is thus an /extensional/ notion. 
# 
A concept on the other hand refers to the mental representation of these objects and is therefore /intensional/ parencite:Hannan_2019_concepts,Piazzai_concepts. 
# 
The notions of concept and category are hence mutually constitutive: 
# 
Without items labeled together, no mental representation of them can be formed, while without a concept, items cannot be grouped together. 
# 
With such terminology established, I argue that concepts are generalizations of their categories items in term of features. 
#
Operations that involve concepts, such as similarity assessments and hierarchical structuring, use these features dynamically rather than following predetermined structures. 
#
The precise meaning of these arguments depend on positioning them in the literature on concepts, to which I now turn. 

# ~is apple an item~
# ~is easier to explain that way~
# ~if i say concept typicality, i need relations between concepts first~
# ~check what terms Rosch uses~


*** classical view :ignhead:
# 
The question of how information is stored and processed to enable complex cognitive functions is not a recent one. 
#
textcite:Smith_1981_categories,Strauss_1997_cognitive and textcite:Murphy_2004_concepts characterize the historical development of the scholarship of concepts by contrasting broad developments. 
#
The main distinction is posited between the so-called /classical view/, taken for granted "since Aristotle" [[parencite:Smith_1981_categories][Preface]] up to the 1970s, against a much more recently emerged /probabilistic view/. 
# 
The classical view is primarily characterized by logic and well-orderedness of the conceptual realm, which is expressed in particular in the idea of /concepts as definitions/ [[parencite:Murphy_2004_concepts][p.15]].  
#
Drawing on formal logic and set theory, it posits that a concept can be clearly defined in terms of its necessary and sufficient features. 
# 
Category membership is hence seen as clear cut: 
# 
Either an item fulfills the specific requirements, in which case it is a member, or it is a clear non-member. 
# 
For example, prime numbers constitute an category where membership can be clearly defined: 
# 
A number is either divisible only by 1 and itself in which case it is a member, or by additional numbers, in which case it is a clear non-member. 
# 

*** probabilistic view :ignhead:
While such a rigid view has appeal as it provides a great amount of clarity (or rather, is assumed to do so [fn::A more situated analysis might evaluate the taken-for-grantedness of the classical view through a theoretical lens of logocentrism parencite:derrida2016grammatology or a bureaucratic institutional logic parencite:thornton_2012_logics]), the high requirements for formal integrity can create problems when trying to find a clear definition. 
# 
textcite:Wittgenstein_1968_investigations has pointed out these problems in his influential discussion of the attempt to define the everyday-concept of "game":

#+begin_quote
"If you look at [board-games, card-games, ball-games, Olympic games, and so on] you will not see something that is common to all, but similarities and relationships [...] Look for example at board-games, with their multifarious relationships. Now pass to card-games; here you find many correspondences with the first group, but many common features drop out, and others appear. When we pass next to ball-games, much that is common is retained, but much is lost. Are they all 'amusing'? Compare chess with noughts and crosses. Or is there always winning and losing, or competition between players? Think of patience. In ball games there is winning and losing; but when a child throws his ball at the wall and catches it again, this feature has disappeared. Look at the parts played by skill and luck; and at the difference between skill in chess and skill in tennis. Think now of games like ring-a-ring-a-roses; here is the element of amusement, but how many other characteristic features have disappeared! And we can go through the many, many other groups of games in the same way; can see how similarities crop up and disappear. And the result of this examination is: we see a complicated network of similarities overlapping and criss-crossing: sometimes overall similarities, sometimes similarities of detail." (p.31)
#+end_quote

*** concept as definition bad :ignhead:
# 
Thus while it might be possible to construct clear-cut membership rules for some categories, the idea that /all/ concepts are clearly defined seems difficult to uphold.
#
It is worth noting that such ambiguity is not only present in every-day concepts, but in highly formalized domains as well, such as the debate of the planethood of Pluto or the categorization of geometric figures parencite:Lakatos_2015_proofs.
# 
Similarly, attempts to clearly define science such as by the demarcation criterion of falsifiability parencite:popper1971conjectural, have been contested by alternative conceptualizations that stress a multitude of non-formal aspects parencite:Kuhn_2012_structure or outright deny the possibility of a clear definition parencite:Feyerabend_1993_method. 
# 
While (particularly in the latter case of science) the idea of concepts as definitions might be argued to still loom in public consciousness, it encounters difficulties to provide definitions in the case of complex concepts to an extent that warrants the consideration of alternatives. 

*** prototypicality :ignhead:

Difficulties to clearly define a concept have also received empirical support from studies that question clear-cut membership. 
#
textcite:Rosch_1975_family argue that category membership is not absolute, but rather partial. 
#
Asking respondents to list fruits, apples and oranges are listed more frequently than pineapples and blueberries, while tomatoes and olives are listed even less. 
#
Such /typicality effects/ show that membership is not a yes-or-no question, but a gradient. 
# 
However, the mere existence of graded memberships does not provide an explanation of its cause. 

# However, graded memberships still leaves open the question of how a concept (for example, fruit) is structured. 
# 


# without concept, items cannot be labelled together



*** feature overlap -> typicality :ignhead:

For this purpose, textcite:Rosch_1975_family consider the /attributes/ that the different concepts (e.g. different fruits) are associated with: 
# 
An apple for example can be described as approximately hand-sized, being of bright color, being edible, being moderately firm and so on. 
# 
In practice, attributes are typically acquired by having participants list features. 
# 
This necessarily includes the possibility that some features are not used for some concepts as "each item has at least one, and probably several, elements in common with one or more other items, but no, or few, elements are common to all items" [[parencite:Rosch_1975_family][p.574]]. 
# 
This idea formally captures the notion of textcite:Wittgenstein_1968_investigations: 
# 
Rather than being characterized by a set of fully shared features to which logical operations (e.g, necessity or sufficiency) can be applied, "natural semantic categories [can be viewed as] networks of overlapping attributes" [[parencite:Rosch_1975_family][p.575]].
# 
Graded membership of items can hence be explained as "the extent to which they [...] have attributes which overlap those of other members of the category" (ibid.). 
# 
The "attributes of other members of the category" can then be abstracted into a generalization which consists of the features that are typical of the category (e.g. fruit): 
# 
The reason then why olives and tomatoes are /atypical/ fruit is that they lack or have only few fruit features (e.g. sweetness, bright-colored, approximately hand-sized), while these features are strongly present in apples and oranges which therefore receive high typicality values. 

# These /feature lists/ can then be used to generate abstractions for each concept by weighing how much each feature was listed for a particular concept. 

*** exemplar vs prototype theory :ignhead:

textcite:Smith_1981_categories and Murphy (citeyear:Murphy_2004_concepts,Murphy_2016_exemplar) refer to these abstractions of feature lists as the /prototype/ theory. 
# 
An alternative theory is the /exemplar/ approach. 
# 
While both rely on the features of items for categorization, the exemplar approach differs in that it does not assume that abstractions are formed but rather posits that many item instances are stored. 
# 
For example, the concept of an orange is then not seen as an abstraction of features, but as the set of objects label as oranges that an individual has encountered so far. 
# 
Exemplar theories can explain the limitations of the classical view (in particularly variation in typicality) however the emphasis on specific instances may underestimate the propensity to generalize [[parencite:Markman_1999_representation][p.247]] or provide only limited explanation of induction parencite:Murphy_2016_exemplar. 
# 
While there are certainly occasions where people rely on specific instances, the current study focuses on everyday concepts in which I consider generalization as proposed by the prototype view to be more adequate. 


*** schema ~currently unclear what level of orange/fruit is~ :ignhead:
# 
So far the prototype theory has been presented as a /feature list/ in which features may differentiated by their importance to the concept. 
# 
However, some features are difficult to represent coherently in an unstructured list. 
# 
For example, the color of a typical fruit can be red or yellow, but hardly both at the same time. 
#
To capture such variation, textcite:Markman_1999_representation has proposed "structured representations" as a specialization of the prototype view; I refer to this view here however as the /schema/ approach as this term seems to have become more established parencite:Murphy_2004_concepts). 
#
In this view, a concept has a number of dimensions (or slots) in which all possible values are weighted by typicality.
# 
This notion of typical values can be captured more precisely through the concept of a /probability distribution function/, which specifies the probability (typicality) for each position on a slot. 
# 
Probability distributions can be defined over nominal, ordinal or continuous slots. 
# 
For example, the "color" slot of the concept of fruit displays the highest values for bright colors such as red or yellow whereas darker colors like green or brown receive lower values. 
# 
The 'size' slot would give highest values to medium, (apple- or orange-sized) fruits, while the extremes (very small, e.g. berries or  very large, e.g. pineapples) would receive lower values. 
#  
A complete schema of a concept can therefore be conceptualized as a collection of probability functions which for each slot describe the typicality of possible values. 
# 
The contribution of the schema view is hence a refinement of the prototype view as the slots are in many aspects equivalent to features. 
# 
Just as it is not necessary that all concepts have the same features, it is not necessary that all have the same slots: 
# 
Typicality ratings of a category member (e.g. apple to fruit) do then depend both on how many slots are "alignable" [[parencite:Markman_1999_representation][p.131]] between the item and the prototype as well how well the probability distributions of these alignable differences coincide.[fn::Schemas also allow the specifications of relations between slots. For example, it is not the entire orange that is edible, but only the pulp, whereas in the case of apples, the peel is edible as well. While such specifications allow to describe concepts in much more detail, they require an account of the structure (in this case, that fruits are  have a peel and pulp). In terms of everyday concepts, in particular the musical genres investigated in this study, an account of the internal structure beyond features (or their probability distributions) has to the best of my knowledge not yet been developed.]



# which - given the probabilistic framework that replaced the classical view - can vary in the degree to which they are associated with the concept.
# 
# For example, the feature of sweetness may be a highly influential one for the concept of fruit, that of size might be moderately important, and the thickness of the peel might only have limited influence. 
# # maybe add schema stuff here
# Exemplar theory however argues sees concepts as collections of objects. 
# # 
# Each encounter with an object is stored, resulting in large list of objects experiences to which new instances are compared. 



** Relations between Concepts
Concepts are not just relevant in terms of their features, but also in terms of their relation to other concepts. 
#
One way in which concepts can be considered to be linked is by their degree of abstraction:
# 
The concepts "fruit", "apple" or "Elstar" can all refer to the same object, however the concepts differ in their degree of specificity. 
# 
The question hence arises how these different levels of abstraction are related to each other.[fn::Questions such the relation between everyday situations and level of specificity or individual-level variation in specificity constitute separate issues which are discussed by [[textcite:Murphy_2004_concepts][p.197]].]
# 

*** Hierarchical Relations: tree structure bad :ignhead:
# add references? 

# "Animals" for example refers to a much more general category than does "mammals", while "dogs" and "cats" are even more specific concepts. 
# #
# What is however less obvious is the relations between these concepts at different levels of abstraction. 
# 
The example of a plant taxonomy shows a well ordered hierarchical structure that represents a tree parencite:Collins_1969_retrieval. 
# 
In such a model, a general concept stem branches out into a few sub-concepts, which in turn are the basis for even more fine-grained twig-like concepts. 
#
At each level, a concept has one (and only one) superordinate concept from which it inherits features.
# 
Category memberships is therefore transitive as all Elstars and Jonagolds are apples as well as fruits, and all apples are fruit. 
#
Furthermore, there is no "cross-branching" between once separated concept links: no apple is also a member of the "vegetable" category. 
# 
A valuable contribution of this perspective is its ability to explain the location of feature values. 
#
In particular, it posits that features are only stored at the level of abstraction for which they are relevant, and "passed down" the branches parencite:Collins_1969_retrieval. 
# 
For example, it argues that we do not need to store the feature "is edible" for every fruit we have a concept of separately, but that the "is edible" feature is stored only once in a general "fruit" class which all specific fruit concepts inherit. 
#
However, this model has the substantial requirement of explicitly stored links between different levels to allow concepts to retrieve features of their superordinates. 
# 
While such hierarchical structure is a computationally efficient way of storing information, its relatively high rigidity raises the question if such a structure would be flexible enough for use in everyday life.[fn::The scholars most associated with the taxonomic feature structure, textcite:Collins_1969_retrieval seem to have been aware of the limited applicability of the strictly hierarchical conceptualization (p.242, also see [[textcite:Quillian_1966_memory][p.6]] and [[textcite:Quillian_1988_memory][p.88]]). However this has not prevented scholars both approving parencite:Hannan_2019_concepts and disapproving parencite:Sloman_1998_tree,Steyvers_2005_structure,Murphy_2004_concepts from characterizing the tree model as a /general/ model of conceptual structure. It seems to me that such characterization might be motivated by different topics of interest, such as explicitly institutionalized classification systems in the former contrasted against flexible categorization in everyday life in the latter. Another view is proposed by [[textcite:Markman_1999_representation][p.93]] who argues that the limited processing power in the 1950s and 1960s constituted a technical constraint which turned the practical issue of efficient information storage into a theoretical consideration.]
# 

*** semi-lattice :ignhead:
textcite:Hannan_2019_concepts propose to abandon the rigid tree structure with a /semi-lattice/ which allows multiple parents and cross-branching. 
#
While the semi-lattice is a plausible structure to account for concept combinations and hybrids (, the nature of the links as pre-stored requires further investigation. 

# caution is advised in the judgment of how far such well-orderedness is generally applicable

*** computational :ignhead:
textcite:Murphy_2004_concepts provides two reasons against explicitly stored hierarchical linkages. 
# 
First, /typicality effects/ are present in hierarchical links as well (p.208). 
# 
Judgments for typical items are generally stronger or faster, whether they concern membership ("a robin is a bird" is evaluated faster as "a penguin is a bird") or feature inference ("birds have an ulnar artery, therefore robins have an ulnar artery" is rated more believable as "birds have an ulnar artery, therefore penguins have an ulnar artery"). 
# 
Membership verification can even violate the tree structure: the statement "a dog is an animal" can be faster validated than the statement "a dog is a mammal", although the hierarchical tree model would posit the opposite as the former statement requires more paths to be traveled. 
# 
Secondly, /transitivity violations/ raise doubts to how strictly membership is passed downwards the branch: 
#
While respondents agree that seats are furniture, and car seats are seats, they deny that car seats are furniture (p.207). 
#
# Third, in some occasions statements that would require multiple paths to be traversed are evaluated /faster/ than statements that require less paths.
# # 
# For example, 

*** overlap :ignhead:
Due to these arguments that question the existence of stored explicit links between different levels of abstraction, textcite:Murphy_2004_concepts argues that instead hierarchical relationships are computed on the spot due to feature overlap (p.207). 
#
In this line of reasoning, concepts are considered similar if they are associated with similar features. 
#
While this approach does away with the cognitive economy of a hierarchical order in which features are stored only once, it provides the flexibility to arbitrarily juxtapose concepts. 
# 
Feature overlap can then explain the phenomena that pose problems for the pre-stored view: 
#
As robins are more typical birds than penguins, inferences between the a typical concept and its superordinate flow easier as it resembles the prototype stronger than an atypical one. 
# 
Additionally, the animal concept is likely to be more familiar than the more abstract "mammal" concepts, the technical features of which provide little overlap to the everyday experiential features associated with the concepts of animals and dogs. 
#
Similarly, while car seats share some features with furniture and some with seats, car seats and furniture do have no substantial feature overlap, resulting in the rejection of membership of the former in the latter. 
# 


*** hierarchy conclusion :ignhead:
# 
There thus are substantial reasons to prefer the computational view of hierarchical structure. 
# 
I therefore combine the theory of textcite:Hannan_2019_concepts to model conceptual hierarchies as a semi-lattice with the proposition of textcite:Murphy_2004_concepts to construct the links dynamically based on overlapping attributes. 
# 
A certain similarity of /feature matching/ can be seen as the basis of both concept typicality and concept structure. 
# 
As this approach rejects predetermined concept meaning (in terms of definitions) and pre-stored hierarchical structure, it highlights the flexibility and improvisation characteristic of everyday life. [fn::This is not to say that this approach is nearly complete, as it in particular lacks relations between features and context effects, as well as an account of the actual process of  feature matching parencite:Medin_1993_respects. Nevertheless, it provides a solid grounding to investigate conceptual structure.]


** Spatial models
*** content :ignhead:
Next to feature based approaches that view "natural semantic categories [as] networks of overlapping attributes" [[parencite:Rosch_1975_family][p.575]], an alternative exists in the form of /spatial models/. 
# 
These approaches argue that the features create a semantic space, in which concepts are located as points parencite:Rips_1973_semantic,Shepard_1962_mds1 or regions parencite:Ashby_1988_unified,Hannan_2019_concepts (sometimes the phrase "space" or "spatial" is used metaphorically; here I focus on theories that explicitly utilize spatial properties to model concept structure). 
#
This assumption may seem negligible, it however results in far-reaching consequences, both theoretical and measurement-wise.
# 
For concepts to be located in a space, they need to have the same properties.
# 
While this seems theoretically hard to justify from the perspective of textcite:Wittgenstein_1968_investigations and textcite:Rosch_1975_family, these are of less influence and do not pose a practical problem if it is not features that are known, but pairwise similarity judgments, measurement of stimuli confusion or measures of word similarity based on co-occurrence with other words which. 
# 
In these cases, multidimensional scaling can be used to find latent dimensions that (nearly) explain the dissimilarities, confusion ratios or similarities by positing a link between spatial distance and similarity judgments. 
# 
textcite:Rothkopf_1957_similarity finds morse code confusion to be structured by length and relative number of short and long tones, and textcite:Rips_1973_semantic find similarity ratings between birds to be based on size and ferocity (for a discussion of scaling of similarities based on co-occurrence, see [[textcite:Murphy_2004_concepts][p.426]]).
# 

*** limitations points :ignhead:
While such scaling approaches can provide insights (although one might speculate that the illustrative power has also contributed to their success), as a general theory of concept structure they entail limitations. 
# 
For one, as scaling solutions generally only result in a low number of interpretable dimensions [[parencite:Markman_1999_representation][p.43]], which generally do not include shared features (for example in the case of birds the fact that birds have wings, beaks and generally fly).
#
Furthermore, textcite:Tversky_1977_similarity has argued that similarity judgments do often violate metric assumptions of spaces such as symmetry and triangle inequality. 
# 
Symmetry posits that the similarity is independent of direction, however North Korea is rated more similar to China than China is to North Korea. 
# 
Triangle inequality demands that the distance between two points cannot be larger that the sum of the distances between each of the two points and a third point, which however does not hold for similarity ratings between Jamaica, Cuba and Russia: 
# 
Both Jamaica and Cuba as well as Cuba and Russia are rated fairly similar, Jamaica and Russia are however rated less similar as would be admissible under the assumption of triangle inequality; positioning them as points in a metric space can therefore not adequately represent similarity ratings (additional more technical limitations of the view of concepts as points in metric spaces is given by best fitting distance metrics parencite:Tversky_1982_similarity,Gati_1982_dimensions and nearest neighbor analysis cite:Tversky_1986_neighbor).
# 

*** limitation probability densities :ignhead:
#
However, when concepts are seen as /regions/ instead of points positioned in a semantic space, the limitations raised by textcite:Tversky_1977_similarity, textcite:Tversky_1982_similarity and textcite:Tversky_1986_neighbor do not apply. 
# 
This idea dates back to at least [[textcite:Smith_1981_categories][p.114]], and has been further developed by textcite:Ashby_1988_unified and textcite:Hannan_2019_concepts. 
# 
In this approach, concepts are defined as a probability density function over the semantic space [[parencite:Hannan_2019_concepts][p.70]], in which regions with high values are more typical. 
# 
On the first sight, this may seem similar to the schema approach, which uses probability distributions to model the typicality of feature values. 
# 
The key distinction is however that the schema approach views the slots as independent and therefore defines a separate probability distribution for each slot, while the probabilistic spatial approach defines a single /multivariate/ probability distribution over the entire space. 
# 
While in the case of the schema model the complexity of a concept grows linearly with the number of slots, in the case of the probabilistic spatial model the complexity grows exponentially as all possible feature combinations have to be considered. 
# 
This "combinatorial explosion" [[parencite:Murphy_2004_concepts][p.46]] does not only "greatly increase the complexity of [probabilistic] metric representations" [[parencite:Smith_1981_categories][p.114]], it also makes the theoretical assumptions that feature /combinations/ are central for concept storage and processing. 
# 
textcite:Murphy_2004_concepts however sees evidence for the use of feature combinations only in rare occasions, such as concepts in which a feature correlation is the only distinguishing property parencite:Malt_1984_correlated or explicit definitions in which feature values are logically combined parencite:Medin_1982_correlated and therefore considers the importance of feature combinations for everyday concepts as limited (p.118).
# 
While there seem to be theoretical concerns with the probabilistic spatial approach, there is no reason reject it completely since, as [[textcite:Markman_1999_representation][preface]] argues, no single approach can explain every cognitive phenomenon. 
# 
Given the novelty its most recent formulation by textcite:Hannan_2019_concepts, instead empirical work is needed to specify the area in which it can be most effectively utilized. [fn::Given that textcite:Ashby_1988_unified have focused on /perceptual/ rather than conceptual similarity, it might be useful in this area.]



** Ecological Dynamics

*** original ecological general :ignhead:
# 
Concepts do not exist in a vacuum, and as all social structures are subject to change. 
# 
Recently, insights from organization ecology parencite:Hannan_1977_ecology,hannan89_organ,Hannan_1992_dynamics,Singh_1991_change have been applied to population of concepts parencite:Ruef_2000_emergence,Ruef_2004_demise,van_Venrooij_2015_ecology. 
# 
This approach allows to study an entire population of concepts rather than for example focus on a few case studies. 
#
It is however worth to first summarize the original research program which focused primarily on long-term industry developments parencite:Hannan_1977_ecology,Hannan_1992_dynamics. 
# 
Here the primary forces that are seen to shape the survival chances of an organization are competition and legitimation. 
# 
textcite:Hannan_1977_ecology have argued that both can be inferred from density, which described the number of organizations at a given point in time. 
# 
Legitimation is hypothesized to be the shaping force in times of low densities: 
# 
As new industries develop, they still lack recognition, and an increase in organizations operating in the sector increases founding rates and enhances survival prospects as it indicates acceptance of the form. 
#
However, when the an industry is established, an increase in the number of organizations now increases competitive pressure, and therefore increases the risk of failure and decreases founding rates. 
# 
While the specific operationalization of legitimation and competition as a function of density has been both critiqued on theoretical grounds parencite:Zucker_1989_legitimacy and lost relevance due to increasing inclusion of actual measurements of legitimation parencite:Zuckerman_1999_illegitimacy,Rao_1994_reputation,Rao_2005_crossing, the overarching theoretical importance of considering competition and legitimation has remained central to studies of organizational populations parencite:Kennedy_2008_counted and classification systems parencite:van_Venrooij_2015_classifications,Piazzai_concepts. 
#


*** focus on selection :ignhead:
Additionally, a central aspect of the ecological paradigm lies in its focus on /selection/ parencite:Hannan_1977_ecology. 
#
In the original framework, organizations (or in this case, concepts) are seen as heavily constrained by their initial configurations. 
# 
While previous literature has investigated concept emergence parencite:Ruef_2000_emergence,van_Venrooij_2015_ecology, less research exists on the causes of selection (but see textcite:Lounsbury_2004_sources for a focus on power, and textcite:Ruef_2004_demise for a focus on a single organizational form). 


*** applicability :ignhead:
# 
How are these considerations of industry structure relevant to a group of concepts? 
# 
One can discern clear similarities when realizing that concepts operate in a similar way as formal organizations in that they can be argued to compete over another limited resource, namely attention parencite:Piazzai_concepts. 
#
With limited cognitive abilities parencite:Martin_2010_ant, concepts that offer advantages for audiences can be expected to fare better in this competition over mental capacities parencite:Zuckerman_2017_revisited. 
# 
The key question therefore becomes what properties of concepts make them more likely to receive audience attention. 
#
In this regard it is distinguish multiple different ways in which concepts differ in terms of their informative content and their relationships to other concepts. 
#

** Hypotheses
When we recall the (semi-)lattice structure outlined above, we can see first that concepts differ in distance to their superordinate, such as robins and penguins in relation to birds. 
#
As "robin" are more typical birds, the concepts encodes less information than "penguins": 
# 
If we have an animal described to us as "like a robin", we have less information about it than if it is described to use as "like a penguin". 
# 
This distance from the superordinate is characterized as /informativeness/ parencite:Piazzai_concepts,Hannan_2019_concepts. 
#
Following the previous literature, I posit a quadratic relationship between informativeness and survival chances: 
#
Concepts that add little to already existing concepts can be expected to fail, but the same can be expected for extremely informative concepts the high learning costs of which is not adequately compensated by their limited utility. 


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Informativeness affects survival chances in a quadratic way as moderately informative concepts are most likely to survive. 


The informative relationships to concepts on the same level (the cohort) needs also be considered.
# 
The degree to which concepts differ from the genres which have the same parents has been coined /distinctiveness/ parencite:Hannan_2019_concepts.
# 
Here I again follow the literature and expect a purely linear relationship: 

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 2*: More distinctive concepts are more likely to survive. 
#+latex: \bigbreak
*** ecology stuff :ignhead:
# 
Next to these relationships of informative content, it is necessary to consider ecological arguments of density dependence. 
#
Here I again expect a quadratic relationship: 
# 
Concepts in unpopulated cohorts can be expected to have their survival chances enhanced by the presence of other concepts, whereas concepts in well-established cohorts are more likely to face competitive pressures. 


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 3*: Density has a quadratic effect on survival chances with enhancing them in low density regions and diminishing them in high density regions. 
#+latex: \bigbreak
While I do not use a formal measure of legitimation, I argue that legitimation can be inferred from parent popularity. 
#
Concepts whose parents are widely established can be expected to be more likely to survive (as parent popularity likely increases the density, the latter has to be controlled for).  

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Legitimation increases the survival chances of a genre in a linear fashion. 


* Data and Methods
** About last.fm
*** general :ignhead:
Last.fm [fn::https://www.last.fm] is a digital music service website, which provides users a number of ways to organize their music listening activities. 
# 
Founded in 2002, it grew to more than 50 million users a decade later, but has been waning since, presumably due to the emergence of other music streaming services. 
# 
While Last.fm initially hosted internet radio streams, it did not provide on-demand selection of specific works that emerging competitors such as Spotify, Deezer and Google Play provided. 
#
Most importantly for this study, last.fm allows users to track the songs they play on various devices by  /scrobbling/ them to last.fm, which over time builds up a unique listening history [fn::last.fm also has social network features which allow to befriend other users and exchange messages. While the spread of music through social networks is worth investigating, social network data is only accessible publicly to a very limited extent, and even less is available of its the longitudinal development.]. 
# 
The website provides a variety of services to analyze one's music consumption patterns such as weekly reports of favorite songs and artists, and gives recommendations for similar music.
#
# Of central importance is also the last.fm API (Application programming interface), which (while by current standards relatively slow) allows access to large amounts of highly detailed information. 

*** labelling :ignhead:

# 
Another way in which users can shape their music consumption on last.fm is through a labeling system:
#
Last.fm allows users to freely label songs, artists and tracks with so-called tags. 
#
It is primarily this lack of limitations that distinguishes the categorizations of last.fm from those of other platforms.
# 
In the case of Spotify and Allmusic, genre, style and mood classifications are provided by the musical industry. 
#
Where users have influence, for example in the case of Discogs, they have to select genres from an explicitly  defined classification system which in turn are also subject to control by other users or moderators to ensure correct classification parencite:Piazzai_concepts. 
# 
last.fm however allows users to tag songs, albums and artists without restrictions. 
#
As one might expect this, this opportunity produces vast amount of tags.
#
While familiar concepts such as rock (along its variants of alternative, classic and indie rock), rap, metal, punk, dance or electronic are the most widely used ones, a much larger number of much more specific tags are present as well: 
# 
"Italian progressive rock", "punk noise hardcore rocknroll" and "neoclassical darkwave" are examples of highly specific combinations of established genres. 
#
However, since there are no restrictions, tags can also reflect sentiments ("most loved", "i want back to the 60s", "sweetncatchy") or other works ("green eggs and ham") or refer to seemingly trivial features ("title is a full sentence", "why on earth is this just a bonus track"). 
# 
As such, the tags of last.fm constitute (or given its decline in current years, constituted) a diverse conceptual ecology. 
#
Given the low extent of formal structuration and absence of explicit guidelines, it seems likely that mechanisms involving the information content of the concepts have substantial impact[fn::It is however worth pointing out that it is not clear who exactly performs the labeling and therefore might be possible that 'behind the scenes' substantial amount of labeling are not performed by users, but by industry actors. While there are certainly more forces in category creation involved than can be accounted in this study, there is no reason to assume that actors involved in other processes do not /also/ process the genres in terms of features, which are focused in this study.].

*** features :ignhead:
#
Given such extensive opportunities for categorizations, nearly all songs have multiple tags (those which are only member of one category are songs with very low playcounts).
#
Last.fm therefore weights tags based on the frequency with which they were assigned: 
#
Tags that are often given to a track, artist or album are given high weights and are displayed (without weights) on the respective site to provide genre information to users. 
#
However, weights for all (not just the most popular ones that are listed on the websites) are available via the API (Application Programming Interface)[fn::https://www.last.fm/api/].
#
Here the most frequent tag is given the weight 100, while less popular ones receive lower weights. 
#
It is not explicitly stated how tags are weighted, but the distribution of tag weights for songs with few tags shows spikes at 20, 25 and 33 and 50, which makes me fairly confident that weights are assigned in a linear fashion: 
#
As the most popular tag receives a weight of 100, all subsequent ones are weighted by how frequently they were assigned compared to the most popular one (this also seems likely as (unpopular) songs can have multiple tags with weights of 100, which would be plausible if these are all given once). 
# more sources
To standardize the degree of membership, I calculate the proportion of each tag weight to the sum of tag weights given to the song (for example, a tag with weight 50 gets a stronger relative weight when only one other genre is present, compared to when multiple other genres with similar weights are present). 
# 
It is therefore possible to estimate the gradient of each membership, which is rare in the case of music classification (for example, genre membership in the more formalized classification systems of Discogs or Allmusic is binary). 
#


** The Music Listening Histories Dataset
*** general :ignhead:
#
Next to information about the tags and their frequencies, the last.fm API also provides access to a users listening history accumulated over his or her time of using the service.
# 
This is a key distinguishing feature from other services that collect such listening histories (such as Spotify or Google Play), for which third parties have to acquire explicit authentication from each user individually. 
#
On last.fm however, users (formally) agree to their listening history being publicly accessible signing up. 
#
textcite:Vigliensoni_2017_mlhd have therefore used the last.fm API to construct a the Music Listening History Dataset (MLHD), which consists of the listening logs of 582,703 users with a total of 27 billion listening events. 
# 
Users were randomly sampled from the last.fm userbase and included in the MHLD if their accumulated playcount equaled or exceeded 7300, corresponding to an average of ten songs every day for a period of two years. 
# 
To maintain degree of cultural consistency I limit my selection to users that have listed the United States as their country of residence, which with around 98,432 users contributes the largest amount of users to the MLHD. 
# 
Due to computational limitations, I select a random subset of 26,231 US users. 

*** bias :ignhead:
While textcite:Vigliensoni_2017_mlhd have sampled the users randomly, such a big data source does not constitute a representative sample in the traditional sense. 
#
First, the very use of last.fm is obviously not evenly spread along socio-demographic lines:
#
Younger (the average age in the sample is 25) and male (men contribute 58%, women 23%, 18% undeclared) demographics are very clearly over-represented.
#
Secondly, the requirement of a playcount of at least 7300 requires that users are avid music consumers, which likely skews the selection to favor consumers whose taste can be described as voracious parencite:Sullivan_2006_voracious. 
# 
Third, there is no information on socio-economic indicators, albeit given that voraciousness is linked to educational qualifications and social status (ibid.) one could likely expect a skew towards upper social strata. 

*** contra-bias :ignhead:
# 
However, such sample bias do not necessarily limit the ability to investigate the development of genres. 
#
As the interest lies in the survival chances of concepts rather than the properties held on a personal level, it has to be considered how the biased sample affects this goal. 
#
From this point of view, the focus on voracious consumers might be a benefit as it highlights those which are heavily invested in music. 
# 
Such avid consumers are likely to have a well-developed sense of their areas of interest enabling them to evaluate the cultural fit of new or existing categories and thereby exerting relatively strong influence on a genre's survival chances.
# 
Additionally, highly active last.fm might actually be the best way to study categories coined or established through last.fm's tagging system. 

*** log processing :ignhead:
#
The dataset consists of a file for each user, with each line constituting a listening event. 
#
Each listening event in turn consists of a time stamp and MusicBrainz IDs (an identification system developed by the MusicBrainz Project[fn::www.musicbrainz.org]) of the song, the album and the artist, to the extent that each was available at the time of dataset construction. 
# 
As my operationalizations of genres as prototypes which describe a probability distribution over feature values, I only use listening events for which an MBID of the song is present[fn::Due to the particular technical setup I use I can currently not precisely estimate how many listening events do not have a song MBID and are therefore dropped. However, I do not think this poses a substantial issue: First, manual inspection of some logs seems to indicate that song MBIDs are generally present, it is rather album MBIDS that seem to be missing. Second, songs lack MBIDs presumably due to their rarity (such as old recordings) and are therefore unlikely to be influential in defining genres.]. 
# 
This results in 1,034,669,879 listening events for the 26,231 users, or 39,445 on average, spread over 4,150,846 unique songs in a highly skewed way. 
#
To obtain genre membership information, I queried the last.fm tag API for the 3.2 million most listened songs  which account for 98.5% of the listening events.
#
Furthermore I used the MusicBrainz API retrieve information on release dates, which is not provided by last.fm. 
#
For 97% songs, both of these queries were successful, which resulted in 3,136,615 songs for which genre membership is available. 
#
In total there are 885,630 tags associated with the 3.1 million songs. 
# 
I first provide a general account of schema creation given a tag, and afterwards elaborate the criteria for tag selection. 

# Last.fm however was no exclusive place for avant-garde audiences, as mainstream artists and established genres are ~strongly present~. 
# # 
# Awarded multiple times for its innovativeness, last.fm stood for a time period in the 2000s for a new way of consuming and interacting with music. 
# # 
# New genres in this period of time are likely to have left a trace in the digital listening logs
# TRUE BUT THEN LOGS DON"T SAY ANYTHING ABOUT THEIR CHANCES

** AcousticBrainz and Schema construction
# unclear if lfm uses acoustic features

*** prototypes more justifiable than exemplars :ignhead:

One might (correctly) argue that it is already possible to generate a model of the semi-lattice structure of genres without reference to their attributes. 
#
It is for example possible to use the song-tag links to generate measures of co-occurence to infer a genre hierarchy:
#
Genre X might be a subset of genre Y if most or all songs of genre X are also members of the much larger genre Y. 
#
However, such a definition is /extensional/ and corresponds more to the exemplar model than an /intensional/ feature-based schema parencite:Murphy_2004_concepts. 
# 
It would therefore be much more cognitively expensive as large numbers of objects would have to be stored, whereas a schema is much more compact and hence cognitively processable due to its level of abstraction  [fn::It is nevertheless worth noting though that such co-occurrence likely constitutes the underlying principle of last.fm's well-received recommendation system as there is no indication that last.fm anywhere uses musicological features.]

*** actual features :ignhead:
 # (and more importantly, the meaning vis-a-vis other genres) 
A thoroughly theoretically-informed cognitive model therefore requires information regarding the features of the items, from which (as category memberships are known) schemes can then be inferred. 
#
For this purpose I use the AcousticBrainz project [fn::https://acousticbrainz.org], a joint effort of the Music Technology Group at Universitat Pompeu Fabra in Barcelona and the MusicBrainz Project aiming to provide detailed musicological information on a large number of tracks. 
#
AcousticBrainz provides information on two levels: 
# 
Low-level data is comprised of more technical characteristics such as measures for loudness, dynamics and spectral shape of a signal, rhythm descriptors and tonal information such as keys and scales, which results in hundreds of variables whose specific meaning is hard to discern. 
#
High-level data however consists of summarizing constructs based on the low-level data obtained through supervised machine learning. 
# 
As evaluating the highly technical aspect of low-level musicological data generation is beyond the scope of this project, I exclusively use the high level-data as I assume that it captures meaningful differentiation in terms of how songs sound. 
#
In particular, I use 12 dimensions of the high-level data which describe each track in terms of danceability, gender (of vocals), timbre, tonality, voice (contrasted against instrumentality), acoustic-ness (vs non-acoustic), aggressiveness, electronic-ness (vs non-electronic), happiness, party-ness, relaxed-ness, and sadness. 
# 
Each dimension ranges from 0 to 1. 
# 

*** Data availability :ignhead:
# 
As the data of AcousticBrainz requires much more active processing than the mere registering done by last.fm and MusicBrainz, it is to be expected that coverage would be substantially worse. 
#
Of the 3.1 million songs for which genre metadata was retrieved from last.fm and MusicBrainz, only 1,318,900 had musicological information included by in AcousticBrainz. 
#
As there is likely some motivation to process more popular tracks, the 1.3 million tracks for which musicological information is available constitute 67% of the listening events.  
#
While coverage is therefore imperfect, I nevertheless assume this amount is sufficient to generate a general picture of the musical landscape in terms of acoustic features. 
#
As there is no way to use a song in genre construction without information about its features, I limit all substantial analysis to the the 1.3 million songs for which such feature information is available. 

*** kernel construction :ignhead:

#+label: dists
#+caption: Exemplarary probability distributions over feature space
#+attr_latex: :width 9cm :float wrap :placement {R}{0pt}
[[file:figures/ills.pdf]]
# 
To construct a schema for a genre, I construct a separate probability distribution for each of the 12 high-level dimensions using kernel density estimation. 
# 
This approach is similar to constructing a histogram, but does not require fixed bins as each point (song) shapes the probability density function around it.[fn::see https://mathisonian.github.io/kde/ for an illustration.]
# 
Effectively, kernel density estimation smooths the histogram. 
# 
While no clear bins are required, a crucial parameter is the /bandwidth/, which for each point determine the type and range of influence on the overall probability function. 
# 
Large values smooth the distribution strongly, while small values result in more local variation in the eventual probability function. 
# 
I tried out a number of values, and found that a Gaussian (normal) kernel function with a bandwidth of 0.05 produces plausible results. 
# 
To account for gradient genre membership and variation in popularity, the contribution of each song to the kernel is furthermore weighted by its playcount and relative tag weight. 
# 
Using this kernel, I calculate the probability for each slot for seven equally-spaced points between 0 and 1. 
# 
While this eventually produces a result similar to a histogram, a key property of the smoothing operation is that at no point the density function is exactly zero, which is necessary for operations of probability distributions. 
# 
One might argue that such smoothing imputes values where actually none exist. 
# 
However given the narrow bandwidth, these values are extremely small (10^{-10} is no rarity), and primarily establish formal comparability rather than substantially distorting informational content. 
# 
Resulting probability distributions over the dimensions of exemplary genres are shows in figure [[dists]]. 

*** Contrast to Hannan, ~footnote?~ :ignhead:
# 
It is worth pointing out to differences of this operationalization to the probabilistic spatial approach formalized by textcite:Hannan_2019_concepts. 
# 
Central to their approaches is to not analyze the features separately, but in combination with each other by constructing a metric feature space where each feature constitutes a dimension. 
# 
Concepts can then positioned as probability densities over the cells of the feature space. 
#
While there is a certain elegance to this approach as each concept only has a single probability function (unlike the here-used approach where a concept has separate ones for each dimension), this approach has crucial disadvantages. 
# 
As it assumes that feature /combinations/, rather than the feature values, form the basis of comparison, a typical feature of ambient music would then not be the mere absence of vocals, but absence of vocals /AND/ low timbre /AND/ low danceability (and so on for each dimension). 
# 
Even with a moderate amount of dimensions and values per dimension, such approach results in a "combinatorial explosion" [[parencite:Murphy_2004_concepts][p.46]] of possible features: 
# 
With a logical minimum of two values per dimension, the 12 dimensions used here would require 2^12 = 4096 cells. 
#
To capture variation in bimodality and adequately represent the dimensions as continuous rather than binary [[parencite:Smith_1981_categories][p.120]], at least three values per dimension would be needed, resulting in 3^12 = 531,441 cells.
# 
The schema approach instead makes much more modest assumptions with 12*7 = 84 values per genre while capturing each slot in substantially better resolution. 




** Hierarchy construction
# 
*** KLD :ignhead:
#+label: kld
#+caption: KLDs between two normal distributions (range -4 to 4, \mu=0).
#+attr_latex: :width 9cm :float wrap :placement {R}{0pt}
[[file:figures/kld.pdf]]

While by now I have estimated the musicological content of all genres, this does not yet result in knowledge about their hierarchical structure. 
#
To infer such a asymmetric relationships, I combine the observation of textcite:Tversky_1986_neighbor that a concept is rated most similar to its superordinate with the recommendation of textcite:Hannan_2019_concepts to use the Kullback-Leibler Divergence as measurement of informativeness (the measure of how much a subordinate differs from its superordinate).
# 
The Kullback Leibler Divergence (KLD) is defined as 
\begin{equation*}
\ {\rm KLD} (P||Q) = \sum \limits_{x \in \mathbb{G}} P(x) \log \left( \frac{P(x)}{Q(x)} \right)
\end{equation*}
with P and Q as probability distributions defined over G features. 
# 
Intuitively, the KLD measures the cost to approximate P with Q. 
# 
It can also be seen as proportional to the likelihood that P is observed if the underlying process is truly described by Q parencite:Shlens_2014_kld.
#

*** kld 2 :ignhead:
Importantly, it is an asymmetric measure, meaning that the KLD between probability distribution P and Q differs from the KLD between Q and P. 
#
While this property is often undesirable, it is here crucial here as hierarchical relations are by definition directional [[parencite:Hannan_2019_concepts][p.55]], as a genre cannot be both superordinate and subordinate of another genre. 
# 
These asymmetric properties of the KLD are shown in figure [[kld]], which shows the cost of approximating different Ps with different Qs.  
# 
The dark blue colored diagonal indicates the low cost of approximating a distribution with a distribution similar (or identical) to itself (while the KLD between a distribution and itself is 0, 0.001 is added to all values facilitate visualization with a log-transformed color scheme). 
# 
The asymmetry becomes clear when comparing the top right with the bottom left corner. 
# 
In the top right corner, a very narrow Q (\sigma = 0.3) is used to approximate a very wide P (\sigma = 4) which is around an order of magnitude more expensive than the reverse case in the bottom left corner where a wide Q is used to approximate a narrow P. 
# 
The reason for this asymmetry can be illustrated in the extreme case of P(x) > 0 and Q(x) =0: 
# 
If the true process (Q) has a zero chance of generating event x, it is not possible for P, which has an x value greater than 0, to be generated by Q, turning the KLD infinite. 
# 
On the other hand, if the true process Q has Q(x) > 0, it is still possible to observe P(x) = 0.
# 
The asymmetries thus correspond to findings in the similarity literature parencite:Tversky_1977_similarity that specific items (narrow normal distribution) are judged as more similar to general items (wide normal distribution) than general items are judged similar to specific items. 


# 
To infer the asymmetric similarity between two genres, I calculate the Kullbach-Leibler Divergence for each component (danceability, timbre etc) separately and then sum up the twelve measures. 
# 
I repeat this process for all genre pairs which results in an asymmetric quadratic matrix.
# 


*** thresholds :ignhead:
# 
A judgment has to be made how the Kullback-Leibler divergences constitute concept-subconcept relationships. 
# 
It might be possible to set a fixed threshold under which every relation is considered a concept-subconcept relations, but this proved to be an unsatisfying: 
# maybe in footnote? separate sentences
# 
If a rather low threshold is chosen (KLD < 0.1), it is possible to estimate a set of concept-subconcept relations that appears plausible (in particular, most genres have a low number of parents), however large numbers of genres (~50%) are then excluded for further analysis as their lowest KLD lies above their threshold. 
# 
However, if the threshold is increased sufficiently to include all or most genres (KLD > 0.3), parent-child relationship increase by order of magnitudes, resulting in network densities (the number of actual links divided by the number of possible links) of up to 0.2. 
# 
Large amount of out-going links (out-degrees) are to some extent plausible for the most general genres (in this case, rock and metal) as these are likely to have dozes of children. 
# 
However, it is implausible that many genres have dozens of parents, which is inadvertently the case when using a high threshold:
# 
While it is certainly possible for genres to have multiple parents, it seems implausible that the hybrids would still be meaningful concepts if they were influenced by dozens of parents. [fn::An ironic play on this large amount of parents is the genre 'industrial jungle pussy punk', which was deliberately coined by the group Mindless Self Indulgence to parody overly specific genres, but yet incorporates much fewer genres than most genres would under a high KLD threshold.]
#

*** lowest scoring parents :ignhead:
# 
However, here again we can exploit the fact that concepts are rated most similar to their superordinate parencite:Tversky_1986_neighbor, as it allows to select as parent(s) for each genre the genre(s) which the genre has the least divergence from. 
# 
While it requires to set the number of parents for each genre in advance, it is possible to avoid the problem of unrealistically high amounts of genre-subgenre relations - or more precisely, unrealistically high amounts of parents[fn::It might be possible to estimate the amount of parents more flexibly from features, size and/or KLD values, which however would require further investigation.]. 
# 
It also allows to gain information on all genres (particularly atypical ones), which is crucial as genres constitute the unit of analysis in the final model, and hence allows to capture more variation in typicality and avoid bias towards genres similar to their parents. 
#
To be able to account for hybrids, which I assume constitute the vast amount of the genres, I have set the number of parents to three for all genres. 
# 
While there are losses in accuracy for genres that clearly diverge (this is most apparent in the most general genres such as rock and metal, which now also are forced to have three parents each), the benefits of this trade-off -- information on all genres and variation in typicality -- appear to me to be worth the cost.
# 

*** example CS :ignhead:
#+label: gnr_nw
#+caption: Exemplary genre network
[[file:figures/acst_spc5.pdf]]

An example of a classification system generated in this fashion is shown in figure [[gnr_nw]] (it is however not an graph that is used for eventual measurement, as these are considerably larger and only marginally useful for visual presentation). 
#
When zooming it, it can be seen that every genre has three parents (incoming arrows), although the directed nature of the links allows the more general genres (e.g. electronic, pop, rock) to be parents to large numbers of subgenres, whereas most genres have not produced any subgenres. 
# 
It can furthermore be seen that while the graph depicts hierarchical relations, there is no clear ordered hierarchy as argued for by (or more precisely, attributed to) the tree-model perspective parencite:Quillian_1966_memory: 
#
Instead a large amount of combination of different elements is visible. 
#
While regions of particular styles are still identifiable, such as metal in the bottom or pop in the top right, these do not constitute strict taxonomic subcategories but rather systems of family resemblance in which the boundaries between styles are blurred. 


** Time Period and Thresholds

*** Overall time frame :ignhead:
#+label: times
#+caption: Daily Listening Events 
#+attr_latex: :width 15cm
[[file:figures/time.pdf]]

Figure [[times]] shows the daily listening events. 
# 
To not confuse genre abandonment with changes in popularity of the service, I limit my analysis to a four year time period from September 2008 to September 2012 in which the popularity of last.fm was at its peak. 
 

*** Cutoffs :ignhead:

With hundreds of thousands of tags appearing at least once, it is obvious that some forms of thresholds have to be employed to ensure that the underlying genres are meaningful. 
# 
However, little support for these can be found in the literature, which has either focused on experiments or observational studies of clearly demarcated concepts.[fn::This issue bears similarities to the Modifiable Areal Unit Problem common in spatial analyses parencite:Cheng_2014_mtup.]
# 
Given this high uncertainty about threshold, a single selection of seemingly plausible values might overstate the confidence of the processes (on the other hand, the increase in certainty in the results as a consequence running multiple models should not be overstated either, as it crucially depends on the chosen base values and the values of the coefficients). 
# 
In particular, the presence and, conditional on this, the content of a genre can be described as a function of:
- the length of each observation window 
- the playcount a song has to acquire in this time period to be counted towards the genre
- the minimum degree of membership in absolute (1-100) and relative (0-1) terms
- the number of songs a genre needs to be included at first (the precise reason for is elaborated in the dependent variable section)
- the number of songs a genre needs to be included after it has been instantiated 
- the minimum number of songs and listening events of a user
- the number of users a genre needs to be included

 
To reduce the uncertainty of a set of particular thresholds, I select base values which (after experimenting with different cutoffs) appear plausible (table \ref{bases}) and modify these base values for each run with two coefficients by multiplication. 
# 
The first coefficient modifies the time span, and the second modifies the strictness of the song, user and genre inclusion criteria. 
# 
Both coefficients are valued 0.75, 1, and 1.25; their combinations results in 9 threshold sets for which I estimate the model. 

*** artist concentration :ignhead:
#+latex: \begin{wraptable}{r}{0pt}
#+attr_latex: :center 
|-------------------------------+------------|
| Variable                      | Base Value |
|-------------------------------+------------|
| Time Span                     |   16 weeks |
|-------------------------------+------------|
| Min. Song Playcount           |          8 |
| Min. Song Weight (abs)        |         16 |
| Min. Song Weight (rel)        |       0.16 |
| Min. Songs in Genre           |         12 |
| Min. Instantiation Count      |         20 |
|-------------------------------+------------|
| Min. Genre Songs per User     |          4 |
| Min. Genre Playcount per User |         10 |
| Min. Users in Genre           |         10 |
|-------------------------------+------------|
| Min. Unique Artists           |          6 |
|-------------------------------+------------|
#+latex: \caption{Base values for genre construction}
#+latex: \label{bases}
#+latex: \end{wraptable}

A stable threshold across models is the extent of concentration by artists.  
# 
In particular, no more than 50% of the songs and 70% of the tag-weighted playcount is allowed to be of a single artist. 
# 
This step was implemented to exclude 'artist-genres' where last.fm users (or perhaps other parties) apparently felt the need to tag songs of famous artists (for example Eminem, Metallica, Rihanna) with the artist name [fn::While the process of institutionalization that turns a name into a category ("Kafkaesque", "Foucauldian", "Bourdieusian") is certainly worth investigating, the mere labeling of artistic works with their creators which seems to be the case here does not constitute such a process of abstraction.]



*** time caveat two :ignhead:
*** para1 :ignhead:
# 
It is thus possible to explicitly state what changes and what remains stable. 
#
While the listening logs accumulate over time and hence allow to reconstruct past listening patterns, no temporal information is available for feature values (AcousticBrainz musicological information) and genre membership (the last.fm tags). 
#
The former is of relatively little concern, as given the relatively short period of time the features with which music is perceived are likely to stay relatively unchanged. 
#
More potential to interfere with accurate genre identification is the lack of longitudinal information on genre membership. 
#
While the tags of each song have accumulated over time, the last.fm API only returns the aggregate labels given to a song at the time of the request. 
#
It is therefore imaginable that songs that were categorized in one genre at one point in time, and with a later emerged one at a later point in time indicate the presence of the second genre at a time where it was not yet developed. 
#
Similarly, temporal changes in the gradient of membership are not recoverable from the available aggregate. 


*** para 2 :ignhead:
However, I argue that this problem has overall little impact on the reconstructing the content of genres at different points in time. 
# 
The music industry is rather innovative and constantly churns out new products, which likely results in rather brief periods of popularity for most songs. 
# 
I hence expect that a song has received most of its tags in a such a short time period that occasional re-classifications at a later point in time do not introduce substantial bias.
# 
One might argue that textcite:Anand_2000_sensemaking and textcite:Anand_2006_charting have shown that the idea of the musical industry as constantly innovative is to some extent ideological fabrication as classical works continue to be popular to such an extent that they would constitute a substantial presence in the charts. 
# 
However, it seems unlikely that such classical works are in high danger of re-categorization as it is precisely their membership in highly established categories that guarantees their continued popularity in the first place. 
#
While new genres might aim for association to gain legitimacy, it seems unlikely that this would result in blatant retagging of classical works, but would rather by visible through integrating stylistic features. 
# 
Even if such re-labeling was common, it would in the worst case result in more conservative estimates as actually dead genres would "piggy-back" on alive genres; but it would not be possible to cause a type I error of giving the impression of genre disappearance where it would actually still be alive.


** Dependent Variable: Genre Abandonment
# 
The primary variable of interest is the disappearance of a genre. 
# 
However, the informal nature of the categories under investigation complicates the ability to exactly determine their disappearance. 
# 
Whereas disappearance in organizations parencite:Rao_1994_reputation,Kennedy_2008_counted,Singh_1991_change or highly institutionalized categories parencite:Lounsbury_2004_sources is demarcated by formal events such as declaration of bankruptcy or removal from category-defining institutions, no natural event indicates the disappearance of a last.fm tag. 
# 
As such, abandonment has to be inferred from use frequencies. 
#
In particular, I define a genre as disappeared if it fails to reach the thresholds in the last 3 time periods (4 or 2 time periods for time coefficients of 0.75 or 1.25, respectively), and code the time point of its last appearance as its time of death (this process effectively lags all predictors by one time period). 
# 


*** Hsu nonsense :ignhead:

To further increase the accuracy of distinguishing alive from dead genres I employ an instantiation threshold of number of songs associated in that period  (20 by default). 
# 
Theoretically, this step exemplifies the notion of textcite:Hsu_2006_jacks of taken-for-grantedness after validation even in the case of mild nonconformity. 
# 
Only from the timepoints it has crossed this threshold, it is included. 
# 
From instantiation, it only needs to adhere to the less rigid genre playcount (12 by default). 
# 
This step distinguishes genres who were clearly established at one point from those that fluctuate in the lower boundaries. 


** Concept predictors
*** Predictor: Informativeness :ignhead:
# 
Informativeness describes the extent to which a subordinate genre differs from their parents textcite:Hannan_2019_concepts, which for each genre are the three superordinates it diverges the least from. 
# 
Informativeness is therefore operationalized as the sum of the Kullback-Leibler divergences between a genre and its three superordinates (since all genres have three parents, it makes no difference whether the mean or sum is taken). 
#
As the original variable is heavily right skewed, it is transformed to a more normal shape with a natural log transformation. 
# 
To assess whether informativeness follows a non-monotic relationship, a quadratic term is added as well. 


*** Predictor: Distinctiveness :ignhead:
# 
Distinctiveness concerns the relation between a genre and the genres in the same cohort textcite:Hannan_2019_concepts, which is defined through parent genres. 
# 
As such, it indicates the extent to which a genre "stands out" from fellow genres at the same level. 
# 
It hence is operationalized as the mean Kullback-Leibler Divergence between a genre and its cohort members. 
# 
Here the advantage of a kernel which smooths the probability distribution of each slot becomes apparent: 
# 
Histograms would result in some bins having a zero value, which would turn the KLD infinite. 
# 
Due to excess skew, this variable is log-transformed as well. 


** Ecology predictors

*** Predictor: bandwagoning, parent popularity :ignhead:
# 
Parents might not only in matter in terms of how informative genres are with regards to them. 
#
It might also be relevant how large parents are: 
#
Roots with large audiences might provide more viewers that can insulate its children, as well as provide symbolic legitimation. 
#
To investigate such legitimation effects, a linear coefficient for (the log of) parent size is added. 
# 

*** density len :ignhead:
# 
An equivalent of the dual relationships of roots can be found for cohorts. 
#
These might not only be relevant in terms of distinctiveness as the concept theories elaborate, but also matter in terms of ecological characteristics. 
#
Density plays a central role in this regard, and the typical arguments of density dependence made for organizations apply to genres as organizational forms as well: 
#
Cohorts with a low number of genres offer opportunities to expand as they provide legitimation, while crowded cohorts are expected to be dominated by competition. 
#
In line with the traditional approach, a genre's cohort density is first operationalized as the number of other genres with which it has at least one parent in common (genres with multiple common parents are only considered once), for which both a linear and a quadratic term are added. 


*** density vol :ignhead:
Additionally, the high detail of the data further allows to operationalize a cohort in terms of playcount. 
#
A cohort may consist of only have a handful of genres, but if these are all highly popular, one might expect different cohort effects compared to an equally-sized cohort of genres of low or medium popularity. 
# 
I have therefore added additional (linear and quadratic) measure of cohort density by summing up the (tag-weighted) playcounts of each genre in the cohort. 
# 
Due to high skew, this variable is natural-log-transformed as well. 


** Controls
# 
Most relevant controls concern the size of a genre, as genres with large following are less likely to be abandoned. 
# 
I therefore control for the (natural log of the) total weighted playcount of a genre by summing up the playcounts for each song weighted by the extent to which it belongs to the genre in question. 
# 
I further control for the natural-log-transformed number of releases in the time period in question using the release date data from MusicBrainz. 
# 
I also use the release information to calculate the average age the songs in the genre, again weighted by song playcount and tag weight. 
# 
The genre age, measured in time periods alive since the first occurrence, is included to control for tenure effects. 
#
Furthermore use the Gini index of playcount by artist to estimate the extent to which a genre is dominated by a small proportion of the artists. 
# 
While tags that were highly dominated by one artist were excluded, variations in evenness are still likely to exist and might impact survival chances. 
# 
Given the phenomenon of gradient multiple membership, it is worth to investigate the extent to which a genre is associated with its items. 
#
I therefore control for the average tag weight of a genre's songs, which is weighted by song playcount. 
# 
Additionally, concepts are likely to differ in the range of features of their members. 
#
I therefore include the average cosine similarity of the pairwise comparison between the songs of a genre (or a random sample of 750 in case there are more members). 



** Estimation: Survival Analysis
# 
To estimate the impact of the covariates on the survival chances I follow similar studies parencite:Kennedy_2008_counted,Negro_2011_winemaking and use a Cox proportional hazards model with piecewise exponential specification. 
# 
In this framework, hazard base rate is estimated for each time spell, and hence relaxes the proportional hazards assumption of the standard Cox model[fn:: textcite:Brostrom_2012_event shows that this model is equivalent to a Poisson regression with time period dummy variables (p.58, 98).].
#
To facilitate the interpretation of the highly artificial constructs, all variables except genre age standardized and mean-centered around 0. 


*** parameter interpretation :ignhead:
Coefficients are logarithms of hazard ratios relative to the baseline hazards parencite:Brostrom_2012_event. 
# 
Risk increases with e^{\beta} when the variable in increased by one unit (which for most variables is one standard deviation), and is therefore interpreted as a relative risk ratio or hazard ratio. 
#
For example, given a coefficient of 0.5, the relative risk of genre abandonment increases with e^{0.5} = 1.65 for a one-unit increase of the corresponding dependent variable. 

*** frailty :ignhead:
While many potential predictors are included, it is still likely that important predictors are omitted, resulting in a violation of independence due to repeated observation of genres over time. 
# 
In the survival model literature, this problem can be addressed with frailty terms, the equivalent of fixed effects. 
# 
However, frailty is primarily treated in terms of a non-individual level variable, such as communities or corporate chains parencite:rossman2012climbing, and not in combination with piecewise constant hazards. 
# 
textcite:Brostrom_2012_event argues that individual frailty causes identification problems and advises against them (p.150). 
# 
While he provides an approach to include both piecewise constant hazards and frailty terms, this model does indeed not properly converge. 
# 
I therefore additionally estimate frailty terms without piece-wise constant hazards (thereby assuming proportionality of hazards). 




* Results

#+latex: \input{./tables/summaries_mult.tex}

#+latex: \input{./tables/pch_res.tex}


** Summary statistics
Table \ref{summaries} shows summary statistics of the variables. 
# 
Since I estimate multiple models without a priori preference for a particular set of thresholds, I averaged the summary values across the 9 models and included 95% confidence intervals. 
# 
The correlation matrix is reported in table \ref{cor_tbl}; which are likewise averaged and hence are reported with 95% confidence intervals. 


** Analysis :ignhead:
All individual piecewise constant hazard (PCH) models are in table \ref{pch} and all frailty models in table \ref{frailty}. 
#
While these tables are not convenient to read, they are indicative of the number of genre abandonments within each set of thresholds (table \ref{pch} also contains the number of genres present at least once within each model specification). 
# 
With the numbers of total genres ranging from 389 to 1703, it can be argued that a wide range of possible values is captured through the use of different threshold sets. 
#
To ease interpretation of the multiple models, I also averaged coefficients and standard errors. 
#
This summary is shown in table \ref{res_sum}. 
#
While not all coefficients are consistent across specifications, the summary table provides a good overview of those that are, to which I will turn first. 
# 

** Controls 
#+latex: \begin{wraptable}{r}{0pt}
#+latex: \input{./tables/res_sum.tex}
#+latex: \caption{Averaged PCH Models}
#+latex: \label{res_sum}
#+latex: \end{wraptable}

*** coef values :ignhead:
It is not surprising that the largest effect is due to the size: 
#
Large genres are widely established and hence much less likely disappear (furthermore, the operationalization of genre abandonment hinges to some extent on size). 
# 
To be precise, an increase of 1 standard deviation of size decreases the risk of dying by 1- e^-1.50 = 78%.
#
All other things being equal, an average-sized genre (1.97 SD above minimum) is has its hazard ratio reduced to e^{1.97 * -1.5} = 5% of that of the smallest genres. 
#
Number of new releases has (despite its high correlation with size) still has an independent negative effect on the hazard ratio as a increase of a standard deviation lowers a genre's relative risk by 1-e^{-0.44} =35%. 
#
Tenure similarly increases a genre's survival chances as each additional time period decrease the hazard by 1-e^{-0.39} = 32%. 
# 
This is also supported by the consistently negative and marginally significant effect of average song age. 
# 
Furthermore, a genre's likelihood to disappear is significantly decreased by an increase of the average similarity of its songs, which supports the idea that a function of concepts is to effectively structure information. 
# 
On the other hand genres with high average tag values are more likely to disappear, which might be indicative of isolation and lack of acceptance of a genre beyond its core. 
# 
There are thus a number of processes which affect genre survival at varying degrees of granularity. 

** Concept variables

#
The summary table shows relative small and insignificant effects of informativeness, albeit the picture changes when inspecting the individual models (table \ref{pch}). 
# 
Here it can be seen that values of informativeness vary greatly, ranging from 0.76 to -0.8; with values of the squared term similarly varying between 0.67 and -0.9. 
# 
Since additionally only two of the linear and one squared term are significant, there is little evidence of a systematic relationship between the distance of a genre to its superordinate and its survival chances (H1). 
# 
While distinctiveness has on average a small negative effect, there is similarly little evidence of consistency as values range from 0.31 to -0.35 (the only significant coefficient). 
# 
As such, little points to a systematic relationship between the extent to which a genre "stands out from the crowd" and its survival prospect (H2). 
 

** Ecological Variables

Similar to the conceptual predictors, the ecological variables differ too much in direction and size to allow generalizations to a systematic impact. 
#
The density terms describing the playcount (vol) vary from 4.7 to -2.75 in the linear specification and from 2.81 to -4.42 in the squared specification between threshold set and thereby display the largest a large degree of variation in coefficients. 
# 
While variation in the density coefficient of genre count (len) is lower with a maximum of 0.89 (squared: 1.05) and a minimum of -1.05 (squared: 0.73), there is little evidence of a systematic relationship either (H3). 
#
The most support for an effect of a central variable of interest is the case of legitimacy (parent size), which is nearly consistently negative (only two of nine models violate this pattern). 
# 
However, the small size of this effect relative to its standard errors still indicate a range of possible values too wide to fulfill the criterion of statistical significance (H4). 




* Discussion

** results accurate :ignhead:
# 
This lack of evidence for conceptual and ecological variables is certainly unexpected. 
# 
A possible interpretation would be that this lack of findings does truly indicate the absence of substantial effects of relational information content on genre survival prospects in the case of musical genres. 
# 
In particular, it might be possible that "genres represent socially constructed organizing principles that imbue artworks with significance /beyond/ their thematic content, and are, in turn, responsive to structurally generated demand for cultural information and affiliation" [[parencite:dimaggio1987classification][p.441, emphasis added]]. 
#
It is imaginable that the information content is indeed secondary to the potential to function as a means of distinction parencite:bourdieu1984distinction, in which case the primary focus would not lie on genres in relation to their features, but the relative power positions of their audiences. 
#
However, such an approach is hard to investigate with the current dataset as no information on socio-economic status is included. 
#
However even if such a distinction-based mechanism is present, it does not imply that thematic content is completely insignificant. 
# 
This is especially likely since a non-relational measure of thematic content, the average song similarity, consistently predicted a decrease of likelihood of abandonment. 
#

** limits structure :ignhead:
#
If thematic content matters, it becomes crucial to contrast the intrinsically (song similarity) and relationally defined variables. 
#
While it might be that audiences do only evaluate internal coherence, a more likely explanation seems to me that the theories used to construct the genre hierarchy do not adequately model relationships between genres. 
#
A particularly weak links seems to lie in the dynamic hierarchy construction /based on feature values/ as proposed by textcite:Murphy_2004_concepts: 
#
While there is some evidence that in everyday judgments people use the extent of feature matching to judge membership, it does not need to be the case that genre relationships are judged in the same manner. 
# 
First, decisions to align or distance a genre in relation to others might be much more thought through than quick judgments of whether a car seat is a piece of furniture. 
# 
Second, they might be much more concerned with particular items, in this case songs, than the feature generalizations that characterize schemata. 
# 
These considerations hence imply a genre hierarchy constructed from tag co-occurrence in songs, which is much more feasible than the one based on audience power positions. 
# 
Such an approach would then use the presence of multiple membership to a great extent, and thereby also allow to distinguish similarity between genres that comes from multiple memberships (of the same songs) and unique membership of similarly sounding songs. 


** limits concepts :ignhead:
# 
Another cause of error might lie in the current requirement of three parents for each genre might be overly rigid and assume hierarchical connections where none exist, or on the other hand overlook these. 
# 
Whether such issues would still be present in a hierarchy based on co-occurrence, or if generally a different approach to constructing hierarchical links from asymmetric similarities exists, remains subjects of further research. 
# 

** additions :ignhead:
#
Topics for further investigations are generally of no short supply given the complexity of the data and their public nature that allows the combination with a variety of other data sources. 
#
The influence of user tastes is one of them, as differences in breadth and volume might be influential. 
#
This area would also allow to focus more on how a classification system is internalized parencite:Lizardo_2016_improving, and hence would allow to measure the extent of agreement of categories [[parencite:Hannan_2019_concepts][p.189]].
#
A focus on the user experience could also investigate the influence of changes in the interface of last.fm. 

#
The degree of continuity or disruption in intensional features, extensional items and/or users over time might be relevant as well, especially to investigate the question of structural inertia parencite:Hannan_1977_ecology.
#
More explicit forms of legitimation might be yet another topic which turned out to be beyond the scope of the current project. 
# 
However, formal tokens of legitimation such as awards, or the degree of adherence to established musical classification systems might very well influence a genre's survival chances. 
#



* Conclusion
This study investigated genre abandonment as a consequence of inadequate amount of differentiation from superordinates, lack of distinction from cohort members, lack of legitimation through parents and competition with cohort members. 
# 
However the employed operationalizations did not lead to significant effects of these relationally defined predictors of genre abandonment that were consistent between a different model specifications.
# 
It might thus be that relative informative content does indeed have no substantial influential on concept survival which, given the existing literature on concepts as tools for structuring information and the finding of substantial impact of non-relationally defined predictors, is less likely than a misspecification of the hierarchical genre structure by relying on feature overlap. 
#
Despite the lack of clear findings in this study, these two specific concerns as well as a wide range of other possible angles highlight the ample opportunities that exist to further investigate how concepts are used to make sense of the world. 



* refs :ignhead:
#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}

* Appendix

The code used to generate the analyses is available at https://github.com/swhalemwo/thesis. While all data used is publicly available, I can also provided all data used to anybody who does not want to query rather slow APIs for multiple weeks. 


#+latex: \input{./tables/cors_mult.tex}

#+latex: \input{./tables/frail_res.tex}

** export :noexport:
#+BEGIN_SRC emacs-lisp
  (org-babel-tangle)
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                      'comment 'identity))
      do
      (setf (buffer-substring (org-element-property :begin comment)
                  (org-element-property :end comment))
            "")))

  (let ((org-export-before-parsing-hook '(delete-org-comments)))
    (switch-to-buffer (org-latex-export-to-pdf)))
#+END_SRC

#+RESULTS:
: #<buffer /home/johannes/Dropbox/gsss/thesis/text/thesis.pdf>

