
#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
# #+OPTIONS: num:nil
#+OPTIONS: toc:nil
# #+OPTIONS: toc:nil#+TITLE: #+AUTHOR: #+DATE: 
# #+OPTIONS: h:5




# -*- org-export-babel-evaluate: nil -*-

* header :ignhead:
#+latex: \input{./title_page}

# #+TOC: headlines 3
#+latex: \tableofcontents



* Introduction
** para 1 :ignhead:

Classification systems are essential for social life parencite:Durkheim_2019_primitive. 
# 
Without conceptual systems to aid in sense-making and generalization of experience, the complexity of perception would be overwhelming. 
# 
Interpretive frameworks that structure perception and allow cognitive processing to make sense of the world parencite:Hsu_2006_jacks,Zuckerman_1999_illegitimacy. 
# 
Yet it is equally important to take a step back from the deployment of categorical systems and investigate the processes and dynamics that these very classification systems are shaped by.  
# 
While often taken-for-granted, a classification system is not immune to change. 


** para 2 :ignhead:
# 
In this study, I focus on a particular process of change, namely abandonment of concepts. 
# 
Using the case of last.fm, a digital music service website, I investigate which forces shape the disappearance of particular genres. 
#
In particular, I focus on predictors that measure the informative content of a genre vis-a-vis its more general superordinates ("metal" is a superordinate of "death metal") and its cohort members on the same level of specificity ("black metal" and "death metal" are cohort members). 
#
Using an ecological approach parencite:Ruef_2009_credit, I further investigate how density (the saturation of a genre's environment) influences survival chances. 
#
Contrary to my expectations, I find no substantial effects of my key variables, which I argue is likely due to difficulties of operationalization. 
#

** para 3 :ignhead:
# 
The rest of the study is structured as follows: 
#
First, I outline the main theoretical developments in the literature on concept structure, which are furthermore evaluated in terms of ecological mechanisms. 
# 
I then describe the case of last.fm, which gives highly detailed account on category membership and listening histories. 
#
I give then a detailed description of how this data was processed to construct a genre-network, whose longitudinal properties I exploit to fit a survival model that measures genre abandonment. 
#
As I fail to find substantial support for my key predictors, I discuss possible causes and outline areas for future research. 


* Theoretical framework
** The structure of concepts: What makes something something? 

*** classical view :ignhead:
# 
The question of how information is stored and processed to enable complex cognitive functions is not a recent one. 
#
textcite:Smith_1981_categories,Strauss_1997_cognitive and textcite:Murphy_2004_concepts characterize the historical development of the scholarship of concepts by contrasting broad developments. 
#
The main distinction is posited between the so-called /classical view/, taken for granted "since Aristotle" [[parencite:Smith_1981_categories][Preface]] up to the 1970s, against a much more recently emerged /probabilistic view/. 
# 
The classical view is primarily characterized by logic and well-orderedness of the conceptual realm, which is expressed in particular in the idea of /concepts as definitions/ [[parencite:Murphy_2004_concepts][p.15]].  
#
Drawing on formal logic and set theory, it posits that a concept can be clearly defined in terms of its necessary and sufficient features. 
# 
Category membership is hence seen as clear cut: 
# 
Either an item fulfills the specific requirements, in which case it is a member, or it is a clear non-member. 
# 
For example, prime numbers constitute an category where membership can be clearly defined: 
# 
A number is either divisible only by 1 and itself in which case it is a member, or by additional numbers, in which case it is a clear non-member. 
# 

*** probabilistic view :ignhead:
While such a rigid view has appeal as it provides a great amount of clarity (or rather, is assumed to do so [fn::A more situated analysis might evaluate the taken-for-grantedness of the classical view through a theoretical lens of logocentrism parencite:derrida2016grammatology or a bureaucratic institutional logic parencite:thornton_2012_logics]), the high requirements for formal integrity can create problems when trying to find a clear definition. 
# 
textcite:Wittgenstein_1968_investigations has pointed out these problems in his influential discussion of the attempt to define the the everyday-concept of "game":

#+begin_quote
"If you look at [board-games, card-games, ball-games, Olympic games, and so on] you will not see something that is common to all, but similarities and relationships [...] Look for example at board-games, with their multifarious relationships. Now pass to card-games; here you find many correspondences with the first group, but many common features drop out, and others appear. When we pass next to ball-games, much that is common is retained, but much is lost. Are they all 'amusing'? Compare chess with noughts and crosses. Or is there always winning and losing, or competition between players? Think of patience. In ball games there is winning and losing; but when a child throws his ball at the wall and catches it again, this feature has disappeared. Look at the parts played by skill and luck; and at the difference between skill in chess and skill in tennis. Think now of games like ring-a-ring-a-roses; here is the element of amusement, but how many other characteristic features have disappeared! And we can go through the many, many other groups of games in the same way; can see how similarities crop up and disappear. And the result of this examination is: we see a complicated network of similarities overlapping and criss-crossing: sometimes overall similarities, sometimes similarities of detail." (p.31)
#+end_quote

*** concept as definition bad :ignhead:
# 
Thus while it might be possible to construct clear-cut membership rules for some categories, the idea that concepts /generally/ are clearly defined seems difficult to uphold.
#
It is worth noting that such ambiguity is not only present in every-day concepts, but in highly formalized domains as well, such as the debate of the planethood of Pluto or the categorization of geometric figures parencite:Lakatos_2015_proofs.
# 
Similarly, attempts to clearly define science such as by the demarcation criterion of falsifiability parencite:popper1971conjectural, have been contested by alternative conceptualizations that stress a multitude of non-formal aspects parencite:Kuhn_2012_structure or outright deny the possibility of a clear definition parencite:Feyerabend_1993_method. 
# 
While (particularly in the latter case of science) the idea of concepts as definitions might be argued to still loom in public consciousness, it encounters difficulties to provide definitions in the case of complex concepts to an extent that warrants the consideration of alternatives. 

*** prototypicality :ignhead:

Difficulties to clearly define a concept have also received empirical support from studies that question clear-cut membership. 
#
textcite:Rosch_1975_family argue that category membership is not absolute, but rather partial. 
#
Asking respondents to list fruits, apples and oranges are listed more frequently than pineapples and blueberries, while tomatoes and olives are listed even less. 
#
Such /typicality effects/ show that membership is not a yes-or-no question, but a gradient. 
# 
However, the mere existence of graded memberships does not provide an explanation of its cause. 

# However, graded memberships still leaves open the question of how a concept (for example, fruit) is structured. 
# 

*** todo need a concept v categories definition paragraph somewhere
intension 
extension

concept and categories as co-constitutive
duality


*** feature overlap -> typicality :ignhead:

For this purpose, textcite:Rosch_1975_family consider the /attributes/ that the different concepts (e.g. different fruits) are associated with: 
# 
An apple for example can be described as approximately hand-sized, being of bright color, being edible, being moderately firm and so on. 
# 
In practice, attributes are typically acquired by having participants list features. 
# 
This necessarily includes the possibility that some features are not used for some concepts as "each item has at least one, and probably several, elements in common with one or more other items, but no, or few, elements are common to all items" [[parencite:Rosch_1975_family][p.574]]. 
# 
This idea formally captures the notion of textcite:Wittgenstein_1968_investigations: 
# 
Rather than being characterized by a set of fully shared features to which logical operations (e.g, necessity or sufficiency) can be applied, "natural semantic categories [can be viewed as] networks of overlapping attributes" [[parencite:Rosch_1975_family][p.575]].
# 
Graded membership of items can hence be explained as "the extent to which they [...] have attributes which overlap those of other members of the category" (ibid.). 
# 
The "attributes of other members of the category" can then be abstracted into prototype which consists of the features that are typical of the category (e.g. fruit): 
# 
The reason then why olives and tomatoes are /atypical/ fruit is that they lack or have only few fruit features (e.g. sweetness, bright-colored, approximately hand-sized), while these features are strongly present in apples and oranges which therefore receive high typicality values. 

# These /feature lists/ can then be used to generate abstractions for each concept by weighing how much each feature was listed for a particular concept. 

*** exemplar vs prototype theory :ignhead:

textcite:Smith_1981_categories and Murphy (citeyear:Murphy_2004_concepts,Murphy_2016_exemplar) refer to these abstractions of feature lists as the /prototype/ theory. 
# 
An alternative theory is the /exemplar/ approach. 
# 
While both rely on the features of items for categorization, the exemplar approach differs in that it does not assume that abstractions are formed but rather posits that many item instances are stored. 
# 
For example, the concept of an orange is then not seen as an abstraction of features, but as the set of objects label as oranges that an individual has encountered so far. 
# 
Exemplar theories can explain the limitations of the classical view (in particularly variation in typicality) however the emphasis on specific instances may underestimate the propensity to generalize [[parencite:Markman_1999_representation][p.247]] or provide only limited explanation of induction parencite:Murphy_2016_exemplar. 
# 
While there are certainly occasions where people rely on specific instances, the current study focuses on everyday concepts in which I consider generalization as proposed by the prototype view to be more adequate. 


*** schema ~currently unclear what level of orange/fruit is~ :ignhead:
# 
So far the prototype theory has been presented as a /feature list/ in which features may differentiated by their importance to the concept. 
# 
However, some features are difficult to represent coherently in an unstructured list. 
# 
For example, the color of a typical fruit can be red or yellow, but less easily both at the same time. 
#
To capture such variation, textcite:Murphy_2004_concepts proposes the /schema/ view as a specialization of the prototype view (textcite:Markman_1999_representation calls the same approach "structured representation"; here I however refer to this perspective as the schema view).
# 
In this view, a concept has a number of dimensions (or slots) in which all possible values are weighted by typicality.
# 
This notion of typical values can be captured more precisely through the concept of a /probability distribution function/, which specifies the probability (typicality) for each position on a slot. 
# 
For example, the "color" slot of the concept of fruit displays the highest values for bright colors such as red or yellow whereas darker colors like green or brown receive lower values. 
# 
A complete prototype can therefore be conceptualized as a collection of probability functions which for each slot describe typical values. 
# 
The contribution of the schema view is hence a refinement of the prototype view as the slots are in many aspects equivalent to features. 
# 
Just as it is not necessary that all concepts have the same features, it is not necessary that all have the same slots: 
# 
Typicality ratings of a ~category member~ (e.g. apple to fruit) does then depend both on how many slots are "alignable" [[parencite:Markman_1999_representation][p.131]] between the item and the prototype as well how well the probability distributions of these alignable differences coincide.[fn::Schemas also allow the specifications of relations between slots. For example, it is not the entire orange that is edible, but only the pulp. While such specifications allow to describe concepts in much more detail, they require an account of the structure. In terms of everyday concepts, in particular the musical genres investigated in this study, an account of the internal structure beyond features (or their probability distributions) has not yet been developed.]



# which - given the probabilistic framework that replaced the classical view - can vary in the degree to which they are associated with the concept.
# 
# For example, the feature of sweetness may be a highly influential one for the concept of fruit, that of size might be moderately important, and the thickness of the peel might only have limited influence. 
# # maybe add schema stuff here
# Exemplar theory however argues sees concepts as collections of objects. 
# # 
# Each encounter with an object is stored, resulting in large list of objects experiences to which new instances are compared. 



** Relations between Concepts
Concepts are not just relevant in terms of their features, but also in terms of their relation to other concepts. 
#
One way in which concepts can be considered to be linked is by their degree of abstraction:
# 
The concepts "fruit", "apple" or "Granny Smith" can all refer to the same object, however the concepts differ in their degree of specificity. 
# 
The question hence arises how these different levels of abstraction are related to each other.[fn::the question which level is used in everyday life is a separate question which is discussed by [[textcite:Murphy_2004_concepts][p.197]].]
# 

*** Hierarchical Relations: tree structure bad ~necessary? Stick with fruits?~ :ignhead:
# add references? 

# "Animals" for example refers to a much more general category than does "mammals", while "dogs" and "cats" are even more specific concepts. 
# #
# What is however less obvious is the relations between these concepts at different levels of abstraction. 
# 
# The example of a species taxonomy shows a well ordered hierarchical structure that represents a tree parencite:Collins_1969_retrieval. 
# 

In such a model, a general concept stem branches out into a few sub-concepts, which in turn are the basis for even more fine-grained twig-like concepts. 
#
At each level, a concept has one (and only one) superordinate concept from which it inherits features.
# 
Category memberships is therefore transitive as all Granny Smiths and ~Elstars~ are both apples as  well as fruits, and all apples are fruit. 
#
Furthermore, there is no "cross-branching" between once separated concept links as no apple is also a member of the "vegetable" category. 
# 
An valuable contribution of this perspective is its ability to explain the location of feature values. 
#
In particular, it posits that features are only stored at the level of abstraction for which they are relevant, and "passed down" the branches parencite:Collins_1969_retrieval. 
# 
For example, it argues that we do not need to store the feature "is edible" for every fruit we have a concept of separately, but that the "is edible" feature is stored only once in a general "fruit" class which all specific fruit concepts inherit. 
#
However, this model has the substantial requirement of explicitly stored links between different levels to allow concepts to retrieve features of their superordinates. 
# 
While such hierarchical structure is a computationally efficient way of storing information ([[textcite:Markman_1999_representation][p.93]] in fact argues that the limited processing power in the 1950s and 1960s constituted a technical constraint which turned the practical issue of efficient information storage into a theoretical consideration), it is also by definition rather rigid, which raises the question if such a structure would be flexible enough for everyday uses. [fn::The scholars most associated with the taxonomic feature structure, textcite:Collins_1969_retrieval seem to have been aware of the limited applicability of the strictly hierarchical conceptualization (p.242, also see [[textcite:Quillian_1966_memory][p.6]] and [[textcite:Quillian_1988_memory][p.88]]). However this has not prevented scholars both approving parencite:Hannan_2019_concepts and disapproving parencite:Sloman_1998_tree,Steyvers_2005_structure,Murphy_2004_concepts from characterizing the tree model as a /general/ model of conceptual structure. It seems to me that such characterization might be motivated by different topics of interest, such as explicitly institutionalized classification systems in the former contrasted against flexible categorization in everyday life in the latter.]
#

# caution is advised in the judgment of how far such well-orderedness is generally applicable

*** computational :ignhead:
textcite:Murphy_2004_concepts in particular provides three main reasons against explicitly stored hierarchical linkages. 
# 
First, typicality effects are present in hierarchical links as well (p.208). 
# 
Judgments for typical items are generally stronger or faster, whether they concern membership ("a robin is a bird" is evaluated faster as "a penguin is a bird") or feature inference ("birds have an ulnar artery, therefore robins have an ulnar artery" is rated more believable as "birds have an ulnar artery, therefore penguins have an ulnar artery"). 
# 
Secondly, transitivity violations give raise doubts to how strictly membership is passed downwards the branch: 
#
While respondents agree that seats are furniture, and car seats are seats, they deny that car seats are furniture (p.207). 
#
Third, in some occasions statements that would require multiple paths to be traversed are evaluated faster than statements that require less paths.
# 
For example, the statement "a dog is an animal" can be faster validated than the statement ("a dog is a mammal"), although the hierarchical tree would posit the opposite as the former statement requires more paths to be traveled. 

*** overlap 
Due to these arguments that question the existence of stored explicit links between different levels of abstraction, he argues that instead hierarchical relationships are computed on the spot due to feature overlap (p.207). 
#
In this line of reasoning, concepts are considered similar if they are associated with similar features. 
#
While this approach does away with the cognitive economy of a hierarchical order in which features are stored only once, it provides the flexibility to arbitrarily juxtapose concepts. 
# 
Feature overlap can then explain the phenomena that pose problems for the pre-stored view: 
#
As robins are more typical birds than penguins, inferences between the a typical concept and its superordinate flow easier as it resembles the prototype stronger than an atypical one. 
# 
Similarly, while car seats share some features with furniture and some with car seats, car seats and furniture do have a substantial feature overlap, resulting in the rejection of membership of the former in the latter. 
# 
Additionally, the animal concept may be more familiar than the more technical mammal concept, ~resulting in greater feature overlap (does not follow~).

*** hierarchy conclusion
# 
There thus are substantial reasons to prefer the computational view of hierarchical structure. 
# 
A certain similarity of /feature matching/ can be seen as the basis of both concept typicality and concept structure. 
# 
As this approach rejects predetermined concept meaning (in terms of definitions) and pre-stored hierarchical structure, it highlights the flexibility and improvisation that characterize everyday life. [fn::This is not to say that this approach is nearly complete, as it in particular lacks relations between features and context effects, as well as an account of the actual process of  feature matching parencite:Medin_1993_respects. Nevertheless, it provides a useful approach to investigate conceptual structure.]

 between concept meaning in terms of features and conceptual structure can thus be seen as neither are fixed a priori and 


*** asymmetry :ignhead:
These considerations lead to another important aspect of the relations between concepts, namely asymmetry.
#
Hierarchical relations can obviously not be symmetric as a concept can not be both subordinate and superordinate to another concept at the same time. 
#
Yet given the general mechanism of feature overlap, judgments are also not necessarily symmetric between concepts at the same level. 
#
textcite:Tversky_1977_similarity finds for example that North Korea is rated more similar to China than China is to North Korea. 
# 
From a perspective of feature overlap perspective this is expected as the more prototypical China can be better resembled by the variant North Korea than vice versa. 
#
Additionally, triangle inequality is not necessarily adhered: 
# 
With symmetric distances, the distance between two points can not be larger than sum of distances of both to a third point. 
# 
In the case of feature overlap, this does not hold, which textcite:Tversky_1977_similarity shows in the case of Jamaica, Cuba and Russia. 
#
Jamaica and Cuba are rated fairly similar due to their common feature of being located in the Caribbean, as are Cuba and Russia due to their (at the time) shared political system. 
# 
Jamaica and Russia however are not considered similar at all, and in particular are more distant than the sum of distances between Jamaica and Cuba and Cuba and Russia. 
#

*** concept represenation implications ~not clear if relevant~:ignhead:
These considerations have substantial implications for the models used to represent concepts. 
#
They can for example hardly be represented as points in a metric space, as this form of representation assumes symmetry and triangle inequality parencite:Smith_1981_categories,Tversky_1977_similarity. 
#
textcite:Steyvers_2005_structure evaluate different models and suggest networks as better suited alternative. 
#
It is worth pointing out that the hierarchical trees discussed earlier are also forms of networks, albeit very rigid ones as they do not permit interaction between separated branches. 
#
textcite:Hannan_2019_concepts suggest to loosen this constraint and instead model conceptual networks as semi-lattices (p.68), which allows cross-branching. 
#
Concepts can therefore be members of multiple superordinates, in the case of which they constitute hybrids, such as romantic comedy which in the example of films, is both a member of genre "romance" and the genre "comedy". 


** Ecological Dynamics

*** original ecological general :ignhead:
# 
Concepts do not exist in a vacuum, and as all social structures are subject to change. 
# 
Recently, insights from organization ecology parencite:Hannan_1977_ecology,hannan89_organ,Hannan_1992_dynamics,Singh_1991_change have been applied to population of concepts parencite:Ruef_2000_emergence,Ruef_2004_demise,van_Venrooij_2015_ecology. 
# 
This approach allows to study an entire population of concepts rather for example than focus on a few case studies. 
#
It is however worth to first summarize the original research program which focused primarily on long-term industry developments parencite:Hannan_1977_ecology,Hannan_1992_dynamics. 
# 
Here the primary forces that are seen to shape the survival chances of an organization are competition and legitimation. 
# 
textcite:Hannan_1977_ecology has argued that both of these can be inferred from density, which described the number of organizations at a given point in time. 
# 
Legitimation is hypothesized to be the shaping force in times of low densities: 
# 
As new industries develop, they lack still lack recognition, and an increase in organizations operating in the sector increases founding rates and enhances survival prospects as it indicates acceptance of the form. 
#
However, when the an industry is established, an increase in the number of organizations now increases competitive pressure, and therefore increases the risk of failure and decreases founding rates. 
# 
While the specific operationalization of legitimation and competition as a function of density has been both critiqued on theoretical grounds parencite:Zucker_1989_legitimacy and lost relevance due to increasing inclusion of actual measurements of legitimation parencite:Zuckerman_1999_illegitimacy,Rao_1994_reputation,Rao_2005_crossing, the overarching theoretical importance of considering competition and legitimation has remained central to studies of organizational populations cite:Kennedy_2008_counted and classification systems parencite:van_Venrooij_2015_classifications,Piazzai_concepts. 
#


*** focus on selection :ignhead:
Additionally, a central aspect of the ecological paradigm lies in its focus on selection parencite:Hannan_1977_ecology. 
#
in the original framework, organizations (or in this case, concepts) are seen as heavily constrained by their initial configurations. 
# 
While previous literature has investigated concept emergence parencite:Ruef_2000_emergence,van_Venrooij_2015_ecology, less research exists on the causes of selection (but see cite:Lounsbury_2004_sources for a focus on power, and cite:Ruef_2004_demise for a focus on a single organizational form).  

# Rather than flexibly adapting, 

*** applicability :ignhead:
# 
How are these considerations of industry structure relevant to a group of concepts? 
# 
One can discern clear similarities when realizing that concepts operate in a similar way as formal organizations in that they can be argued to compete over another limited resource, namely attention parencite:Piazzai_concepts. 
#
With limited cognitive abilities parencite:Martin_2010_ant, concepts that offer advantages for audiences can be expected to fare better in this competition over mental capacities parencite:Zuckerman_2017_revisited. 
# 
The key question therefore becomes what properties of concepts make them more likely to receive audience attention. 
#
In this regard it is distinguish multiple different ways in which concepts differ in terms of their informative content and their relationships to other concepts. 
#

** Hypotheses
When we recall the (semi-)lattice structure outlined above, we can see first that concepts differ in distance to their superordinate, such as robins and penguins in relation to birds. 
#
As "robin" are more typical birds, the concepts encodes less information than "penguins": 
# 
If we have an animal described to us as "like a robin", we have less information about it than if it is described to use as "like a penguin". 
# 
This distance from the superordinate is characterized as /informativeness/ parencite:Piazzai_concepts,Hannan_2019_concepts. 
#
Following the previous literature, I posit a quadratic relationship between informativeness and survival chances: 
#
Concepts that add little to already existing concepts can be expected to fail, but the same can be expected for extremely informative concepts whose high learning costs is not compensated by their limited utility. 


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Informativeness affects survival chances in a quadratic way as moderately informative concepts are most likely to survive. 


The informative relationships to concepts on the same level (the cohort) needs also be considered.
# 
The degree to which concepts differ from the genres which have the same parents has been coined /distinctiveness/ parencite:Hannan_2019_concepts.
# 
Here I again follow the literature and expect a purely linear relationship: 

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 2*: More distinctive concepts are more likely to survive. 
#+latex: \bigbreak
*** ecology stuff :ignhead:
# 
Next to these relationships of informative content, it is necessary to consider ecological arguments of density dependence. 
#
Here I again expect a quadratic relationship: 
# 
Concepts in unpopulated cohorts can be expected to have their survival chances enhanced by the presence of other concepts, whereas concepts in well-established cohorts are more likely to face competitive pressures. 


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 3*: Density has a quadratic effect on survival chances with enhancing them in low density regions and diminishing them in high density regions. 
#+latex: \bigbreak
While I do not use a formal measure of legitimation, I argue that legitimation can be inferred from parent popularity. 
#
Concepts whose parents are widely established can be expected to be more likely to survive (as parent popularity likely increases the density, the latter has to be controlled for).  

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Legitimation increases the survival chances of a genre in a linear fashion. 


* Data and Methods
** About last.fm
*** general :ignhead:
Last.fm [fn::https://www.last.fm] is a digitial music service website, which provides users a number of ways to organize their music listening activities. 
# 
Founded in 2002, it grew to more than 50 million users a decade later, but has been waning since, presumably due to the emergence of other music streaming services. 
# 
While Last.fm initially hosted internet radio streams, it did not provide on-demand selection of specific works that emerging competitors such as Spotify, Deezer and Google Play provided. 
#
Most importantly for this study, last.fm allows users to track the songs they play on various devices by  /scrobbling/ them to last.fm, which over time builds up a unique listening history [fn::last.fm also has social network features which allow to befriend other users and exchange messages. While the spread of music through social networks is worth investigating, social network data is only accessible publicly to a very limited extent, and even less is available of its the longitudinal development.]. 
# 
The website provides a variety of services to analyze one's music consumption patterns such as weekly reports of favorite songs and artists, and gives recommendations for similar music.
#
Of central importance is also the last.fm API (Application programming interface), which (while by current standards relatively slow) allows access to large amounts of highly detailed information. 

*** labelling :ignhead:


# 
Another way in which users can shape their music consumption on last.fm is through a labeling system:
#
last.fm allows users to freely label songs, artists and tracks with so-called tags. 
#
It is primarily this lack of limitations that distinguishes the categorizations of last.fm from those of other platforms.
# 
In the case of Spotify and Allmusic, genre, style and mood classifications are provided by the musical industry. 
#
Where users have influence, for example in the case of Discogs, they have to select genres from an explicitly  defined classification system which in turn are also subject to control by other users or moderators to ensure correct classification textcite:Piazzai_concepts. 
# 
last.fm however allows users to tag songs, albums and artists without restrictions. 
#
As one might expect this, this opportunity produces vast amount of tags.
#
While familiar concepts such as rock (along its variants of alternative, classic and indie rock), rap, metal, punk, dance or electronic are the most widely used once, a much larger number of much more specific tags are present as well: 
# 
"Italian progressive rock", "punk noise hardcore rocknroll" and "neoclassical darkwave" are examples of highly specific combinations of established genres. 
#
However, since there are no restrictions, tags can also reflect sentiments ("most loved", "i want back to the 60s", "sweetncatchy") or other works ("green eggs and ham"), refer to seemingly trivial features ("title is a full sentence", "why on earth is this just a bonus track") and parody the existence of specialized genres ("TELECFUNKNOHAUSINDUBSTRIPIALBREAKSTEP").
# 
As such, the tags of last.fm constitute (or given its decline in current years, constituted) a diverse conceptual ecology. 
#
Given the low extent of formal structuration and absence of explicit guidelines, it seems likely that mechanisms involving the information content of the concepts have substantial impact[fn::It is however worth pointing out that it is not clear who exactly performs the labeling and therefore might be possible that 'behind the scenes' substantial amount of labeling are not performed by users, but by industry actors. While there are certainly more forces in category creation involved than can be accounted in this study, there is no reason to assume that actors involved in other processes do not also process the genres in terms of features, which are focused in this study.].

*** features :ignhead:
#
Given such extensive opportunities for categorizations, the vast majority of songs has multiple tags (the ones which are only member of one category are songs with very low playcounts).
#
Last.fm therefore weights tags based on the frequency with which they were assigned: 
#
Tags that are often given to a track, artist or album are given high weights and are displayed (without weights) on the respective site to provide genre information to users. 
#
However, weights for all (not just the most popular ones that are listed on the websites) are available via the API [fn::https://www.last.fm/api/].
#
Here the most frequent tag is given the weight 100, while less popular ones receive lower weights. 
#
It is not explicitly stated how tags are weighted, but the distribution of tag weights for songs with few tags shows spikes at 20, 25 and 33 and 50, which makes me fairly confident that weights are assigned in a linear fashion: 
#
As the most popular tag receives a weight of 100, all subsequent ones are weighted by how frequently they were assigned compared to the most popular one (this also seems likely as (unpopular) songs can have multiple tags with weights of 100, which would be plausible if these are all given once). 
# more sources
To standardize the degree of membership, I calculate the proportion of each tag weight to the sum of tag weights given to the song (for example, a tag with weight 50 gets a stronger relative weight when only one other genre is present, compared to when multiple other genres with similar weights are present). 
# 
It is thus possible to estimate the gradient of each membership, which is rare in the case of music classification (for example, genre membership in the more formalized classification systems of Discogs or Allmusic is binary). 
#


** The Music Listening Histories Dataset
*** general :ignhead:
#
Next to information about the tags and their frequencies, the last.fm API also provides access to a users listening history accumulated over his or her time of using the service.
# 
This is a key distinguishing feature from other services that collect such listening histories (such as Spotify or Google Play), for which third parties have to acquire explicit authentication from each user individually. 
#
On last.fm however, users (formally) agree to their listening history being publicly accessible signing up. 
#
textcite:Vigliensoni_2017_mlhd have therefore used the last.fm API to construct a the Music Listening History Dataset (MLHD), which consists of the listening logs of 582,703 random last.fm users with a a total of 27 billion listening events. 
#
To be included, each of the users has to have a total playcount of 7300, corresponding to an average of ten songs every day for a period of two years. 
# 
To maintain degree of cultural consistency I limit my selection to users that have listed the United States as their country of residence, which with around 98,432 users contributes the largest amount of users to the MLHD. 
# 
Due to computational limitations, I select a random subset of 26,231 US users. 

*** bias :ignhead:
While textcite:Vigliensoni_2017_mlhd have sampled the users randomly, such a big data source does not constitute a representative sample in the traditional sense. 
#
First, the very use of last.fm is obviously not evenly spread along socio-demographic lines:
#
Younger (the average age in the sample is 25) and male (men contribute 58%, women 23%, 18% undeclared) demographics are very clearly over-represented.
#
Secondly, the requirement of a playcount of at least 7300 requires that users are avid music consumers, which likely skews the selection to favor consumers whose taste can be described as voracious parencite:Sullivan_2006_voracious. 
# 
Third, there is no information on socio-economic indicators, albeit given that voraciousness is linked to educational qualifications and social status (ibid.) one could likely expect a skew towards upper social strata. 

*** contra-bias :ignhead:
# 
However, such sample bias do not necessarily limit the ability to investigate the development of genres. 
#
As the interest lies in the survival chances of concepts rather than the properties held on a personal level, it has to be considered how the biased sample affects this goal. 
#
From this point of view, the focus on voracious consumers might be a benefit as it highlights those which are heavily invested in music. 
# 
Such avid consumers are likely to have a well-developed sense of their areas of interest which enables them to evaluate the cultural fit of new or existing categories. 
#
Hence their actions might have relatively strong influence on a genre's survival chances.
# 
Additionally, in the case of categories that were coined or established through last.fm's tagging system, highly active last.fm might actually be the best way to study their development. 

*** log processing :ignhead:
#
The dataset consists of a file for each user, with each line constituting a listening event. 
#
Each listening event in turn consists of a time stamp and MusicBrainz IDs (an identification system developed by the MusicBrainz Project) of the song, the album and the artist, to the extent that each was available at the time of dataset construction. 
# 
As my operationalizations of genres as prototypes which describe a probability distribution over feature values, I only use listening events for which an MBID of the song is present[fn::Due to the particular technical setup I use I can currently not precisely estimate how many listening events do not have a song MBID and are therefore dropped. However, I do not think this poses a substantial issue: First, manual inspection of some logs seems to indicate that song MBIDs are generally present, it is rather album MBIDS that seem to be missing. Second, songs lack MBIDs presumably due to their rarity (such as old recordings) and are therefore unlikely to be influential in defining genres.]. 
# 
This results 1,034,669,879 listening events for the 26,231 users, or 39,445 on average. 
# 
This 1 billion of listening events is spread over 4,150,846 unique songs in a highly skewed way. 
#
To obtain genre membership information, I queried the last.fm tag API for the 3.2 million most listened songs  which account for 98.5% of the listening events.
#
Furthermore I used the MusicBrainz API retrieve information on release dates, which is not provided by last.fm. 
#
For 97% songs, both of these queries were successful, which resulted in 3,136,615 songs for which genre membership is available. 
#
In total there are 885,630 tags associated with the 3.1 million songs. 
# 
I will describe later on how these are filtered down. 

# Last.fm however was no exclusive place for avant-garde audiences, as mainstream artists and established genres are ~strongly present~. 
# # 
# Awarded multiple times for its innovativeness, last.fm stood for a time period in the 2000s for a new way of consuming and interacting with music. 
# # 
# New genres in this period of time are likely to have left a trace in the digital listening logs
# TRUE BUT THEN LOGS DON"T SAY ANYTHING ABOUT THEIR CHANCES

** AcousticBrainz and Prototype construction
# unclear if lfm uses acoustic features

*** prototypes more justifiable than exemplars :ignhead:

One might (correctly) argue that it is already possible to generate a model of the semi-lattice structure of genres without reference to their attributes. 
#
It is for example possible to use the song-tag links to generate measures of co-occurence to infer a genre hierarchy:
#
Genre X might be a subset of genre Y if most or all songs of genre X are also members of the much larger genre Y. 
#
However, such a definition is /extensional/ and corresponds more to the exemplar model than an /intensional/ feature-based prototype parencite:Murphy_2004_concepts. 
# 
It would therefore be much more cognitively expensive as large numbers of objects would have to be stored, whereas a prototype is much more compact and hence cognitively processable due to its level of abstraction  [fn::It is nevertheless worth noting though that despite a lacking theoretical foundation this is likely the underlying principle of last.fm's recommendation system as there is no indication that last.fm anywhere uses musicological features (Spotify on the other hand seems to integrate musicological features in their services, as it makes them accessible via the API).].


*** actual features :ignhead:
 # (and more importantly, the meaning vis-a-vis other genres) 
A thoroughly theoretically-informed cognitive model therefore requires information regarding the features of the items, from which then (as category memberships are known) prototypes can be inferred. 
#
For this purpose I use the AcousticBrainz project [fn::https://acousticbrainz.org], a joint effort of the Music Technology Group at Universitat Pompeu Fabra in Barcelona and the /MusicBrainz/ aiming to provide detailed musicological information on a large number of tracks. 
#
AcousticBrainz provides information on two levels: 
# 
Low-level data is comprised of more technical characteristics such as measures for loudness, dynamics and spectral shape of a signal, rhythm descriptors and tonal information such as keys and scales, which results in hundreds of variables whose specific meaning is hard to discern. 
#
High-level data however consists of summarizing constructs based on the low-level data obtained through supervised machine learning. 
# 
As evaluating the highly technical aspect of low-level musicological data generation is beyond the possibilities of this project, I exclusively use the high level-data as I assume that it captures meaningful differentiation in terms of how songs sound. 
#
In particular, I use 12 dimensions of the high-level data which describe each track in terms of danceability, gender (of vocals), timbre, tonality, voice (contrasted against instrumentality), acoustic-ness (vs non-acoustic), aggressiveness, electronic-ness (vs non-electronic), happiness, party-ness, relaxed-ness, and sadness. 
# 
Each of the dimension ranges from 0 to 1. 
# 

*** Data availability :ignhead:
# 
As the data of AcousticBrainz requires much more active processing than the mere registering done by last.fm and MusicBrainz, it is to be expected that coverage would be substantially worse. 
#
Of the 3.1 million songs for which genre metadata was retrieved from last.fm and MusicBrainz, only 1,318,900 had musicological information included by in AcousticBrainz. 
#
As there is likely some motivation to process more popular tracks, the 1.3 million tracks for which musicological information is available constitute 67% of the listening events.  
#
While coverage is therefore imperfect, I nevertheless assume this amount is sufficient to generate a general picture of the musical landscape in terms of acoustic features. 
#
As there is no way to use a song in genre construction without information about its features, I limit all substantial analysis to the the 1.3 million songs for which such feature information is available. 

*** binominal distributions :ignhead:

#+label: dists
#+caption: Exemplarary probability distributions over feature space
#+attr_latex: :width 9cm :float wrap :placement {R}{0pt}
[[file:figures/ills.pdf]]

To construct a schema a genres, I construct a probability distribution of each of the 12 high-level dimensions. 
# 
Typical values for all positions are inferred by selecting all songs that are members of the genre, and construct a histogram for each dimension. 
# 
I use five bins for each dimensions which allows to capture variation on each dimension while not being too complex. 
# 
To account for gradient genre membership and variation in popularity, the contribution of each song to the histogram is weighted by its playcount and relative tag weight. 
# 
The probability distributions over the dimensions of exemplary genres are shows in figure [[dists]]. 


*** Contrast to Hannan, ~footnote?~:ignhead:

It is worth pointing out to differences of this operationalization to the approach used by textcite:Ruef_2000_emergence  and formalized by textcite:Hannan_2019_concepts. 
# 
Central to their approaches is to not analyze the features separately, but in combination with each other by constructing a metric feature space where each feature constitutes a dimension. 
# 
Concepts can then positioned as probability densities over the cells of the feature space. 
#
While there is a certain elegance to this approach as each concept only has a single probability function (unlike the here-used approach where a concept has separate ones for each dimension), this approach has crucial disadvantages. 
# 
Most importantly it assumes that feature /combinations/, rather than the feature values, form the basis of comparison.
# 
A typical feature of ambient music would then not be the mere absence of vocals, but absence of vocals /AND/ low timbre /AND/ low danceability (and so on for each dimension). 
# 
Even with a moderate amount of dimensions and values per dimension, such approach results in a "combinatorial explosion" of possible features: 
# 
With a bare minimum of two values per dimension, the 12 dimensions used here would require 2^12 = 4096 cells. 
#
To capture variation in bimodality, at least 3 values per dimension would be needed, which would result in 3^12 = 531,441 cells.
# 
It is primarily on these grounds of computational complexity that textcite:Murphy_2004_concepts generally rejects approaches involving feature combinations (p.45). 



*** Cutoffs :ignhead:
A number of cutoffs are introduced to construct meaningful genres: 
#
Songs where only considered if they had an weighted aggregate playcount greater than 8 to prevent the songs with little influence to slow down the analysis. 
# 
As all major measures are thoroughly weighted by playcount, I am fairly confident this does not bias the results. 
# 
Additionally, a tag needs to occur on at least 15 unique songs with a minimum absolute weight of 20 (maximum 100; indicating  a tag is used no less than a fifth of the maximum tag) and a minimum relative weight of 0.1 (maximum 1; indicating that at least 10 percent of all membership assignments go to the tag in question).
# 
This step both excludes idiosyncratic tags as well as ensures that genres have sufficient information to properly estimate similarity measures (discussed below) which might be biased if the content of a genre cannot be sufficiently established. 
# 
Furthermore, each genre needs at least 8 unique artists, and no more than 50% of the songs and 70% of the tag-weighted playcount is allowed to be of a single artist. 
# 
This step was implemented to exclude 'artist-genres' where last.fm users (or perhaps other parties) apparently felt the need to tag songs of famous artists (for example Eminem, Metallica, Rihanna) with the artist name [fn::While the process of institutionalization that turns a name into a category ("Kafkaesque", "Foucauldian", "Bourdieusian") is certainly worth investigating, the mere labeling of artistic works with their creators which seems to be the case here does not constitute such a process of abstraction.]
#

** Hierarchy construction
# 
*** KLD :ignhead:
While by now I have estimated the musicological content of all genres, this does not yet result in knowledge about their hierarchical structure. 
#
To infer such a asymmetric relationships, I combine the observation by [[textcite:Smith_1981_categories][p.118]] as well as textcite:Tversky_1986_neighbor that a concept is rated most similar to its superordinate with the recommendation of textcite:Hannan_2019_concepts to use the Kullback-Leibler Divergence as measurement of informativeness (the measure of how much a subordinate differs from its superordinate).
# 
The Kullback Leibler Divergence (KLD) in turn is defined as 
\begin{equation*}
\ {\rm KLD} (P_1||P_2) = \sum\limits_{x \in \mathbb{G}} P_1(x)  \log \left( \frac{P_1(x)}{P_2(x)} \right)
\end{equation*}
with P_1 and P_2 as probability distributions over G features. 
#
Most importantly, it is an asymmetric measure, meaning that the KLD between probability distribution P_1 and P_2 differs from the KLD between P_2 and P_1. 
#
While this property is often undesirable, it is here crucial here as hierarchical relations are by definition directional [[parencite:Hannan_2019_concepts][p.55]], as a genre cannot be both superordinate and subordinate of another genre. 
# 
To infer the hierarchical structure, the resulting 60 feature positions are used to calculate the Kullback-Leibler Divergence between all genres, which, given the asymmetry of the measurement, results in an asymetric quadratic matrix [fn::As the KLD is intended for single probability distribution, it might seem strange to use it for multiple ones simultaneously. However, since the KLD is additive, and the values of each slot add up to 1 there is no difference between calculating the KLD for the dimensions separately or calculating it jointly.].
# 


*** thresholds :ignhead:
# 
A judgment has to be made how the Kullback-Leibler divergences constitute concept-subconcept relationships. 
# 
It might be possible to set a fixed threshold under which every relation is considered a concept-subconcept relations, but this proved to be an unsatisfying: 
# maybe in footnote? separate sentences
# 
If a rather low threshold is chosen (KLD < 0.1), it is possible to estimate a set of concept-subconcept relations that appears plausible (in particular, most genres have a low number of parents), however large numbers of genres (~50%) are then excluded for further analysis as their lowest KLD lies above their threshold. 
# 
However, if the threshold is increased sufficiently to include all or most genres (KLD > 0.3), parent-child relationship increase by order of magnitudes, resulting in network densities (the number of actual links divided by the number of possible links) of up to 0.2. 
# 
Large amount of out-going links (out-degrees) are to some extent plausible for the most general genres (in this case, rock and metal) as these are likely to have dozes of children (for example in the final dataset, there are 110 genres which contain the string "metal", and 146 which contain "rock"). 
# 
However, it is implausible that many genres have dozens of parents, which is inadvertently the case when using a high threshold:
# 
While it is certainly possible for genres to have multiple parents, it seems implausible that the hybrids would still be meaningful concepts if they were influenced by dozens of parents [fn::An ironic play on this large amount of parents is the genre 'industrial jungle pussy punk', which was deliberately coined by the group Mindless Self Indulgence to parody overly specific genres, but yet incorporates much fewer genres than most genres would under a high KLD threshold.]
#

*** lowest scoring parents :ignhead:
# 
However, here again we can exploit the fact that concepts are rated most similar to their superordinate [[parencite:Smith_1981_categories][p.118]], as it allows to select as parent(s) for each genre the genre(s) which the genre has the least divergence from. 
# 
While it requires to set the number of parents for each genre in advance, it is possible to avoid the problem of unrealistically high amounts of genre-subgenre relations - or more precisely, unrealistically high amounts of parents[fn::It might be possible to estimate the amount of parents more flexibly from its features, size and/or KLD values, which however would require further investigation.]. 
# 
It also allows to gain information on all genres (particularly atypical ones), which is crucial as genres constitute the unit of analysis in the final model, and hence allows to capture more variation in typicality and avoid bias towards genres similar to their parents. 
#
To be able to account for hybrids, which I assume constitute the vast amount of the genres, I have set the number of parents to three for all genres. 
# 
While there are losses in accuracy for genres that clearly diverge (this is most apparent in the most general genres such as rock and metal, which now also are forced to have three parents each), the benefits of this trade-off -- information on all genres and variation in typicality -- appear to me to be worth the cost.
# 

*** example CS :ignhead:
#+label: gnr_nw
#+caption: Exemplary genre network
[[file:figures/acst_spc5.pdf]]

An example of a classification system generated in this fashion is shown in figure [[gnr_nw]] (it is however not an graph that is used for eventual measurement, as these are considerably larger and only marginally useful for visual presentation). 
#
When zooming it, it can be seen that every genre has three parents (incoming arrows), although the directed nature of the links allows the more general genres (e.g. electronic, pop, rock) to be parents to large numbers of subgenres, whereas most genres have not produced any subgenres. 
# 
It can furthermore be seen that graph depicts hierarchical relations, there is no clear ordered hierarchy as argued for by (or more precisely, attributed to) the classical view parencite:Quillian_1966_memory: 
#
Instead a large amount of combination of different elements is visible. 
#
While regions of particular styles are still identifiable, such as metal in the bottom or pop in the top right, these do not constitute strict taxonomic subcategories but rather systems of family resemblance in which the boundaries between styles are blurred. 

** Time frame
#+label: times
#+caption: Daily Listening Events 
#+attr_latex: :width 15cm
[[file:figures/time.pdf]]

#
The temporal element of listening logs allows to investigate the longitudinal development of genre survival in a very flexible way as listening events can be selected for any time-period of interest. 
#
This flexibility however also requires to explicitly choose time intervals, as there is no possibility to rely on natural time intervals, such as publications in yearly parencite:Rao_2005_crossing or quarterly parencite:Kennedy_2008_counted intervals. 
#
Since my measures depend on playcount (both in genre selection as well as generated variables), I considered it crucial to have equally sized intervals. 
# 
Eventually, I decided on a time period of 12 weeks. 
#
Additionally it is important to misattribute genre abandonment to decreasing popularity of last.fm or data collection ranges. 
# 
Figure [[times]] shows the daily listening events, which display a the harsh decline from 2013 onwards. 
#
It is unclear whether this decline is due to last.fm rapidy losing popularity or due to data collection taking place in that period, but either way, inclusion of 2013 would have resulted in an artificially high mortality rate.
# 
I therefore limit my time periods from the beginning of 2006 to the end of 2012, which given the requirement for equally sized time intervals results in 29 time periods from the beginning of 2006 to the end of September 2012. 
#
While in this time period there were no revolutions in the musical industry parencite:Peterson_1990_advent, with the great amount of detailed data available it should still be possible to identify the entire lifespan particularly of small and emerging genres. 
#

*** time caveat two :ignhead:
# 
It is furthermore important to state what changes and remains stable. 
#
While the listening logs accumulate over time and hence allow to reconstruct past listening patterns, no temporal information is available for feature values (AcousticBrainz musicological information) and genre membership (the last.fm tags). 
#
The former is of relatively little concern, as given the relatively short period of time the features with which music is perceived are likely to stay relatively unchanged. 
#
More potential to interfere with accurate genre identification is the lack of longitudinal information on genre membership. 
#
While the tags of each song have accumulated over time, the last.fm API only returns the aggregate labels given to a song at the time of the request. 
#
It is therefore imaginable that songs who were categorized in one genre at one point in time, and with a later emerged one at a later point in time indicate the presence of the second genre at a time where it was not yet developed. 
#
Similarly, temporal changes in the gradient of membership are not recoverable from the available aggregate. 
#
However, I think that this problems has overall little impact on the reconstructing the content of genres at different points in time because the industry is rather innovative and constantly churns out new products, causing most songs to accumulate most of their playcount in a rather short amount of time. 
# 
One might argue that textcite:Anand_2000_sensemaking and textcite:Anand_2006_charting have shown that the idea of the musical industry as constantly innovating is to some extent ideological fabrication as classical works continue to be popular to such an extent that they would constitute a substantial presence in the charts. 
# 
However, it seems unlikely that such classical works are in high danger of recategorization as it is precisely their membership in highly established categories that guarantees their continued popularity in the first place. 
#
While new genres might aim for association to gain legitimacy, it seems unlikely that this would result in blatant retagging of classical works, but would rather by visible through integrating stylistic features. 



** Dependent Variable: Genre Abandonment
# 
The primary variable of interest is the disappearance of a genre. 
# 
However, the informal nature of the categories under investigation complicates the ability to exactly determine their disappearance. 
# 
Whereas disappearance in organizations parencite:Rao_1994_reputation,Kennedy_2008_counted,Singh_1991_change or highly institutionalized categories parencite:Lounsbury_2004_sources is demarcated by formal events such as declaration of bankruptcy or removal from category-defining institutions, no natural event indicates the disappearance of a last.fm tag. 
# 
As such, their abandonment has to be inferred from their use frequencies. 
#
Since I generate measures for each time period separate, a genre can be classified as having died in period t when in period t+1 it fails any of the thresholds discussed (this effectively lags the predictors by one time period as no information is available for a genre for the time period in which it actually dies). 
#
A further complication arises from the fact that genres can display spotty histories: 
# 
After being considered alive in time period t, it may be considered dead in period t+1 but through a gain in popularity be considered alive again in period t+2. 
#
To ensure that genres have actually disappeared, I do not require them therefore to have died at least three time periods before the end of the observation period. 
#
In the case of abandoned genres with spotty histories the last time period in which they were active is coded as the time period of their abandonment. 
# 
These two operationalizations result in a total of 422 abandoned genres, 235 with complete listening histories and 187 with spotty ones. 
# 
However, preliminary analysis showed that under these conditions, large amounts of genres fluctuate around the lower threshold of 15 songs. 
#
To make sure that genres have actually "been alive" at one point, I further limit my selection to abandoned genres which have had at least at one time point 25 songs associated with them.
# 
This results in a final of 92 abandoned genres for the observation period. 

** Concept predictors
*** Predictor: Informativeness :ignhead:
# 
Informativeness describes the extent to which a subordinate genre differs from their parents, which for each genre are the three least-divergent genres textcite:Hannan_2019_concepts. 
# 
Informativeness is therefore operationalized as the sum of the Kullback-Leibler divergences between a genre and its three superordinates (since all genres have three parents, it makes no difference whether the mean or sum is taken). 
#
As the original variable is heavily right skewed, it is transformed to a more normal shape with a log transformation. 
# 
To whether the impact of informativeness differs depending on its size, a quadratic term is added as well. 


*** Predictor: Distinctiveness :ignhead:
# 
Distinctiveness concerns the relation between a genre and the genres in the same cohort textcite:Hannan_2019_concepts, which is defined through parent genres. 
# 
As such, it indicates the extent to which a genre stands out. 
# 
It hence is operationalized as the mean of a distance metric between a genre and the other genres of its cohort parencite:Piazzai_concepts. 
# 
However, an issue arises with the choice of the distance metric: 
# 
A central aspect of concept similarity (and distance) is asymmetry parencite:Tversky_1977_similarity, which arises due from feature overlap. 
#
However, the Kullback-Leibler divergence, which had allowed asymmetric similarity judgments to infer the hierarchical structure of the classification framework, is not necessarily defined for relations between cohort members. 
# 
Since the Kullback-Leibler divergence is measured  from one genre to another, it requires the first to be a subset of the second as otherwise the lack of features cause it to be undefined.  
# 
While all songs are measured on the same variables, the splitting of these dimensions into five cells for each features can result in genres having values of zero for some of the features. 
# 
This is no problem for inferring the hierarchical structure as it is constructed with only the three lowest divergences (in practice Python returns undefined divergences as undefined) and hence uses only a small subset (in the case of 1k genres, only 3k/1k*1k-1=0.003=0.3% of the computed KLDs are used for network construction), of which by definition all are defined. 
#
Within cohorts however, Kullback-Leibler divergences can be undefined. 
# 
While textcite:Hannan_2019_concepts recommend the Kullback-Leibler divergence for distinctiveness measurements as well, it cannot reliably be used for this task.
#
The genres also have still the same weighted total amount of features as the presence of zero values on some features is offset by higher values elsewhere, which would result in a measure of similarity based on feature overlap to be symmetric as well. 
# 
Since I could not employ a true asymmetric measurement for distinctiveness,  use the mean cosine similarity between a genre and its cohort members (which is what textcite:Hannan_2019_concepts eventually resort to as well).
# 
While it might that asymmetry is less central for comparisons within cohorts as there due to the shared roots overall similarities can be expected to be lower  than within a random selection of genres, this specific issue clearly requires further investigation. 
# 
Due to excess skew, this variable is log-transformed as well. 


** Ecology predictors

*** Predictor: bandwagoning, parent popularity :ignhead:
# 
Parents might not only in matter in terms of how informative genres are with regards to them. 
#
It might also be relevant how large parents are: 
#
Roots with large audiences might provide more viewers that can insulate its children, as well as provide symbolic legitimation. 
#
To investigate such legitimation effects, linear coefficient for (the log of) Parent size is added. 
# 


*** density len :ignhead:
# 
An equivalent of the dual relationships of roots can be found for cohorts. 
#
They might not only be relevant in terms of distinctiveness as the concept theories elaborate, but also matter in terms of ecological characteristics. 
#
Density plays a central role in this regard, and the typical arguments of density dependence made for organizations apply to genres as organizational forms as well: 
#
Cohorts with a low number of genres offer opportunities to expand as they provide legitimation, while crowded cohorts are expected to be dominated by competition. 
#
In line with the traditional approach, a genre's cohort density is first operationalized as the Number of other genres with which it has at least one parent in common (genres with multiple common parents are only considered once), for which both a linear and a quadratic term are added. 



*** density vol :ignhead:
Additionally, the high detail of the data further allows to operationalize a cohort in terms of playcount. 
#
A cohort may consist of only have a handful of genres, but if these are all highly popular, one might expect different cohort effects compared to an equally-sized cohort of genres of low or medium popularity. 
# 
I have therefore added additional (linear and quadratic) measure of cohort density by summing up the (tag-weighted) playcounts of each genre in the cohort. 
# 
Due to the skew, this variable is log-transformed as well. 
#  



** Controls
# 
Most relevant controls concern the size of a genre, as genres with large following are less likely to be abandoned. 
# 
I therefore control for the (log of the) total weighted playcount of a genre by summing up the playcounts for each song weighted by the extent to which it belongs to any genre. 
# 
I further control for the log-transformed number of releases in the time period in question using the release date data from MusicBrainz. 
# 
I also use the release information to calculate the average age the songs in the genre, again weighted by song playcount and tag weight. 
# 
The genre age, measured in time periods alive since the first occurrence, is included to control for tenure effects. 
#
Furthermore use the Gini index of playcount by artist to estimate the extent to which a genre is dominated by a small proportion of the artists. 
# 
While tags that were highly dominated by one artist were excluded (see above), variations in evenness are still likely to exist and might impact survival chances. 
# 
Given the phenomenon of gradient multiple membership, it is worth to investigate the extent to which a genre is associated with its items. 
#
I therefore control for the average tag weight of a genre's songs, which is weighted by song playcount. 
# 
Additionally, concepts are likely to differ in the range of features of their members. 
#
I therefore include the average cosine similarity of the pairwise comparison between the songs of a genre (or a random sample of 750 in case there are more members). 



** Survival Analysis
#+label: hazards
#+caption: Hazard rates over time
#+attr_latex: :width 15cm
[[file:figures/hazards.pdf]]

To estimate the impact of the covariates on the survival chances I follow similar studies parencite:Kennedy_2008_counted,Negro_2011_winemaking and use a Cox proportional hazards model with piecewise exponential specification. 
#
In this framework, hazard base rate is estimated for each time spell. 
# 
This allows the hazard rate to vary over time (figure [[hazards]]), which is required due to substantial changes in the last.fm usercounts (figure [[times]]).
# 
While in traditional studies such a model is difficult as measures are often not available for all participants for all time spells, no such limitations exist for working with trace data which can be aggregated to arbitrary intervals. 

*** parameter interpretation :ignhead:
Coefficients are logarithms of hazard ratios relative to the baseline hazards parencite:Brostrom_2012_event. 
# 
Risk increases with e^\beta when the variable in increased by one unit (which for most variables is one standard deviation), and is therefore interpreted as a relative risk ratio or hazard ratio. 
#
For example, given a coefficient of 0.5, the relative risk of genre abandonment increases with e^{0.5} = 1.65 for a one-unit increase of the corresponding dependent variable. 
# 
To facilitate the interpretation of the highly artificial constructs, all variables except genre age standardized and mean-centered around 0. 

* Results
** Controls 
#+latex: \input{./tables/summaries.tex}

Table \ref{summaries} shows summary statistics of the variables. 
# 
The correlation matrix is reported in table \ref{cor_tbl}


#+latex: \input{./tables/res1.tex}


Table \ref{res1} shows the effects of the variables regarding the information content. 
#
Model 1 includes only controls. 
#
It is not surprising that the largest effect is due to the size: 
#
Large genres are widely established and hence much less likely disappear (furthermore, the operationalization of genre abandonment hinges to some extent on size). 
# 
To be precise, an increase of 1 standard deviation of size decrease the risk of dying by 1- e^-1.05 = 65%.
#
All other things being equal, an average-sized genre (1.79 SD above minimum) is more than six times less likely to die out than the smallest ones. 
#
Number of new releases has despite its high correlation with size still an independent negative effect on the hazard ratio and with each increase of a standard deviation lowers a genre's relative risk by 45%. 
#
Tenure similarly increases a genre's survival chances as each additional time period decrease the hazard by 6%. 
# 
On the other hand, a genre's likelihood to disappear is much increases by the average similarity of its songs, as well as by an unequal concentration of playcount among artist. 
#
It might be that these represent a lack of broader acceptance of the category as strong association with few (or even one) artists and/or a highly specific features lead to dissolution (or failure to permanently establish) a general and flexible concept. 
# 


** Concept variables
#
Model 2 and 3 add informativeness as a linear and both linear and quadratic term. 
#
A quadratic specification seems to be fitting better, however no non-monotonic relationship is predicted as both the linear and the quadratic coefficient are positive, which implies that the impact of distance from superordinates is stronger at higher distances. 
# 
However, the standard errors of both terms are too large and imply reasonable parameters ranging from -0.717 to 1.478 for the linear and -0.786 and 1.566 for the quadratic term. 
#
There is no significant model improvement for between either specification and Model 1 either. 
# 
The parameters for the controls remain substantially unchanged. 
#

*** distinctiveness :ignhead:
Distinctiveness is added on its in Model 4. 
#
With a slight negative coefficient, it points to the direction predicted by the theory.
# 
Yet as in the same case as informativeness, its standard error is too large to be able to speak of a substantial independent effect, which is also supported by the lack of improvement of model fit. 
#
Adding informativeness, informativeness squared and distinctiveness together increases the latter, albeit not to an extent to reach statistical significance or improve model fit. 
#
Neither does adding the ecological variables (Model 6) which might have acted as suppressors substantially change the general picture of absence of evidence of an independent impact of content-related measures. 
# 
There is hence little support for H1 and H2. 

** Ecological Variables
#
#+latex: \input{./tables/res2.tex}
# 
Table \ref{res2} shows the impact of the ecological predictors. 
#
Model 7 is identical to model 1 facilitate the comparison of coefficients.
#
Model 8 adds the linear and squared term for density, measured as the tag-weighted cohort playcount. 
#
Again coefficients are insignificant and model improvement absent, however a non-monotonic relationship appears to be present. 
# 
It is however in the opposite direction as expected: 
# 
In low density regions an increase in density /increases/ the hazard, while a one-unit increase /decreases/ the hazard. 
#
The same relationship can be seen in weakened form for density operationalized with number of genres. 
#
Legitimacy (parent size) has a minuscule positive effect on its own (Model 10), albeit it is only meaningful when controlling for density (Model 11) as larger genres are likely to have more subgenres than smaller ones. 
#
When density is controlled for, legitimacy indeed has a slight negative effect on survival chances, which supports H4. 
# 
It is also noteworthy that in this variable configuration, density defined via number of genres in cohort shows the predicted non-monotonic relationship of decreasing the hazard at lower levels and increasing it at higher ones. 
#
This on the other hand increases the strength of density defined by playcount, which points in the other direction. 
#
Model 12 this time adds the concept based measures. 
# 
Most noteworthy is the decrease the effect size of density defined through the number of genres, particular its quadratic term, which weakens the competitive effect of an increase of the number of genres. 
#
However, the complete absence of statistical significance in the main predictors as well as a lack of model improvement cast strong doubt on any particular interpretation as the large standard errors allow for a wide range of possible interpretations, often ranging near the very opposite of their best estimate. 


* Discussion

** limits DV :ignhead:
# 
What can explain these unexpected results? 
# 
In particular it is surprising that both scholarship of concepts and of ecology do not substantially predict genre abandonment. 
#
It seems reasonable to look not at their individual features, but rather the dependent variable - genre mortality. 
#
This variable is not naturally available, but was constructed from the longitudinal analysis. 
# 
First, it might be that the period for which data is available (2006 to 2012) is insufficiently short to detect disappearance. 
# 
It could hence be possible that what is actually observed is not abandonment but fluctuation over and under an arbitrary threshold. 
#
It might also be that this operationalization of abandonment through a clear threshold does not actually capture genre mortality. 
#
A decently popular genre might stop to exist in its current form and lose, say, 90% of its listening base, but a handful of loyal fans might nevertheless be able to make it seem sufficiently alive. 
#
On the other hand, changes in popularity of a genre do not necessarily imply its abandonment. 
# 
While seems not impossible to use continuous variables to operationalize genre abandonment, the effort to specify it given the complexity involved go beyond the realm of this study. 


** limits concepts :ignhead:
# 
While dependent variable may be misspecified, it might also be that predictive branch is operationalized in a way that makes it unlikely to capture actually existing effects. 
# 
Regarding the theory of concepts, the construction of the genre semi-lattice seems to be the most prone to produce errors. 
# 
In particular the requirement of three parents for each genre might be overly rigid and assume hierarchical connections where none exist, or on the other hand overlook these. 
# 
While as I have outlined previously, a fixed number of parents seemed the best option to include all genres, there is obviously room for improvement as most research so far has focused rather on established classification systems with clear linkages, than how to reconstruct more fleeting classification systems from the traces it left in people's behavior[fn::For example, I also attempted to use Lasso regression to predict a genre's musicological vector with the other genre vectors. However, as it was unclear how well this approach would maintain the central feature of asymmetry I did not pursue this approach further]. 
#
On the other hand, the public availability of large scale datasets such as the MLHD which allow to study this issue in further detail begets optimism.

** limits ecology :ignhead:
#
The link to the limited validity of the ecological variables is straightforward. 
#
With an inadequate measurement of the conceptual structure, density-related measures based on them will be of little use. 
#


** limits theory: ommitted variable :ignhead:
# 
Yet another explanation might be that features are less influential as assumed.  
# 
While the kind of musical genres investigated here are not strongly codified as classification schemes under government regulation, the very fact that they exist as an explicit category in symbolic form on the last.fm website might limit the influence of the probability distributions of their features. 
#
It might for example matter less to have a distinctive intensional sound than an established extensional set of songs. 
# 
In the same line of reasoning, it might be considered a limitation that this study does not distinguish similarity between genres that comes from multiple memberships (of the same songs) and unique membership of similarly sounding songs. 
#

** additions :ignhead:
#
Additionally, a number of other mechanisms that could not be considered here might result in omitted variable bias and hence might be investigated in the future. 
#
The influence of users is one of them, as differences in breadth and volume might be influential. 
#
This area would also allow to focus more on how a classification system is internalized parencite:Lizardo_2016_improving, and hence would allow to measure the extent of agreement of categories[fn::I spent not unconsiderable time to measure agreement by clustering users using LDA and estimating cluster-specific classification systems. However, it turned out to be of little use as the vast majority of abandonded genres were only shared by one cluster]. 
#
The degree of continuity or disruption in intensional features, extensional items and/or users might be relevant as well, especially to investigate the question of structural intertia parencite:Hannan_1977_ecology. 
#
More explicit forms of legitimation might be yet another topic which turned out to be beyond this studies capacities. 
# 
However, formal tokens of legitimation such as awards, or the degree of adherence to established musical classification systems might very well influence a genre's survival chances. 
#


* Conclusion
This study investigated genre abandonment as a consequence of inadequate amount of differentiation from superordinates, lack of distinction from cohort members, lack of legitimation through parents and competition with cohort members. 
# 
However the here-used operationalizations of genre structure and predictors did not lead to any significant effects nor improvement in the prediction of genre abandonment. 
# 
A number of possible explanations was discussed, which highlight in particular the difficulty to detect genre abandonment as well as to determine the concept structure of a weakly institutionalized classification system. 
#
Despite the lack of clear findings in this study, these two specific concerns as well as a wide range of other possible angles highlight the ample opportunities that exist to further investigate how concepts are used to make sense of the world. 




* refs :ignhead:
#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}

* Appendix

The code used to generate the analyses is available at https://github.com/swhalemwo/thesis. While all data used is publicly available, I can also provide the Last.fm tag data and MusicBrainz metadata to anybody who does not want to query rather slow APIs for multiple weeks. 

#+latex: \begin{landscape}
#+latex: \input{./tables/cor_tbl.tex}
#+latex: \end{landscape}

** export :noexport:
#+BEGIN_SRC emacs-lisp
  (org-babel-tangle)
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                      'comment 'identity))
      do
      (setf (buffer-substring (org-element-property :begin comment)
                  (org-element-property :end comment))
            "")))

  (let ((org-export-before-parsing-hook '(delete-org-comments)))
    (switch-to-buffer (org-latex-export-to-pdf)))
#+END_SRC

#+RESULTS:
: #<buffer /home/johannes/Dropbox/gsss/thesis/text/thesis.pdf>

