
#+latex_class: article_usual2
# erases make title
#+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
# #+OPTIONS: toc:nil#+TITLE: #+AUTHOR: #+DATE: 
#+OPTIONS: h:5

# -*- org-export-babel-evaluate: nil -*-

* text
** Introduction

** Theory
*** The structure of concepts 

**** classical view
# 
The question of how information is stored and process to enable complex cognitive functions is not a recent one. 
#
textcite:Smith_1981_categories,Strauss_1997_cognitive,Murphy_2004_concepts characterize the historical development of the scholarship of concepts by contrasting broad developments. 
#
The first contrast concerns is primarily historical and posits a so-called /classical view/, taken for granted since Aristotle up to the 1970s, against a much more recently emerged and theoretically sound /probabilistic view/. 
# 
The classical view is primarily characterized by logic and well-orderedness of the conceptual realm, which entails a the idea of /concepts as definitions/: 
#
Drawing on formal logic and set theory, it posits that a concept can be clearly defined in terms of its necessary and sufficient features. 
# 
Category membership is hence seen as clear cut: 
# 
Either an item fulfills the specific requirements, in which case it is a member, or it is a clear non-member. 
# 
For example, if membership in the category of "animals" requires members to be alive, evince metabolism and movement (or have so in the past), it is clear that a dog or a butterfly are clear members, whereas a rock or a cup of coffee are not. 

**** probabilistic view
While such a rigid view has appeal as it provides a great amount of clarity [fn::A more situated analysis might evaluate its taken-for-grantedness through a theoretical lens of logocentrism parencite:derrida2016grammatology or a bureaucratic institutional logic cite:thornton_2012_logics], it demands high requirements which create problems for everyday concepts: 
#
textcite:Wittgenstein_1968_investigations has pointed out these problems in his influential discussion of the attempt to define the the everyday-concept of "game":

#+begin_quote
If you look at [board-games, card-games, ball-games, Olympic games, and so on] you will not see something that is common to all, but similarities and relationships [...] Look for example at board-games, with their multifarious relationships. Now pass to card-games; here you find many correspondences with the first group, but many common features drop out, and others appear. When we pass next to ball-games, much that is common is retained, but much is lost. Are they all 'amusing'? Compare chess with noughts and crosses. Or is there always winning and losing, or competition between players? Think of patience. In ball games there is winning and losing; but when a child throws his ball at the wall and catches it again, this feature has disappeared. Look at the parts played by skill and luck; and at the difference between skill in chess and skill in tennis. Think now of games like ring-a-ring-a-roses; here is the element of amusement, but how many other characteristic features have disappeared! And we can go through the many, many other groups of games in the same way; can see how similarities crop up and disappear. And the result of this examination is: we see a complicated network of similarities overlapping and criss-crossing: sometimes overall similarities, sometimes similarities of detail. (p.31)
#+end_quote

**** prototypicality
Such difficulties to clearly define a concept have received support from empirical studies that question clear-cut membership. 
#
textcite:Rosch_1975_family argues that category membership is not absolute, but rather partial. 
#
Asking respondents to list fruits, apples and oranges are listed more frequently than pineapples and blueberries, while tomatoes and olives are listed even less. 
#
Such /typicality effects/ show that membership is not a yes-or-no question, but an gradient dependent. 
# 
However, graded memberships still leaves open the question of how a concept (for example, fruit) is structured. 


**** prototypes vs exemplars
# 
In this regard, textcite:Smith_1981_categories,Murphy_2004_concepts distinguish primarily between /prototype/ theories and /exemplar/ theories. 
# 
According to prototype theory, concepts are generalized abstractions of features, which given the probabilistic framework that replaced the classical view, can vary in the degree to which they are associated with the concept.
# 
For example, the feature of sweetness may be a highly influential one for the concept of fruit, that of size might be moderately important, and the thickness of the peel might only have limited influence. 
#
Exemplar theory however argues sees concepts as collections of objects. 
# 
Each encounter with an object is stored, resulting in large list of objects experiences to which new instances are compared. 
#
Recently, textcite:Murphy_2016_exemplar has argued that prototype theory is more adequate in regards to explain phenomena such as conceptual hierarchies (which will be elaborated further), knowledge and induction; I therefore use it primarily. 

**** concepts = features
It is additionally relevant to point out that there is no apriori way to distinguish concepts and features   parencite:Smith_1981_categories: 
# 
The letter e can be a feature of a word such as bed, or it can be a concept if it is compared to other letters, the features the being the positions, shapes and angles of the lines that make up each individual letter. 


**** Hierarchical Relations: tree structure bad

# 
While it is possible to deduce a order in degree of abstraction from this observation, it is also to some degree apparent: 
# 
"Animals" for example refers to a much more general category than does "mammals", while "dogs" and "cats" are even more specific concepts. 
#
What is however less obvious is the relations between these concepts at dfiferent levels of abstraction. 
# 
The case of a taxonomy shows a well ordered hierarchical structure that represents a tree: 
#
At each level, a concept has one superordinate the properties of which its inherits, which causes category memberships to be transitive: 
# 
All dogs and cats are both mammals well as animals, and all mammals are animals. 
#
Furthermore, there is no "cross-branching" between once separated concept links; no cat is also a member of the "fish" category. 
# 
However the concerns raised by the probabilistic view should elicit caution in how far this logical well-orderedness is generally applicable[fn::The scholars most associated with the taxonomic feature structure, [[textcite:Collins_1969_retrieval][p.242]] seem to have been aware of the limited applicability of the strictly hierarchical conceptualization (also see cite:Quillian_1966_memory,Quillian_1988_memory). However, this has not prevented scholars both approving parencite:Hannan_2019_concepts and disapproving parencite:Sloman_1998_tree,Steyvers_2005_structure,Murphy_2004_concepts of characterizing the tree-structure as a /general/ view of conceptual structure. Such a characterization might be motivated different topics topics of interest, such as rigidly institutionalized classification systems in the former contrasted against flexible categorization in everyday life.]
#

**** computational 
textcite:Murphy_2004_concepts in particular provides two main reasons against explicitly stored hierarchical linkages, which leads him to regard the alternative of hierarchical relationships being computed on the spot due to feature overlap as more plausible (p.207). 
#
First, typicality effects are present in hierarchical links as well. 
# 
Judgements for typical items are generally stronger or faster, whether they concern membership ("a robin is a bird" is evaluated faster as "a penguin is a bird") or feature inference ("birds have an ulnar artery, therefore robins have an ulnar artery" is rated more believable as "birds have an ulnar artery, therefore penguins have an ulnar artery"). 
#
Secondly, transitivity violations give raise doubts to how strictly membership is passed downwards the branch: 
#
While respondents agree that seats are furniture, and car seats are seats, they deny that car seats are furniture. 
#
Both effects are however explainable by a seeing hierarchical links as computed by feature overlap. 
#
As robins are more typical birds than penguins, inferences between the a typical concept and its superordinate flow easier as it resembles the prototype stronger than an atypical one. 


**** tversky makes only sense after discussing multiple concepts, so after hierarchy? 
# 
A general approach for how feature overlap leads to similarity judgments has been proposed by textcite:Tversky_1977_similarity in the form of the ratio model. 
#
According to the ratio model, the similarity between concepts a and b corresponds to a relation of their feature sets A and B in such a way that

\begin{equation*}
S(a,b) = \frac{f(A \cap B)}{f(A \cap B) + \alpha f (A-B) + \beta f (B-A)}
\end{equation*}
where /f/ describes a measure for feature salience, and \alpha and \beta describe the weights given to the features exclusive of each concept. 
# 
An assessment of directed similarity from a to b asks how well features of a match those of b, and therefore correspond to \alpha=1 and \beta = 0. 
#
In this case, the similarity can be reduced to 

\begin{equation*}
S(a,b) = \frac{f(A \cap B)}{f(A)}
\end{equation*}

which describes the proportion of feature overlap compared to the features of a.[fn::It is worth to point out that textcite:McPherson_1983_affiliation effectively used the same approach to measure competition between organizational forms]
# 
Robins, for example are typical birds, and therefore the proportion of the intersection of the concepts "robin" and "bird" (f(A \cap B)) to the features of robins (A) is high. 
#
The opposite is the case for "penguins", as one of their defining features, the inability to fly, is not included in the prototype of "bird". 
#

**** dimensionality: not clear if fits properly here
In this line of thought, two concepts are in a hierarchical relationship if the features of the more general one are a subset of the more specific one. 
# 
This may at first seem unintuitive, but is in fact plausible when considering that more features imply higher specificity. 
# 
The concept of mammals, for example, is characterized by more detailed features than the more general concept of animals, or as textcite:Hannan_2019_concepts describe, "The dimensionality of the semantic space of a subconcept is larger that of the parent concept" (p.65). 

**** asymmetry
These considerations lead to another important aspect of the relations between concepts, namely asymmetry.
#
Hierarchical relations can obviously not be symmetric as a concept can not be supordinate and superordinate of another concept at the same time. 
#
Yet given the general mechanism of feature overlap, judgments are also not necessarily symmetric between concepts at the same level. 
#
textcite:Tversky_1977_similarity finds for example that North Korea is rated more similar to China than China is to North Korea
# 
From a perspective of feature overlap perspective this is expected as the more prototypical China can be better resembled by the variant North Korea than vice versa. 
#
Additionally, triangle inequality is not necessarily adhered: 
# 
With symmetric distances, the distance between two points can not be larger than sum of distances of both to a third point. 
# 
In the case of feature overlap, this does not hold, which textcite:Tversky_1977_similarity shows in the case of Jamaica, Cuba and Russia. 
#
Jamaica and Cuba are rated fairly similar due to their common feature of being located in the Caribbean, as are Cuba and Russia due to their (at the time) shared political system. 
# 
Jamaica and Russia however are not considered similar at all, and in particular are more distant than the sum of distances between Jamaica and Cuba and Cuba and Russia. 
#

**** concept represenation implications 
These considerations have substantial implications for the models used to represent concepts. 
#
They can for example hardly be represented as points in a metric space, as this form of representation assumes symmetry and triangle inequality parencite:Smith_1981_categories,Tversky_1977_similarity. 
#
textcite:Steyvers_2005_structure evaluate different models and suggest networks as better suited alternative. 
#
It is worth pointing out that the hierarchical trees discussed earlier are also forms of networks, albeit very rigid ones as they do not permit interaction between separated branches. 
#
textcite:Hannan_2019_concepts suggest to loosen this constraint and instead model conceptual networks as semi-lattices (p.68), which allows cross-branching. 
#
Concepts can therefore be members of multiple superordinates, in the case of which they constitute hybrids, such as romantic comedy which in the example of films, is both a member of genre "romance" and the genre "comedy". 
# 


*** Ecological Dynamics

**** original ecological general
# 
Concepts do not exist in a vacuum, and as every social structures are subject to change. 
# 
Recently, insights from organization ecology parencite:Hannan_1977_ecology,hannan89_organ,Hannan_1992_dynamics,Singh_1991_change have been applied to population of concepts parencite:Ruef_2000_emergence,Ruef_2004_demise,van_Venrooij_2015_ecology. 
# 
This approach allows to study an entire population of concepts rather for example than focus on a few case studies. 
#
It is however worth to first summarize the original research program which focused primarily on long-term industry developments parencite:Hannan_1977_ecology,Hannan_1992_dynamics. 
# 
Here the primary forces that are seen to shape the survival chances of an organization are competition and legitimation. 
# 
textcite:Hannan_1977_ecology has argued that both of these can be inferred from density, which described the number of organizations at a given point in time. 
# 
Legitimation is hypothesized to be the shaping force in times of low densities: 
# 
As new industries develop, they lack still lack recognition, and an increase in organizations operating in the sector increases founding rates and enhances survival prospects as it indicates acceptance of the form. 
#
However, when the an industry is established, an increase in the number of organizations now increases competitive pressure, and therefore increases the risk of failure and decreases founding rates. 
# 
While the specific operationalization of legitimation and competition as a function of density has been both critiqued on theoretical grounds parencite:Zucker_1989_legitimacy and lost relevance due to increasing inclusion of actual measurements of legitimation parencite:Zuckerman_1999_illegitimacy,Rao_1994_reputation,Rao_2005_crossing, the overarching theoretical importance of considering competition and legitimation has remained central to studies of organizational populations cite:Kennedy_2008_counted and classification systems parencite:van_Venrooij_2015_classifications,Piazzai_concepts. 
#


**** focus on selection
Additionally, it is worth to explicitly point out the key focus on selection parencite:Hannan_1977_ecology. 
#
Rather than flexibly adapting, organizations (or in this case, concepts) are seen as heavily constrained by their initial configurations. 
# 
While previous literature has investigated concept emergence cite:Ruef_2000_emergence,van_Venrooij_2015_ecology, less research exists on what causes selection (but see cite:Lounsbury_2004_sources).  


**** applicability
# 
How are these considerations of industry structure relevant to a group of concepts? 
# 
One can discern clear similarities when realizing that concepts operate in a similar way as formal organization in that they can be argued to compate over another limited resource, namely attention parencite:Piazzai_concepts. 
#
With limited cognitive abilities, parencite:Martin_2010_ant, concepts that offer advantages for audiences can be expected to fare better in this competition over mental capacities parencite:Zuckerman_2017_revisited. 
# 
The key question therefore becomes what properties of concepts make them more likely to receive audience attention. 
#
In this regard it is distinguish multiple different ways in which concepts differ in terms of their informative content and their relationships to other concepts. 
#

**** concepts stuff
When we recall the (semi-)lattice structure outlined above, we can see first that concepts differ in distance to their superordinate, such as robins and penguins in relation to birds. 
#
As "robin" are more typical birds, the concepts encodes less information than "penguins": 
# 
If we have an animal described to us as "like a robin", we have less information about it than if it is described to use as "like a penguin". 
# 
This distance from the superordinate is characterized as /informativeness/ parencite:Piazzai_concepts,Hannan_2019_concepts. 
#
Following the previous literature, I posit a quadratic relationship between informativeness and survival chances: 
#
Concepts that add little to already existing concepts can be expected to fail, but the same can be expected for extremely informative concepts whose high learning costs is not compensated by their limited utility. 
#
H1: Informativeness affects survival chances in a quadratic way as moderately informative concepts are most likely to survive. 

The informative relationships to concepts on the same level (the cohort) needs also be considered.
# 
The degree to which concepts differ from the genres which have the same parents has been coined /distinctiveness/ parencite:Hannan_2019_concepts.
# 
Here I again follow the literature and expect a purely linear relationship: 
#
H2: More distinctive concepts are more likely to survive. 

**** ecology stuff
# 
Next to these relationships of informative content, it is necessary to consider ecological arguments of density dependence. 
#
Here I again expect a quadratic relationship: 
# 
Concepts in unpopulated cohorts can be expected to have their survival chances enhanced by the presence of other concepts, whereas concepts in well-established cohorts are more likely to face competitive pressures. 
#
H3: Density has a quadratic effect on survival chances with enhancing them in low density regions and diminishing them in high density regions. 
#
While I do not use a formal measure of legitimation, I argue that legitimation can be inferred from parent popularity. 
#
Concepts whose parents are widely established can be expected to be more likely to survive (as parent popularity likely increases the density, hte latter has to be controlled for).  
#
H4: Legitimation increases the survival chances of a genre in a linear fashion. 






** Data and Methods
*** About last.fm
Last.fm [fn::https://www.last.fm] is a digitial music service website, which provides users a number of ways to organize their music listening activities. 
# 
Founded in 2002, it grew to more than 50 million users a decade later, but has been waning since, presumably due to the emergence of other music streaming services. 
# 
While Last.fm initially hosted internet radio streams, it did not provide on-demand selection of specific works that emerging competitors such as Spotify, Deezer and Google Play provided. 
#
Most importantly for this study, last.fm allows users to track the songs they play on various devices by  /scrobbling/ them to last.fm, which over time builds up a unique listening history [fn::last.fm also has social network features which allow to befriend other users and exchange messages. While the spread of music through social networks this data is only accessible publicly to a very limited extent, and even less is available about the longitudinal development]. 
# 
The website provides a variety of services to analyze one's music consumption patterns such as weekly reports of favorite songs and artists, and gives recommendations for similar music.
#
Of central importance is also the last.fm API (Application programming interface), which (while by current standards relatively slow) allows access to large amounts of highly detailed information. 

**** labelling
# 
Another way in which users can shape their music consumption on last.fm is through a labeling system:
#
last.fm allows users to freely label songs, artists and tracks with so-called tags. 
#
It is primarily this lack of limitations that distinguishes the categorizations of last.fm from those of other platforms.
# 
In the case of Spotify and Allmusic, genre, style and mood classifications are provided by the musical industry. 
#
Where users have influence, for example in the case of Discogs, they have to select genres from an explicitly  defined classification system which in turn are also subject to control by other users or moderators to ensure correct classification textcite:Piazzai_concepts. 
# 
last.fm however allows users to tag songs, albums and artists without restrictions. 
#
As one might expect this, this opportunity produces vast amount of tags.
#
While familiar concepts such as rock (along its variants of alternative, classic and indie rock), rap, metal, punk, dance or electronic are the most widely used once, a much larger number of much more specific tags are present as well: 
# 
"Italian progressive rock", "punk noise hardcore rocknroll" and "neoclassical darkwave" are examples of highly specific combinations of established genres. 
#
However, since there are no restrictions, tags can also reflect sentiments ("most loved", "i want back to the 60s", "sweetncatchy") or other works ("green eggs and ham"), refer to seemingly trivial features ("title is a full sentence", "why on earth is this just a bonus track") and parody the existence of specialized genres ("TELECFUNKNOHAUSINDUBSTRIPIALBREAKSTEP") [fn::they can also turn exceptionally long, such as "songs die so gut sind das ich meiner oma ihr klein haeuschen zwar nicht verkaufen aber zumindest dafuer beleihen wuerde" (german for songs so good that I wouldn't sell, but at least hypothecate my grandma's little house for them)]
# 
As such, the tags of last.fm constitute (or given its decline in current years, constituted) a diverse conceptual ecology. 
#
Given the low extent of formal structuration and absence of explicit guidelines, it seems likely that mechanisms involving the information content of the concepts have substantial impact[fn::It is however worth pointing out that it is not clear who exactly performs the labeling and therefore might be possible that 'behind the scenes' substantial amount of labeling are not performed by users, but by industry actors. While there are certainly more forces in category creation involved than can be accounted in this study, there is no reason to assume that actors involved in other processes do not also process the genres in terms of features, which are focused in this study.].

**** features
#
Given such extensive opportunities for categorizations, the vast majority of songs has multiple tags (the ones which are only member of one category are songs with very low playcounts).
#
Last.fm therefore weights tags based on the frequency with which they were assigned: 
#
Tags that are often given to a track, artist or album are given high weights and are displayed (without weights) on the respective site to provide genre information to users. 
#
However, weights for all (not just the most popular ones that are listed on the websites) are available via the API [fn::https://www.last.fm/api/].
#
Here the most frequent tag is given the weight 100, while less popular ones receive lower weights. 
#
It is not explicitly stated how tags are weighted, but the distribution of tag weights for songs with few tags shows spikes at 20, 25 and 33 and 50, which makes me fairly confident that weights are assigned in a linear fashion: 
#
As the most popular tag receives a weight of 100, all subsequent ones are weighted by how frequently they were assigned compared to the most popular one (this also seems likely as (unpopular) songs can have multiple tags with weights of 100, which would be plausible if these are all given once). 
# more sources
It is thus possible to estimate the gradient of each membership, which is rare in the case of music classification (for example, genre membership in the more formalized classification systems of Discogs or Allmusic is binary). 
#


*** the Music Listening Histories Dataset
#
Next to information about the tags and their frequencies, the last.fm API also provides access to a users listening history accumulated over his or her time of using the service.
# 
This is a key distinguishing feature from other services that collect such listening histories (such as Spotify or Google Play), for which third parties have to acquire explicit authentication from each user individually. 
#
On last.fm however, users (formally) agree to their listening history being publicly accessible signing up. 
#
textcite:Vigliensoni_2017_mlhd have therefore used the last.fm API to construct a the Music Listening History Dataset (MLHD), which consists of the listening logs of 582,703 random last.fm users with a a total of 27 billion listening events. 
#
To be included, each of the users has to have a total playcount of 7300, corresponding to an average of ten songs every day for a period of two years. 
# 
To maintain degree of cultural consistency I limit my selection to users that have listed the United States as their country of residence, which with around 100,000 users contributes the largest amount of users to the MLHD. 
# 
Due to computational limitations, I select a random subset of 26,231 US users. 

**** bias
While textcite:Vigliensoni_2017_mlhd have sampled the users randomly, such a big data source does not constitute a representative sample in the traditional sense. 
#
First, the very use of last.fm is obviously not evenly spread along socio-demographic lines:
#
Younger (the average age in the sample is 25) and male (men contribute 58%, women 23%, 18% undeclared) demographics are very clearly over-represented.
#
Secondly, the requirement of a playcount of at least 7300 requires that users are avid music consumers, which likely skews the selection to favor voracious parencite:Sullivan_2006_voracious consumers. 
# 
Third, there is no information on socio-economic indicators, albeit given that voraciousness is linked to educational qualifications and social staatus (ibid.) one could likely expect a skew towards upper social strata. 

**** contra-bias
# 
However, there is no substantial reason to despair either. 
#
As the interest lies in the survival chances of concepts rather than the properties held on a personal level, it has to be considered how the biased sample affects this goal. 
#
From this point of view, the focus on voracious consumers might be a benefit as it highlights those which are heavily invested in music. 
# 
Such avid consumers are likely to have a well-developed sense of their areas of interest which enables them to evaluate the cultural fit of new or existing categories. 
#
Hence due to this above average interest, their actions might have an above average amount of influence on a genre's survival chances.
# 
Additionally, in the case of categories that were coined or established through last.fm's tagging system, highly active last.fm might actually be the best way to study their development. 

**** log processing
#
The dataset consists of a file for each user, with each line constituting a listening event. 
#
Each listening event in turn consists of a time stamp, and MusicBrainz IDs of (an identification system developed by the MusicBrainz Project) the song, the album and the artist, to the extent that they are available. 
# 
As my operationalizations of genres as prototypes which describe a probability distribution over feature values, I only use listening events for which an MBID of the song is present[fn::Due to the particular technical setup I use I can currently not precisely estimate how many listening events do not have a song MBID and are therefore dropped. However, I do not think this poses a substantial issue: First, manual inspection of some logs seems to indicate that song MBIDs are generally, it is rather album MBIDS that seem to be missing. Second, songs lack MBIDs presumably due to their rarity (such as old recordings) and are therefore unlikely to be influential in defining genres]. 
# 
This results 1,034,669,879 listening events for the 26,231 users, or 39,445 on average. 
# 
This 1 billion of listening events is spread over 4,150,846 unique songs in a highly skewed way. 
#
To obtain genre membership information, I queried the last.fm tag API for the 3.2 million most listened songs, which given the variation in popularity, account for 98.5% of the listening events.
#
Furthermore I used the MusicBrainz API retrieve information on release dates, which is not provided by last.fm. 
#
For 97% songs, both of these queries were successful, which resulted in 3,136,615 songs for which genre membership is available (As we will see soon, a more substantial bottleneck lies elsewhere). 
#
In total there are 885,630 tags associated with the 3.1 million songs. 
# 
I will describe later on how these are filtered down. 

# Last.fm however was no exclusive place for avant-garde audiences, as mainstream artists and established genres are ~strongly present~. 
# # 
# Awarded multiple times for its innovativeness, last.fm stood for a time period in the 2000s for a new way of consuming and interacting with music. 
# # 
# New genres in this period of time are likely to have left a trace in the digital listening logs
# TRUE BUT THEN LOGS DON"T SAY ANYTHING ABOUT THEIR CHANCES

*** AcousticBrainz and Prototype construction
# unclear if lfm uses acoustic features

**** prototypes more justifiable than exemplars

One might (correctly) argue that it is already possible to generate a model of the semi-lattice structure of genres without reference to their attributes. 
#
It is for example possible to use the song-tag links to generate measures of co-occurence to infer a genre hierarchy:
#
Genre X might be a subset of genre Y if most or all songs of genre X are also members of the much larger genre Y. 
#
However, such a definition is /extensional/ and corresponds more to the exemplar model than an /intensional/ feature-based prototype parencite:Murphy_2004_concepts. 
# 
It would therefore be much more cognitively expensive as large numbers of objects would have to be stored, whereas a prototype is much due to its level of abstraction ~more compact~ [fn::It is nevertheless worth noting though that despite a lacking theoretical foundation this is likely the underlying principle of last.fm's recommendation system as there is no indication that last.fm anywhere uses musicological features (Spotify on the other hand seems to integrate musicological features in their services, as it makes them accessible via the API).].


**** actual features
 # (and more importantly, the meaning vis-a-vis other genres) 
A thoroughly theoretically-informed cognitive model therefore requires information regarding the features of the items, from which then (as category memberships are known) prototypes can be inferred. 
#
For this purpose I use the AcousticBrainz project [fn::https://acousticbrainz.org], a joint effort of the Music Technology Group at Universitat Pompeu Fabra in Barcelona and the /MusicBrainz/ aiming to provide detailed musicological information on a large number of tracks. 
#
AcousticBrainz provides information on two levels: 
# 
Low-level data is comprised of more technical characteristics as measures for loudness, dynamics and spectral shape of a signal, rhythm descriptors and tonal information such as keys and scales, which results in hundreds of variables whose specific meaning is hard to discern. 
#
High-level data however consists of a of summarizing constructs based on the low-level data obtained through supervised machine learning. 
# 
As evaluating the highly technical aspect of low-level musicological data generation is beyond the possibilities of this project, I exclusively use the high level-data as I assume that it captures meaningful differentiation in terms of how songs sound. 
#
In particular, I use 12 dimensions of the high-level data which describe each track in terms of danceability, gender (of vocals), timbre, tonality, voice (contrasted against instrumentality), acoustic-ness (vs non-acoustic), aggressiveness, electronic-ness (vs non-electronic), happiness, party-ness, relaxed-ness, and sadness. 
# 
Each of the dimension ranges from 0 to 1. 
# 

**** Data availability
# 
As the data of AcousticBrainz requires much more active processing than the mere registering done by last.fm and MusicBrainz, it is to be expected that coverage would be substantially worse. 
#
Of the 3.1 million songs for which genre metadata was retrieved from last.fm and MusicBrainz, only 1,318,900 had musicological information included by in AcousticBrainz. 
#
As there is likely some motivation to process more popular tracks, the 1.3 million tracks for which musicological information is available constitute 67% of the listening events.  
#
While coverage is therefore far from perfect, I nevertheless assume this amount is sufficient to generate a general picture of the musical landscape in terms of acoustic features. 
#
As there is no way to use a song in genre construction without information about its features, I limit all substantial analysis to the the 1.3 million songs for which such feature information is available. 

**** binominal distributions

During preliminary investigation, it became clear that the classifiers which produce the high level dimensions are geared towards producing unambiguous classifications of tracks, which results in bimodal distributions where most tracks are situated on the extremes of the scales. 
# NOT CONVINCING
This is not necessarily a reason for concern: 
#
Features can certainly be described as binary, in fact [[textcite:Smith_1981_categories][p.12]] see the lack of dimensionality as the defining characteristic of a feature vis-a-vis a dimension. 
#
Since multiple dimensions are included, binary features would also not imply binary category memberships. 
# 
However, most of the dimensions would not be intuitively understood as binary. 
#
Another argument for explicitly modeling the disjointedness concern typicality judgments. 
#
While item typicality is not the focus of investigation, it is worth taking into account generally. 
#
If we imagine a bimodal probability distribution over a single feature with roughly equally sized peaks, a prototype that would just use the mean as the typical value for this dimension would position the most typical value in the valley between the peaks. 
# 
Items who would be located close to it would, according to the prototype, be classified as highly typical. 
#
Actual typical items, which are located in either of the peaks where the probability mass is concentrated, would be regarded as highly atypical given their distance from the prototype. 
#
While no single reason strictly requires to explicitly model the bimodality of the probability distributions, it seems nevertheless preferable to do so as it coincides with a generally solid theoretical foundation and allows to capture meaningful variation (The AcousticBrainz Project seems to think so as well, otherwise there would have been little reason to include the gradient of categorization). 
#
I therefore split each dimension into five sub-dimensions which cover a range of 0.2 of the respective dimension (for example, aggressiveness_{0-0.2})
~example figure~
#
This results in a total of 60 features over which the probability distribution of each genre's prototype is constructed. 

**** Contrast to Piazzai
It would have also been possible to operationalize the genres within a 12-dimensional space, in which the (in the case of binary classification, 2^12 = 4096) cells would constitute the features (cf. cite:Ruef_2000_emergence,Piazzai_concepts). 
#
I however decided against this approach as it would imply that attributes are always evaluated together. 
#
While there is evidence of parallel processing parencite:Strauss_1997_cognitive, this does not imply that combinations of features form the basis of comparison[fn::It is also apparent that the number of possible combinations make this approach implausible. 4096 feature combinations might still be imaginable, the number of possible combinations increases strongly with the degree of each dimension, such as 531,441 for 3 subdivisions and 16,777,216 for 4 subdivisions]. 
#
It would also imply that genres who completely align on all dimension save for one on which they would be completely diverged would occupy completely separate regions of the feature space. 
#
Similarly, textcite:Steyvers_2005_structure argues against high-dimensional semantic spaces as they fail to accurately represent similarity judgments between different levels of abstraction: 
#
Objects are judged most similar to their superordinates (which is to be expected from a standpoint of feature overlap), which requires high dimensionality, which in turn might cause problems for similarity judgment between objects ~source~
# 
Instead, textcite:Steyvers_2005_structure favor probability distributions over features, which is the approach I have taken here. 

**** Prototype construction
# 
With the process of the feature processing established, it is possible to construct prototypes for the genres. 
#
For each timeperiod, I take all songs of a genre, and weight their contribution to the genre by their playcount as well as by their gradient membership of the genre. 
#
Technically, this is achieved for each genre by constructing a histogram for each dimension with five bins, in which songs are weighted by the product of their playcount and tag weight. 
#
As most songs have multiple songs, they hence contribute with varying influence to multiple genres, causing the musicological features to be weighted with great detail.
# 

**** Cutoffs
A number of cutoffs are introduced to construct meaningful genres: 
#
Songs where only considered if they had an weighted aggregate playcount greater than 5 to prevent the songs that with little influence to slow down the analysis. 
# 
As all major measures are thoroughly weighted by playcount, I am fairly confident this does not bias the results. 
# 
A tag needs to occur on at least 20 unique songs with a minimum absolute weight of 8 and a minimum relative weight of 0.075.
# 
This step both excludes idiosyncratic tags as well as ensures that genres have sufficient information to properly estimate similarity measures (discussed below) which might be biased if the content of a genre cannot be sufficiently established. 
# 
Furthermore, each genre needs at least 8 unique artists, and no more than 50% of the songs and 70% of the tag-weighted playcount is allowed to be of a single artist. 
# 
This step was implemented to exclude 'artist-genres' where lastfm users (or perhaps other parties) apparently felt the need to tag songs of famous artists (for example Eminem, Metallica, Rihanna) with the artist name [fn::While the process of institutionalization that turns a name into a category ("Kafkaesque", "Foucauldian", "Bourdieusian") is certainly worth investigating, the mere labeling of artistic works with their creators which seems to be the case here does not constitute such a process of abstraction.]
#

*** Hierarchy construction
# 
While by now we have estimated the musicological content of all genres, this does not yet result in knowledge about their hierarchical structure. 
#
To infer such a asymmetric relationships, I combine the observation by [[textcite:Smith_1981_categories][p.118]] that a concept is rated most similar to its superordinate with the recommendation of textcite:Hannan_2019_concepts to use the Kullback-Leibler Divergence as measurement of informativeness.
# 
The Kullback Leibler Divergence (KLD) in turn is defined as 
\begin{equation*}
KLD(P_1||P_2) = \sum\limits_{x \in \mathbb{G}} P_1(x)  \log \left( \frac{P_1(x)}{P_2(x)} \right)
\end{equation*}
with P_1 and P_2 as probability distributions over G features. 
#
Most importantly, it is an asymmetric measure, meaning that the KLD between probability distribution P_1 and P_2 differs from the KLD between P_2 and P_1. 
#
While this property is often undesirable, it is here crucial here as hierarchical relations are by definition directional [[parencite:Hannan_2019_concepts][p.55]], as a genre cannot be both superordinate and subordinate of another genre. 
# 
To infer the hierarchical structure, the resulting 60 features are used to calculate the Kullback-Leibler Divergence between all genres, which, given the asymmetry of the measurement, results in an asymetric quadratic matrix. 
# 

**** alternatives
It is worth for a moment to reflect on the potential alternatives of hierarchy construction. 
#
In particular, I considered the possibility to use the feature overlap approach outlined by textcite:Tversky_1977_similarity. 
#
Yet to compute an asymmetric measure based on straightforward overlap, variation in the features is required between concepts (in the sense that not all features are present for all concepts), or if the same features are used for all concepts, variation is present in the sum of weights. 
# 
If all features have the same amount of total weights, a comparison between two concepts will result in a certain overlap of which the proportion to the all features will be the same for both genres, which therefore results in a symmetric measurement. 
#
This condition of equal sum of weights is precisely the case for two genres as each item is measured on the same features (the twelve dimensions produced by AcousticBrainz further processed into 5 sub-dimensions each), for which the summed weights are identical for each genre. 
# I investigated whether the weights could be computed in a way to allow variation in their total sums for example by introducing thresholds.
# # 
# However this causes some tags which cover a wide array of songs such as "cover" (or curiously, "aggressive") 
#
I therefore use the KLD which is better (or more precisely, only) suited if concepts are defined over the same probability space, which still captures the general idea of feature overlap but differs in operationalization. 

**** thresholds
# 
A judgment has to be made how the Kullback-Leibler divergences constitute concept-subconcept relationships. 
# 
It might be possible to set a fixed threshold under which every relation is considered a concept-subconcept relations, but this proved to be an unsatisfying: 
# maybe in footnote? separate sentences
# 
If a rather low threshold is chosen (KLD < 0.1), it is possible to achieve a plausible set of concept-subconcept relations, however large numbers of genres (~50%) are being excluded for further analysis as their lowest KLD lay above their threshold. 
# 
However, if the threshold is increased sufficiently to include all or most genres (KLD > 0.3), parent-child relationship increase by order of magnitudes, resulting in network densities (the number of actual links divided by the number of possible links) of up to 0.2. 
# 
Large amount of out-going links (out-degrees) are to some extent plausible for the most general genres (in this case, rock and metal) as these are likely to have dozes of children (for example in the final dataset, there are 110 genres which contain the string "metal", and 146 which contain "rock"). 
# 
Conversely, it is implausible that many genres have dozens of parents, which is inadvertently the case when using a high threshold:
# 
While it is certainly possible for genres to have multiple parents, it seems implausible that the hybrids would still be meaningful concepts if they were influenced by dozens of parents [fn::A ironic play on this large amount of parents is the genre 'industrial jungle pussy punk', which was deliberately coined by the group Mindless Self Indulgence to parody overly specific genres, but yet incorporates much fewer genres than most genres would under a high KLD threshold]
#

**** lowest scoring parents
# 
However, here again we can exploit the fact that concepts are rated most similar to their superordinate [[parencite:Smith_1981_categories][p.118]], as it allows to select as parent(s) for each genre the genre(s) which the genre has the least divergence from. 
# 
While it requires to set the number of parents for each genre in advance, it is possible to avoid the problem of unrealistically high amounts of genre-subgenre relations - or more precisely, unrealistically high amounts of parents[fn::It might be possible to estimate the amount of parents more flexibly from its features, size and/or KLD values, which however would require further investigation]. 
# 
It also allows to gain information on all genres (particularly atypical ones), which is crucial genres constitute the unit of analysis in the final model, and hence to capture more variation in typicality and avoid bias towards genres similar to their parents. 
#
To be able to account for hybrids, which I assume constitute the vast amount of the genres, I have set the number of parents to three for all genres. 
# 
While there are losses in accuracy for genres that clearly diverge (this is most apparent in the most general genres such as rock and metal, which now also are forced to have three parents each), the benefits of this trade-off - information on all genres and variation in typicality - appear to me to be worth the cost.
# 

*** example CS
#+label: gnr_nw
#+caption: Exemplary genre network
[[file:figures/acst_spc5.pdf]]

An example of a classification system generated in this fashion is shown in figure [[gnr_nw]] (it is however not an graph that is used for eventual measurement, as these are considerably larger and only marginally useful for visual presentation). 
#
When zooming it, it can be seen that every genre has three parents (incoming arrows), although the directed nature of the links allows the more general genres (e.g. electronic, pop, rock) to be parents to large numbers of subgenres, whereas most genres have not produced any subgenres. 
# 
It can furthermore be seen that graph depicts hierarchical relations, there is no clear ordered hierarchy as argued for by (or more precisely, attributed to) the classical view parencite:Quillian_1966_memory: 
#
Instead a large amount of combination of different elements is visible. 
#
While regions of particular styles are still identifiable, such as metal in the bottom or pop in the top right, these do not constitute strict taxonomic subcategories but rather systems of family resemblance in which the boundaries between styles are blurred. 

*** where to put time thing? 
#
The temporal element of listening logs allows to investigate the longitudinal development of genre survival in a very flexible way as listening events can be selected for any time-period of interest (On a technical level, this is obtained with ClickHouse, a database system geared towards longitudinal data). 
#
This flexibility however also requires to consciously choose time intervals, as no natural event such as publications in yearly textcite:Rao_2005_crossing or quarterly cite:Kennedy_2008_counted intervals. 
#
Since my measures depend heavily on playcount (both in genre selection as well as generated variables), I considered it crucial to have equally sized intervals. 
#
I eventually decided on intervals of 12 weeks, which results in 29 time periods from beginning of 2006 to the end of September of 2012. 
#
While in this time period there were no revolutions in the musical industry parencite:Peterson_1990_advent, with the great amount of detailed data available it should still be possible to identify the entire lifespan particularly of small and emerging genres. 
#

**** time caveat too
# 
It is furthermore important to state what changes and remains stable. 
#
While the listening logs accumulate over time and hence allow to reconstruct past listening patterns, no temporal information is available for feature values and genre membership. 
#
The former is of relatively little concern, as given the relatively short period of time the features with which music is perceived are likely to stay relatively unchanged. 
#
More potential to interfere with accurate genre identification is the lack of longitudinal information on genre membership. 
#
While the tags of each song have accumulated over time, the last.fm API only returns the aggregate labels given to a song at the time of the request. 
#
It is therefore imaginable that songs who were categorized in one genre at one point in time, and with a later emerged one at a later point in time indicate the presence of the second genre at a time where it was not yet developed. 
#
Similarly, temporal changes in the gradient of membership are not recoverable from the available aggregate. 
#
However, I think that this problems has overall little impact on the reconstructing the content of genres at different points in time because the industry is rather innovative and constantly churns out new products, causing most songs to accumulate most of their playcount in a rather short amount of time. 
# 
One might argue that textcite:Anand_2000_sensemaking,Anand_2006_charting have shown that the idea of musical industry as constantly innovating is to some extent ideological fabrication as classical works continue to be popular to such an extent that they would constitute a substantial presence in the charts. 
# 
However, it seems unlikely that such classical works are in high danger of recategorization as it is precisely their membership in highly established categories that guarantees their continued popularity in the first place. 
#
While new genres might aim for association to gain legitimacy, it seems unlikely that this would result in blatant retagging of classical works, but would rather by visible through integrating stylistic features. 




*** Key Variables
**** Dependent Variable: Genre Abandonment
# 
The primary variable of interest is the disappearance of a genre. 
# 
However, the informal nature of the categories under investigation complicates the ability to exactly determine their disappearance. 
# 
Whereas disappearance in organizations parencite:Rao_1994_reputation,Kennedy_2008_counted,Singh_1991_change or highly institutionalized categories parencite:Lounsbury_2004_sources is demarcated by formal events such as declaration of bankruptcy or removal from category-defining institutions, no natural event indicates the disappearance of a last.fm tag. 
# 
As such, their abandonment has to be inferred from their use frequencies. 
#
Since I generate measures for each time period separate, a genre can be classified as having died in period t when in period t+1 it fails any of the thresholds discussed. 
# 
A further complication arises from the fact that genres can display spotty histories: 
# 
After being considered alive in time period t, it may be considered dead in period t+1 but through a gain in popularity be considered alive again in period t+2. 
# 
To ensure that genres have actually disappeared, I do not require them therefore to have died at least three time periods before the end of the observation period. 
#
In the case of abandoned genres with spotty histories the last time period in which they were active is coded as the time period in which they were active. 

*** predictors concepts
**** Predictor: Informativeness 
# 
Informativeness describes the extent to which a subordinate genre differs from their parents, which for each genre are the three least-divergent genres. 
# 
Informativeness is therefore operationalized as the sum of the Kullback-Leibler divergences between a genre and its three superordinates (since all genres have three parents, it makes no difference whether the mean or sum is taken). 
#


**** Predictor: Distinctiveness
# 
Distinctiveness concerns the relation between a genre and the genres in the same cohort, which is defined through parent genres. 
# 
As such, it indicates the extent to which a genre stands out. 
# 
It hence is operationalized as the mean of a distance metric between a genre and the other genres of its cohort parencite:Piazzai_concepts. 
# 
However, an issue arises with the choice of the distance metric: 
# 
A central aspect of concept similarity (and distance) is asymmetry parencite:Tversky_1977_similarity, which arises due from feature overlap. 
#
However, the Kullback-Leibler divergence, which had allowed asymmetric similarity judgments to infer the hierarchical structure of the classification framework, is not necessarily defined for relations between cohort members. 
# 
Since the Kullback-Leibler divergence is measured  from one genre to another, it requires the first to be a subset of the second as otherwise the lack of features cause it to be undefined.  
# 
While all songs are measured on the same variables, the splitting of these dimensions into five cells for each features can result in genres having values of zero for some of the features. 
# 
This is no problem for inferring the hierarchical structure as it is constructed with only the three lowest divergences (in practice Python returns undefined divergences as undefined) and hence uses only a small subset (in the case of 1k genres, only 3k/1k*1k-1=0.003=0.3% of the computed KLDs are used for network construction), of which by definition all are defined. 
#
Within cohorts however, Kullback-Leibler divergences can be undefined. 
# 
While textcite:Hannan_2019_concepts recommend the Kullback-Leibler divergence for distinctiveness measurements as well, it cannot reliably be used for this task.
#
The genres also have still the same weighted total amount of features as the presence of zero values on some features is offset by higher values elsewhere, which would result in a measure of similarity based on feature overlap to be symmetric as well. 
# 
Since I could not employ a true asymmetric measurement for distinctiveness,  use the mean cosine similarity between a genre and its cohort members (which is what textcite:Hannan_2019_concepts eventually resort to as well).
# 
While it might that asymmetry is less central for comparisons within cohorts as there due to the shared roots overall similarities can be expected to be lower  than within a random selection of genres, this specific issue clearly requires further investigation. 


*** predictor ecology

**** Predictor: bandwagoning, parent popularity
# 
Parents might not only in matter in terms of how informative genres are with regards to them. 
#
It might also be relevant how large parents are: 
#
Roots with large audiences might provide more viewers that can insulate its children, as well as provide symbolic legitimation. 
#
On the contrary, large parents might attract many genres, and hence increase competition. 
#
To investigate both mechanisms, a linear and a squared coefficient for parent size are added. 




**** is cohort volume indicator of density? kinda is about how much listening is going on 
# 
An equivalent of the dual relationships to roots can be found for cohorts. 
#
They might not only be relevant in terms of distinctiveness as the concept theories elaborate, but also matter in terms of ecological characteristics. 
#
Density plays a central role in this regard, and the typical arguments of density dependence made for organizations apply to genres as organizational forms as well: 
#
Cohorts with a low number of genres offer opportunities to expand as they provide legitimation, while crowded cohorts are expected to be dominated by competition. 
#
In line with the traditional approach, a genre's cohort density is first operationalized as the number of other genres with which it has at least one parent in common[fn::Genres with multiple common parents are only considered once], for which both a linear and a quadratic term are added. 
#


Additionally, the high detail of the data further allows to operationalize a cohort in terms of playcount. 
#
A cohort may consist of only have a handful of genres, but if these are all highly popular, one might expect different cohort effects compared to an equally-sized cohort of genres of low or medium popularity. 
# 
I have therefore added additional (linear and quadratic) measure of cohort density by summing up the (tag-weighted) playcounts of each genre in the cohort. 
#  


However, the playcount information allows to construct even further metrics to characterize a genre's environment. 
#
First, it allows to estimate the extent to which the genre 'fills out' its cohort by dividing the genre's playcount by the total cohort playcount. 
#
Secondly, it is possible to see how large in terms of playcount a genre is in comparison with the average genre in cohort in terms by playcount by dividing the genre's playcount by the mean cohort playcount. 
#



**** Controls
# 
Most relevant controls concern the size of a genre, as genres with large following are less likely to be abandoned. 
# 
I therefore control for the total weighted playcount of a genre by summing up the playcounts for each song weighted by the extent to which it belongs to any genre. 
# 
I further control for the number of releases in the time period in question using the release date data from MusicBrainz. 
# 
I also use the release information to calculate the average age the songs in the genre, again weighted by song playcount and tag weight. 
#
Furthermore use the Gini index of playcount by artist to estimate the extent to which a genre is dominated by a small proportion of the artists. 
# 
While tags that were highly dominated by one artist were excluded (see above), variations in evenness are still likely to exist and might impact survival chances. 
# 
Given the phenomenon of gradient multiple membership, it is worth to investigate the extent to which a genre is associated with its items. 
#
I therefore control for the average tag weight of a genre's songs, which is weighted by song playcount. 
# 
~put dist_mean to concept variables?~

***** item similarity
The coal of concepts is to function as distillations of objects which are similar in terms of their features. 
#
Consequently, one might expect that they are more clearly described, less cognitively expensive and ultimately more useful if the items they describe are similar. 
#
A key question is therefore the range of objects that are supposed to be subsumed by a concept. 
#
If they are not very similar, a concept might be harder to keep track of. 
#
Large ranges can also indicate conflict or lack of disagreement over what a category means in terms of content. 
#
To capture this item similarity, I calculate the mean cosine similarity between the songs of a genre (or a random sample of 750, if there are more songs in the genre). 
#
The comparisons are weighted by the sum of the tag weights multiplied with the playcounts of both songs to be compared. 



*** Survival Analysis
To estimate the impact of the covariates on the survival chances I follow similar studies cite:Kennedy_2008_counted,Negro_2011_winemaking and use a Cox proportional hazards model with piecewise exponential specification. 
#
In this framework, hazard base rate is estimated for each time spell. 
# 
This allows the hazard rate to vary over time, which is required due to substantial changes in the last.fm usercounts ~figure~. 
# 
While in traditional studies such a model is difficult as measures are often not available for all participants for all time spells, no such limitations exist for working with trace data which can be aggregated to arbitrary intervals. 

**** parameter interpretation
Coefficients are logarithms of hazard ratios relative to the baseline hazards parencite:Brostrom_2012_event. 
# 
Risk increases with e^\beta when the variable in increased by one unit (which for most variables is one standard deviation), and is therefore interpreted as a relative risk ratio or hazard ratio. 
#
For example, given a coefficient of 0.5, the relative risk of genre abandonment increases with e^{0.5} = 1.65 for a one-unit increase of the corresponding dependent variable. 


** Results
# 
Table X shows the effects of the variables regarding the information content. 
#



*** concepts

*** ecology

** Discussion

** Conclusion



* data
#+include: "~/Dropbox/gsss/thesis/text/data.org"




* refs :ignhead:
#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}

** export :noexport:
#+BEGIN_SRC emacs-lisp
  (org-babel-tangle)
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                      'comment 'identity))
      do
      (setf (buffer-substring (org-element-property :begin comment)
                  (org-element-property :end comment))
            "")))

  (let ((org-export-before-parsing-hook '(delete-org-comments)))
    (switch-to-buffer (org-latex-export-to-pdf)))
#+END_SRC

#+RESULTS:
: #<buffer /home/johannes/Dropbox/gsss/thesis/text/thesis.pdf>

